'use strict';function y(e,a,b,d,g){e.v.sc(e.ab,a,b,d,g)}function C(e,a,b,d){e.v.ea?y(e,a,b,d):e.v.nf()._OnMessageFromDOM({type:"event",component:e.ab,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function I(e,a,b){e.v.C(e.ab,a,b)}function K(e,a){for(const [b,d]of a)I(e,b,d)}function L(e){e.Sb||(e.v.Ye(e.he),e.Sb=!0)}function M(e){e.Sb&&(e.v.jg(e.he),e.Sb=!1)}window.yb=class{constructor(e,a){this.v=e;this.ab=a;this.Sb=!1;this.he=()=>this.wa()}hd(){}wa(){}};
function O(e){-1!==e.Pa&&(self.clearTimeout(e.Pa),e.Pa=-1)}window.Pe=class{constructor(e,a){this.Nc=e;this.Kg=a;this.Pa=-1;this.Ub=-Infinity;this.ie=()=>{this.Pa=-1;this.Ub=Date.now();this.gb=!0;this.Nc();this.gb=!1};this.Rd=this.gb=!1}c(){O(this);this.ie=this.Nc=null}};"use strict";
function P(e,a){const b=a.elementId,d=e.md(b,a);e.V.set(b,d);a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{Q(e,"elem-focused",b)});d.addEventListener("blur",()=>{Q(e,"elem-blurred",b)});e.$a&&document.body.appendChild(d)}function R(e,a,b){I(e,a,d=>{const g=e.V.get(d.elementId);return b(g,d)})}function Q(e,a,b,d){d||(d={});d.elementId=b;y(e,a,d)}
window.Be=class extends self.yb{constructor(e,a){super(e,a);this.V=new Map;this.$a=!0;K(this,[["create",b=>P(this,b)],["destroy",b=>{{b=b.elementId;const d=this.V.get(b);this.od(d);this.$a&&d.parentElement.removeChild(d);this.V.delete(b)}}],["set-visible",b=>{this.$a&&(this.V.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.$a){var d=this.V.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";
b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.V.get(b.elementId);this.xd()}],["focus",b=>{{const d=this.V.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.V.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.V.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.V.get(b.elementId).removeAttribute(b.name)}]]);R(this,"get-element",b=>b)}md(){throw Error("required override");}od(){}xd(){throw Error("required override");
}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(n){const c=document.createElement("script");c.async=!1;c.type="module";return n.Wg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=n.$g+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=n;document.head.appendChild(c)})}let d=!1,g=!1;function m(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(n){}d=!0}return g}const p=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let t=new Audio;const B={"audio/webm; codecs=opus":!!t.canPlayType("audio/webm; codecs=opus")&&!p,"audio/ogg; codecs=opus":!!t.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!t.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!t.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!t.canPlayType("audio/mp4"),"audio/mpeg":!!t.canPlayType("audio/mpeg")};t=null;async function E(n){n=
await w(n);return(new TextDecoder("utf-8")).decode(n)}function w(n){return new Promise((c,k)=>{const l=new FileReader;l.onload=q=>c(q.target.result);l.onerror=q=>k(q);l.readAsArrayBuffer(n)})}const x=[];let D=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let J=0;const N=[];self.runOnStartup=function(n){if("function"!==typeof n)throw Error("runOnStartup called without a function");N.push(n)};const f=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Va=class n{constructor(c){this.ea=
c.bh;this.ra=null;this.F="";this.ec=c.Zg;this.vb={};this.Ia=this.ub=null;this.Qb=[];this.jb=this.K=this.Na=null;this.Ma=-1;this.Pg=()=>this.Pf();this.La=[];this.A=c.je;this.hb="file"===location.protocol.substr(0,4);!this.ea||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ea=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ea=!1;if("cordova"===this.A&&this.ea)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.ea=!1)}else this.ea=!1;this.Wb=this.ja=null;"html5"!==this.A&&"playable-ad"!==this.A||!this.hb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.wf(k));this.C("runtime","create-job-worker",()=>this.xf());"cordova"===this.A?document.addEventListener("deviceready",()=>this.Cd(c)):this.Cd(c)}c(){this.yc();this.ra&&(this.ra=this.ra.onmessage=
null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Ke(){return e&&"cordova"===this.A}rc(){const c=navigator.userAgent;return e&&f.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async Cd(c){"macos-wkwebview"===this.A&&this.mg();if("playable-ad"===this.A){this.ja=self.c3_base64files;this.Wb={};await this.cf();for(let l=0,q=c.Qa.length;l<q;++l){var k=c.Qa[l].toLowerCase();this.Wb.hasOwnProperty(k)?
c.Qa[l]={Wg:!0,$g:this.Wb[k]}:this.ja.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ja[k]))}}c.Rg?this.F=c.Rg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.eh&&(this.vb=c.eh);k=new MessageChannel;this.ra=k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Jf(l));this.jb=new self.Le(this);await S(this.jb);"object"===typeof window.StatusBar&&
window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ea?await this.qf(c,k.port2):await this.pf(c,k.port2)}Bc(c){c=this.vb.hasOwnProperty(c)?this.vb[c]:c.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?this.vb["workermain.js"]:"playable-ad"===this.A&&this.ja.hasOwnProperty(c.toLowerCase())?this.ja[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async lc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,
l);if("cordova"===this.A&&this.hb)return c=await this.xb(l.Vg?c:this.ec+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}ya(){return Math.max(window.innerWidth,1)}xa(){return Math.max(window.innerHeight,1)}Bd(c){var k=this.jb;return{baseUrl:this.F,windowInnerWidth:this.ya(),
windowInnerHeight:this.xa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:n.Ta(),projectData:c.jh,previewImageBlobs:window.cr_previewImageBlobs||this.ja,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.hh||"",exportType:c.je,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ih,jobScheduler:{inputPort:k.Uc,outputPort:k.ad,maxNumWorkers:k.Mg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.ec+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ec+"opus.wasm.wasm",isFileProtocol:this.hb,isiOSCordova:this.Ke(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async qf(c,k){var l=this.Bc(c.dh);this.ub=await this.lc(l,this.F,{type:"module",name:"Runtime",Vg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let q=c.gd||[],
v=c.Qa;q=await Promise.all(q.map(r=>this.Ea(r)));v=await Promise.all(v.map(r=>this.Ea(r)));if("cordova"===this.A)for(let r=0,u=c.jc.length;r<u;++r){const z=c.jc[r],H=z[0];if(H===c.ed||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))z[1]=await this.Ea(H)}this.ub.postMessage(Object.assign(this.Bd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:q,engineScripts:v,projectScripts:c.jc,mainProjectScript:c.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...T(this.jb)]);this.Qb=F.map(r=>new r(this));this.Ad();self.c3_callFunction=(r,u)=>this.Na.rf(r,u);"preview"===this.A&&(self.goToLastErrorScript=()=>this.sc("runtime","go-to-last-error-script"))}async pf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Qb=F.map(r=>new r(this));this.Ad();var l=c.Qa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.gd)&&l.unshift(...c.gd);l=await Promise.all(l.map(r=>
this.Ea(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const q=c.ed,v=c.jc;for(let [r,u]of v)if(u||(u=r),r===q)try{u=await this.Ea(u),await b(u),"preview"!==this.A||l[r]||this.Ld(r,"main script did not run to completion")}catch(z){this.Ld(r,z)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))u=await this.Ea(u),await b(u);"preview"===this.A&&"object"!==typeof self.fh.gh?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Bd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:N}),this.Ed(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Ld(c,k){this.Kb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ed(){this.Kb()}Kb(){const c=
window.Sg;c&&(c.parentElement.removeChild(c),window.Sg=null)}async xf(){const c=await U(this.jb);return{outputPort:c,transferables:[c]}}nf(){if(this.ea)throw Error("not available in worker mode");return this.Ia}sc(c,k,l,q,v){this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:q||null,data:l,responseId:null},v)}sd(c,k,l,q,v){const r=J++,u=new Promise((z,H)=>{G.set(r,{resolve:z,reject:H})});this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:q||null,data:l,responseId:r},
v);return u}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Cf(c);if("result"===k)this.Sf(c);else if("runtime-ready"===k)this.Tf();else if("alert-error"===k)this.Kb(),alert(c.message);else if("creating-runtime"===k)this.Ed();else throw Error(`unknown message '${k}'`);}Cf(c){const k=c.component,l=c.handler,q=c.data,v=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(q)}catch(u){console.error(`Exception in '${k}' handler '${l}':`,u);null!==v&&this.Jb(v,!1,""+u);return}if(null===
v)return r;r&&r.then?r.then(u=>this.Jb(v,!0,u)).catch(u=>{console.error(`Rejection from '${k}' handler '${l}':`,u);this.Jb(v,!1,""+u)}):this.Jb(v,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Jb(c,k,l){let q;l&&l.transferables&&(q=l.transferables);this.ra.postMessage({type:"result",responseId:c,isOk:k,result:l},q)}Sf(c){const k=c.responseId,l=c.isOk;c=c.result;const q=G.get(k);l?q.resolve(c):q.reject(c);G.delete(k)}C(c,
k,l){let q=A.get(c);q||(q=new Map,A.set(c,q));if(q.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);q.set(k,l)}static wb(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}Ad(){for(const c of this.Qb)if("runtime"===c.ab){this.Na=c;return}throw Error("cannot find runtime DOM handler");}Jf(c){this.sc("debugger","message",c)}Tf(){for(const c of this.Qb)c.hd()}static Ta(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Md(c){h=!!c}Ye(c){this.La.push(c);this.Lc()}jg(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.yc()}Lc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Pg))}yc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Pf(){this.Ma=-1;for(const c of this.La)c();this.Lc()}Z(c){this.Na.Z(c)}aa(c){this.Na.aa(c)}Kc(){this.Na.Kc()}Eb(c){this.Na.Eb(c)}Je(){return!!B["audio/webm; codecs=opus"]}async Ig(c){c=await this.sd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ie(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}rd(c){return!this.Ie(c)}async Ea(c){return"cordova"===this.A&&(c.startsWith("file:")||this.hb&&this.rd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.xb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async wf(c){const k=c.filename;switch(c.as){case "text":return await this.Ae(k);case "buffer":return await this.xb(k);
default:throw Error("unsupported type");}}ld(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,q)=>{window.resolveLocalFileSystemURL(k,v=>{v.file(l,q)},q)})}async Ae(c){c=await this.ld(c);return await E(c)}zc(){if(x.length&&!(8<=D)){D++;var c=x.shift();this.df(c.filename,c.ah,c.Ug)}}xb(c){return new Promise((k,l)=>{x.push({filename:c,ah:q=>{D--;this.zc();k(q)},Ug:q=>{D--;this.zc();l(q)}});this.zc()})}async df(c,k,l){try{const q=await this.ld(c),v=await w(q);
k(v)}catch(q){l(q)}}mg(){var c={type:"ready"};if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async cf(){const c=[];for(const [k,l]of Object.entries(this.ja))c.push(this.bf(k,l));await Promise.all(c)}async bf(c,k){if("object"===typeof k)this.ja[c]=new Blob([k.str],{type:k.type}),this.Wb[c]=k.str;else{let l=await this.lf(k);
l||(l=this.ff(k));this.ja[c]=l}}async lf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}ff(c){c=this.dg(c);return this.af(c.data,c.Xg)}dg(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||
"";const q=k[2];l="base64"===k[1]||"base64"===q?atob(l):decodeURIComponent(l);return{Xg:c,data:l}}af(c,k){var l=c.length;let q=l>>2,v=new Uint8Array(l),r=new Uint32Array(v.buffer,0,q),u,z;for(z=u=0;u<q;++u)r[u]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=3;l--;)v[z]=c.charCodeAt(z),++z;return new Blob([v],{type:k})}}}"use strict";
{const e=self.Va;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((h,n)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>n(k);c.rel=
"stylesheet";c.href=f;document.head.appendChild(c)})}function t(f){return new Promise((h,n)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>n(k);c.src=f})}async function B(f){f=URL.createObjectURL(f);try{return await t(f)}finally{URL.revokeObjectURL(f)}}function E(f){return new Promise((h,n)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>n(k);c.readAsText(f)})}async function w(f,h,n){if(!/firefox/i.test(navigator.userAgent))return await B(f);var c=await E(f);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),q=k.getAttribute("height");if(!l.includes("%")&&!q.includes("%"))return await B(f)}k.setAttribute("width",h+"px");k.setAttribute("height",n+"px");c=(new XMLSerializer).serializeToString(c);f=new Blob([c],{type:"image/svg+xml"});return await B(f)}function x(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const D=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(f){F.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function G(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await B(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const h=f.getBoundingClientRect();document.body.removeChild(f);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(f,h,n,c,k){f=await w(f,h,n);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(f,0,0,h,n);return l};let J=!1;document.addEventListener("pause",()=>J=!0);document.addEventListener("resume",()=>J=!1);function N(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.wb(class extends self.yb{constructor(f){super(f,"runtime");this.Wd=!0;this.Oa=-1;this.cd="any";this.Nd=this.Od=!1;this.Xc=
this.rb=this.Aa=null;f.C("canvas","update-size",c=>this.ag(c));f.C("runtime","invoke-download",c=>this.Hf(c));f.C("runtime","raster-svg-image",c=>this.Qf(c));f.C("runtime","get-svg-image-size",c=>this.Ef(c));f.C("runtime","set-target-orientation",c=>this.Yf(c));f.C("runtime","register-sw",()=>this.Rf());f.C("runtime","post-to-debugger",c=>this.Gd(c));f.C("runtime","go-to-script",c=>this.Gd(c));f.C("runtime","before-start-ticking",()=>this.vf());f.C("runtime","debug-highlight",c=>this.yf(c));f.C("runtime",
"enable-device-orientation",()=>this.$e());f.C("runtime","enable-device-motion",()=>this.Ze());f.C("runtime","add-stylesheet",c=>this.tf(c));f.C("runtime","alert",c=>this.uf(c));f.C("runtime","hide-cordova-splash",()=>this.Ff());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||x(k)||c.preventDefault()});const n=f.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);n.addEventListener("selectstart",
A);n.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),n.addEventListener("pointerdown",A)):n.addEventListener("touchstart",A);this.ob=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.bg());window.addEventListener("fullscreenchange",
()=>this.Wa());window.addEventListener("webkitfullscreenchange",()=>this.Wa());window.addEventListener("mozfullscreenchange",()=>this.Wa());window.addEventListener("fullscreenerror",c=>this.Gc(c));window.addEventListener("webkitfullscreenerror",c=>this.Gc(c));window.addEventListener("mozfullscreenerror",c=>this.Gc(c));f.rc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):x(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.cg(c);this.Ja=new Set;this.Xb=new WeakSet;this.qa=!1}vf(){"cordova"===this.v.A?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!J)}}hd(){window.addEventListener("focus",()=>
this.Ya("window-focus"));window.addEventListener("blur",()=>{this.Ya("window-blur",{parentHasFocus:N()});this.ob=0});window.addEventListener("focusin",h=>{h=h.target;(D.has(h.tagName.toLowerCase())||x(h))&&this.Ya("keyboard-blur")});window.addEventListener("keydown",h=>this.Fd("keydown",h));window.addEventListener("keyup",h=>this.Fd("keyup",h));window.addEventListener("dblclick",h=>this.Hc("dblclick",h,d));window.addEventListener("wheel",h=>this.Lf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Cc(h);this.Xa("pointerdown",h)}),this.v.ea&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.Pe(()=>this.jf(),5),this.rb.Rd=!0,window.addEventListener("pointerrawupdate",h=>this.Of(h))):window.addEventListener("pointermove",h=>this.Xa("pointermove",h)),window.addEventListener("pointerup",h=>this.Xa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Xa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Cc(h);this.Ic("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Ic("pointermove",h)),window.addEventListener("mouseup",h=>this.Ic("pointerup",h)),window.addEventListener("touchstart",h=>{this.Cc(h);this.Ib("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Ib("pointermove",h)),window.addEventListener("touchend",h=>this.Ib("pointerup",h)),window.addEventListener("touchcancel",h=>this.Ib("pointercancel",h)));const f=()=>this.Kc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",
f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}Ya(f,h){y(this,f,h||null,m)}ya(){return this.v.ya()}xa(){return this.v.xa()}bg(){const f=this.ya(),h=this.xa();this.Ya("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Ta()});this.v.rc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Hd(f,h,0))}kg(f,h,n){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Hd(f,
h,n),48)}Hd(f,h,n){const c=this.ya(),k=this.xa();this.Oa=-1;c!=f||k!=h?this.Ya("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Ta()}):10>n&&this.kg(c,k,n+1)}Yf(f){this.cd=f.targetOrientation}Eg(){const f=this.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(f):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(f):screen.mozLockOrientation?h=screen.mozLockOrientation(f):screen.msLockOrientation&&(h=screen.msLockOrientation(f));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Wa(){const f=e.Ta();f&&"any"!==this.cd&&this.Eg();y(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.ya(),innerHeight:this.xa()})}Gc(f){console.warn("[Construct 3] Fullscreen request failed: ",f);y(this,"fullscreenerror",
{isFullscreen:e.Ta(),innerWidth:this.ya(),innerHeight:this.xa()})}Jc(f){f?this.v.yc():this.v.Lc();y(this,"visibilitychange",{hidden:f})}Fd(f,h){"Backspace"===h.key&&A(h);const n=b.get(h.code)||h.code;C(this,f,{code:n,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Lf(f){y(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,
timeStamp:f.timeStamp},d)}Hc(f,h,n){a(h)||C(this,f,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},n)}Ic(f,h){if(!a(h)){var n=this.ob;"pointerdown"===f&&0!==n?f="pointermove":"pointerup"===f&&0!==h.buttons&&(f="pointermove");C(this,f,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:n,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.ob=h.buttons;this.Hc(h.type,h,g)}}Xa(f,h){if(this.rb&&"pointermove"!==f){var n=this.rb;n.gb||(O(n),n.Ub=Date.now())}n=0;"mouse"===h.pointerType&&(n=this.ob);C(this,f,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:n,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(n="mousemove","pointerdown"===f?n="mousedown":"pointerup"===f&&(n="mouseup"),this.Hc(n,h,g),this.ob=h.buttons)}Of(f){this.Xc=f;f=this.rb;if(-1===f.Pa){var h=Date.now(),n=h-f.Ub,c=f.Kg;n>=c&&f.Rd?(f.Ub=h,f.gb=!0,f.Nc(),f.gb=!1):f.Pa=self.setTimeout(f.ie,Math.max(c-n,4))}}jf(){this.Xa("pointermove",this.Xc);this.Xc=null}Ib(f,h){for(let n=0,c=h.changedTouches.length;n<c;++n){const k=h.changedTouches[n];C(this,f,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Cc(f){window!==window.top&&window.focus();this.Dd(f.target)&&document.activeElement&&!this.Dd(document.activeElement)&&document.activeElement.blur()}Dd(f){return!f||f===document||
f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}$e(){this.Od||(this.Od=!0,window.addEventListener("deviceorientation",f=>this.Af(f)),window.addEventListener("deviceorientationabsolute",f=>this.Bf(f)))}Ze(){this.Nd||(this.Nd=!0,window.addEventListener("devicemotion",f=>this.zf(f)))}Af(f){y(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},
d)}Bf(f){y(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},d)}zf(f){let h=null;var n=f.acceleration;n&&(h={x:n.x||0,y:n.y||0,z:n.z||0});n=null;var c=f.accelerationIncludingGravity;c&&(n={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=f.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});y(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:n,rotationRate:c,interval:f.interval,timeStamp:f.timeStamp},
d)}ag(f){const h=this.v.K;h.style.width=f.styleWidth+"px";h.style.height=f.styleHeight+"px";h.style.marginLeft=f.marginLeft+"px";h.style.marginTop=f.marginTop+"px";this.Wd&&(h.style.display="",this.Wd=!1)}Hf(f){const h=f.url;f=f.filename;const n=document.createElement("a"),c=document.body;n.textContent=f;n.href=h;n.download=f;c.appendChild(n);n.click();c.removeChild(n)}async Qf(f){var h=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);
h=h?await createImageBitmap(f,h):await createImageBitmap(f);return{imageBitmap:h,transferables:[h]}}async Ef(f){return await self.C3_GetSvgImageSize(f.blob)}async tf(f){await p(f.url)}Kc(){var f=[...this.Ja];this.Ja.clear();if(!this.qa)for(const h of f)(f=h.play())&&f.catch(()=>{this.Xb.has(h)||this.Ja.add(h)})}Z(f){if("function"!==typeof f.play)throw Error("missing play function");this.Xb.delete(f);let h;try{h=f.play()}catch(n){this.Ja.add(f);return}h&&h.catch(()=>{this.Xb.has(f)||this.Ja.add(f)})}aa(f){this.Ja.delete(f);
this.Xb.add(f)}Eb(f){this.qa=!!f}Ff(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}yf(f){if(f.show){this.Aa||(this.Aa=document.createElement("div"),this.Aa.id="inspectOutline",document.body.appendChild(this.Aa));var h=this.Aa;h.style.display="";h.style.left=f.left-1+"px";h.style.top=f.top-1+"px";h.style.width=f.width+2+"px";h.style.height=f.height+2+"px";h.textContent=f.name}else this.Aa&&(this.Aa.style.display="none")}Rf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Gd(f){window.c3_postToMessagePort&&
(f.from="runtime",window.c3_postToMessagePort(f))}rf(f,h){return this.v.sd(this.ab,"js-invoke-function",{name:f,params:h},void 0,void 0)}uf(f){alert(f.message)}cg(f){"entered-fullscreen"===f?(e.Md(!0),this.Wa()):"exited-fullscreen"===f?(e.Md(!1),this.Wa()):console.warn("Unknown wrapper message: ",f)}})}"use strict";
async function S(e){if(e.Jg)throw Error("already initialised");e.Jg=!0;var a=e.dc.Bc("dispatchworker.js");e.Qc=await e.dc.lc(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Uc=a.port1;e.Qc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.ad=await U(e)}function T(e){return[e.Uc,e.ad]}
async function U(e){const a=e.Xd.length;var b=e.dc.Bc("jobworker.js");b=await e.dc.lc(b,e.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;e.Qc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);e.Xd.push(b);return g.port1}
self.Le=class{constructor(e){this.dc=e;this.F=e.F;this.F="preview"===e.A?this.F+"workers/":this.F+e.ec;this.Mg=Math.min(navigator.hardwareConcurrency||2,16);this.Qc=null;this.Xd=[];this.ad=this.Uc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Va({bh:!0,dh:"workermain.js",Qa:["scripts/c3runtime.js"],jc:[],ed:"",Zg:"scripts/",gd:[],je:"html5"}));"use strict";
{const e=180/Math.PI;self.fa=class extends self.yb{constructor(a){super(a,"audio");this.Pb=this.f=null;this.Rb=this.Tc=!1;this.ta=()=>this.Fg();this.ca=[];this.D=[];this.ia=null;this.Yd="";this.Zd=-1;this.qb=new Map;this.Yc=1;this.qa=!1;this.dd=0;this.hc=1;this.Rc=0;this.ae="HRTF";this.Sd="inverse";this.be=600;this.$d=1E4;this.de=1;this.Ud=this.bd=!1;this.ge=this.v.Je();this.da=new Map;this.Ga=new Set;this.Vc=!1;this.Zc="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Kf(b,d);this.Ob=null;
self.C3Audio_GetOutputStream=()=>this.Df();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.ef(b)],["play",b=>this.eg(b)],["stop",b=>this.Cg(b)],["stop-all",()=>this.Dg()],["set-paused",b=>this.vg(b)],["set-volume",b=>this.Ag(b)],["fade-volume",b=>this.kf(b)],["set-master-volume",b=>this.tg(b)],["set-muted",b=>this.ug(b)],["set-silent",b=>this.xg(b)],["set-looping",b=>this.sg(b)],["set-playback-rate",b=>this.wg(b)],["seek",b=>this.lg(b)],["preload",b=>this.fg(b)],["unload",b=>
this.Gg(b)],["unload-all",()=>this.Hg()],["set-suspended",b=>this.yg(b)],["add-effect",b=>this.yd(b)],["set-effect-param",b=>this.pg(b)],["remove-effects",b=>this.hg(b)],["tick",b=>this.$f(b)],["load-state",b=>this.If(b)]])}async ef(a){a.isiOSCordova&&(this.bd=!0);this.dd=a.timeScaleMode;this.ae=["equalpower","HRTF","soundfield"][a.panningModel];this.Sd=["linear","inverse","exponential"][a.distanceModel];this.be=a.refDistance;this.$d=a.maxDistance;this.de=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ge||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.zd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.zd()};this.Pb=this.f.createGain();this.Pb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.mc();try{await Promise.all(a.preloadList.map(d=>this.Gb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}zd(){this.Rb||(this.Tc=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Rb=!0)}gf(){this.Rb&&(this.Tc=!0,window.removeEventListener("pointerup",this.ta,!0),window.removeEventListener("touchend",
this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Rb=!1)}Fg(){if(!this.Tc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.gf()}}X(){return this.f}mc(){return this.f.currentTime}ua(){return this.Pb}pd(a){return(a=this.da.get(a.toLowerCase()))?a[0].P():this.ua()}ke(a,b){a=a.toLowerCase();let d=this.da.get(a);
d||(d=[],this.da.set(a,d));b.rg(d.length);b.zg(a);d.push(b);this.Kd(a)}Kd(a){let b=this.ua();const d=this.da.get(a);if(d&&d.length){b=d[0].P();for(let g=0,m=d.length;g<m;++g){const p=d[g];g+1===m?p.S(this.ua()):p.S(d[g+1].P())}}for(const g of this.na(a))g.Qe(b);this.Ba&&this.Zc===a&&(this.Ba.disconnect(),this.Ba.connect(b))}Ab(){return this.Yc}Bb(){return this.qa}qg(){this.Ud=!0}De(a,b){return b?this.v.Ig(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}Z(a){this.v.Z(a)}aa(a){this.v.aa(a)}td(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Re(){let a=0;for(let b=0,d=this.ca.length;b<d;++b){const g=this.ca[b];this.ca[a]=g;g.va()?g.c():++a}this.ca.length=a}*na(a){if(a)for(const b of this.D)self.fa.Ee(b.$,a)&&(yield b);else this.ia&&!this.ia.T()&&(yield this.ia)}async Gb(a,b,d,g,m){for(const p of this.ca)if(p.Sa()===b)return await V(p),
p;if(m)return null;g&&(this.bd||this.Ud)&&this.Re();m="audio/webm; codecs=opus"===d&&!this.ge;g&&m&&this.qg();a=!g||this.bd||m?new self.ye(this,a,b,d,g,m):new self.we(this,a,b,d,g);this.ca.push(a);await V(a);return a}async Ac(a,b,d,g,m){for(const p of this.D)if(p.Sa()===b&&(p.kc()||m))return p.Te(g),p;a=await this.Gb(a,b,d,m);g="html5"===a.Mc?new self.xe(a.i,a,g):new self.ze(a.i,a,g);this.D.push(g);return g}Xe(a){let b=this.qb.get(a);if(!b){let d=null;b={fd:0,Yg:new Promise(g=>d=g),resolve:d};this.qb.set(a,
b)}b.fd++}ig(a){const b=this.qb.get(a);if(!b)throw Error("expected pending tag");b.fd--;0===b.fd&&(b.resolve(),this.qb.delete(a))}xc(a){a||(a=this.Yd);return(a=this.qb.get(a))?a.Yg:Promise.resolve()}Hb(){if(0<this.Ga.size)L(this);else for(const a of this.D)if(a.qd()){L(this);break}}wa(){for(var a of this.Ga)a.wa();a=this.mc();for(var b of this.D)b.wa(a);b=this.D.filter(d=>d.qd()).map(d=>d.Ra());y(this,"state",{tickCount:this.Zd,audioInstances:b,analysers:[...this.Ga].map(d=>d.Ge())});0===b.length&&
0===this.Ga.size&&M(this)}tc(a,b,d){y(this,"trigger",{type:a,tag:b,aiid:d})}async eg(a){const b=a.originalUrl,d=a.url,g=a.type,m=a.isMusic,p=a.tag,t=a.isLooping,B=a.vol,E=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Yd=p;this.Xe(p);try{this.ia=await this.Ac(b,d,g,p,m),w?(this.ia.Db(!0),this.ia.Se(w.x,w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),
w.hasOwnProperty("uid")&&this.ia.Ue(w.uid)):this.ia.Db(!1),this.ia.Play(t,B,E,x)}catch(D){console.error("[Construct 3] Audio: error starting playback: ",D);return}finally{this.ig(p)}L(this)}Cg(a){a=a.tag;for(const b of this.na(a))b.oa()}Dg(){for(const a of this.D)a.oa()}vg(a){const b=a.tag;a=a.paused;for(const d of this.na(b))a?d.Ua():d.Cb();this.Hb()}Ag(a){const b=a.tag;a=a.vol;for(const d of this.na(b))d.Fb(a)}async kf(a){const b=a.tag,d=a.vol,g=a.duration;a=a.stopOnEnd;await this.xc(b);for(const m of this.na(b))m.Fe(d,
g,a);this.Hb()}tg(a){this.Yc=a.vol;for(const b of this.D)b.Mb()}ug(a){const b=a.tag;a=a.isMuted;for(const d of this.na(b))d.ud(a)}xg(a){this.qa=a.isSilent;this.v.Eb(this.qa);for(const b of this.D)b.Lb()}sg(a){const b=a.tag;a=a.isLooping;for(const d of this.na(b))d.vc(a)}async wg(a){const b=a.tag;a=a.rate;await this.xc(b);for(const d of this.na(b))d.wd(a)}async lg(a){const b=a.tag;a=a.pos;await this.xc(b);for(const d of this.na(b))d.uc(a)}async fg(a){const b=a.originalUrl,d=a.url,g=a.type;a=a.isMusic;
try{await this.Ac(b,d,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async Gg(a){if(a=await this.Gb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ca.indexOf(a),-1!==a&&this.ca.splice(a,1)}Hg(){for(const a of this.ca)a.c();this.ca.length=0}yg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.wc(a);a&&this.f.suspend&&this.f.suspend()}$f(a){this.hc=a.timeScale;this.Rc=a.gameTime;this.Zd=a.tickCount;if(0!==this.dd)for(var b of this.D)b.Fa();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ha===a&&g.vd(d.x,d.y,d.angle)}}async yd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.qe(this,...g);else if("delay"===b)g=new self.oe(this,...g);else if("convolution"===b){b=null;try{b=await this.Gb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}g=new self.ne(this,b.ba,...g);g.ng(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.re(this,...g);else if("phaser"===b)g=new self.te(this,...g);else if("gain"===b)g=new self.se(this,...g);else if("tremolo"===b)g=new self.ve(this,...g);else if("ringmod"===b)g=new self.ue(this,...g);else if("distortion"===b)g=new self.pe(this,...g);else if("compressor"===b)g=new self.me(this,...g);else if("analyser"===b)g=new self.le(this,...g);else throw Error("invalid effect type");this.ke(d,g);this.Jd()}pg(a){const b=a.index,d=a.param,g=a.value,m=a.ramp,
p=a.time;a=this.da.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(d,g,m,p),this.Jd())}hg(a){a=a.tag.toLowerCase();const b=this.da.get(a);if(b&&b.length){for(const d of b)d.c();this.da.delete(a);this.Kd(a)}}We(a){this.Ga.add(a);this.Hb()}gg(a){this.Ga.delete(a)}Jd(){this.Vc||(this.Vc=!0,Promise.resolve().then(()=>this.hf()))}hf(){const a={};for(const [b,d]of this.da)a[b]=d.map(g=>g.Ra());y(this,"fxstate",{fxstate:a});this.Vc=!1}async If(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.D)d.va()&&1===
b||(d.va()||2!==b)&&d.oa();for(const g of this.da.values())for(const m of g)m.c();this.da.clear();this.hc=a.timeScale;this.Rc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.qa=a.isSilent;this.v.Eb(this.qa);this.Yc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(m=>this.yd(m))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.sf(g,b)));this.Hb()}async sf(a,b){if(3!==b){var d=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,
p=a.isMusic,t=a.tag,B=a.isLooping,E=a.volume,w=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.Ac(d,g,m,t,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Oe(a.pan);b.Play(B,E,w,0);a.isPlaying||b.Ua();b.Ec(a)}}}Kf(a,b){this.Ba&&this.Ba.disconnect();this.Zc=b.toLowerCase();this.Ba=this.f.createMediaStreamSource(a);this.Ba.connect(this.pd(this.Zc))}Df(){this.Ob||(this.Ob=this.f.createMediaStreamDestination(),this.Pb.connect(this.Ob));return this.Ob.stream}static Ee(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ve(a){return a*e}static Ce(a){return Math.pow(10,a/20)}static nd(a){return Math.max(Math.min(self.fa.Ce(a),1),0)}static Ne(a){return Math.log(a)/Math.log(10)*20}static Me(a){return self.fa.Ne(Math.max(Math.min(a,1),0))}static Tg(a,b){return 1-Math.exp(-b*a)}};self.Va.wb(self.fa)}"use strict";function V(e){e.Vb||(e.Vb=e.Dc());return e.Vb}
self.jd=class{constructor(e,a,b,d,g){this.i=e;this.Og=a;this.Ca=b;this.R=d;this.Lg=g;this.Mc="";this.Vb=null}c(){this.Vb=this.i=null}Dc(){}X(){return this.i.X()}oc(){return this.Og}Sa(){return this.Ca}nc(){return this.R}va(){return this.Lg}ga(){}};"use strict";
self.we=class extends self.jd{constructor(e,a,b,d,g){super(e,a,b,d,g);this.Mc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.kb=this.lb=null;this.J.addEventListener("canplaythrough",()=>!0);this.pb=this.X().createGain();this.nb=null;this.J.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.J&&(this.nb=this.X().createMediaElementSource(this.J),this.nb.connect(this.pb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,m);this.kb&&(this.kb(m),this.kb=this.lb=null)})}c(){this.i.td(this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Dc(){return new Promise((e,a)=>{this.lb=e;this.kb=a;this.J.src=this.Ca})}O(){return this.J}ga(){return this.J.duration}};"use strict";
async function W(e){if(e.za)return e.za;var a=e.i.v;if("cordova"===a.A&&a.rd(e.Ca)&&a.hb)e.za=await a.xb(e.Ca);else{a=await fetch(e.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.za=await a.arrayBuffer()}}async function X(e){if(e.ba)return e.ba;e.ba=await e.i.De(e.za,e.Ng);e.za=null}
self.ye=class extends self.jd{constructor(e,a,b,d,g,m){super(e,a,b,d,g);this.Mc="webaudio";this.ba=this.za=null;this.Ng=!!m}c(){this.i.td(this);this.ba=this.za=null;super.c()}async Dc(){try{await W(this),await X(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,e)}}ga(){return this.ba?this.ba.duration:0}};"use strict";
{let e=0;self.kd=class{constructor(a,b,d){this.i=a;this.L=b;this.$=d;this.Nb=e++;this.M=this.X().createGain();this.M.connect(this.ua());this.B=null;this.ib=!1;this.la=[0,0,0];this.ka=[0,0,0];this.H=!0;this.W=this.ma=this.G=!1;this.tb=1;this.Ha=!1;this.sa=1;a=this.i.dd;this.Wc=1===a&&!this.va()||2===a;this.eb=this.ha=-1;this.fe=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}X(){return this.i.X()}ua(){return this.i.pd(this.$)}Ab(){return this.i.Ab()}zb(){return this.Wc?
this.i.Rc:performance.now()/1E3}oc(){return this.L.oc()}Sa(){return this.L.Sa()}nc(){return this.L.nc()}va(){return this.L.va()}Te(a){this.$=a}T(){}kc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}qd(){return!this.H&&!this.T()}Da(){}ga(){return this.L.ga()}Play(){}oa(){}Ua(){}Cb(){}Fb(a){this.tb=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.pc()}Fe(a,b,d){if(!this.Ha){a*=this.Ab();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.mc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.tb=a;this.eb=b;this.fe=d}}Mb(){this.Fb(this.tb)}wa(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.fe&&this.oa(),this.i.tc("fade-ended",this.$,this.Nb))}pc(){const a=this.tb*this.Ab();return isFinite(a)?a:0}ud(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Lb())}Bb(){return this.i.Bb()}Lb(){}vc(){}wd(a){this.sa!==a&&(this.sa=a,this.Fa())}Fa(){}uc(){}wc(){}Db(a){a=!!a;this.ib!==a&&((this.ib=a)?(this.B||(this.B=this.X().createPanner(),this.B.panningModel=this.i.ae,this.B.distanceModel=
this.i.Sd,this.B.refDistance=this.i.be,this.B.maxDistance=this.i.$d,this.B.rolloffFactor=this.i.de),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}Se(a,b,d,g,m,p){this.ib&&(this.vd(a,b,d),a=self.fa.Ve,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}vd(a,b,d){this.ib&&(this.la[0]=a,this.la[1]=b,this.la[2]=0,this.ka[0]=Math.cos(d),this.ka[1]=Math.sin(d),this.ka[2]=0,this.B.setPosition(...this.la),
this.B.setOrientation(...this.ka))}Ue(a){this.ha=a}qc(){}Qe(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Nb,tag:this.$,duration:this.ga(),volume:this.tb,isPlaying:this.IsPlaying(),playbackTime:this.Da(),playbackRate:this.sa,uid:this.ha,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.va(),isLooping:this.W,isMuted:this.Ha,resumePosition:this.qc(),pan:this.He()}}Ec(a){this.wd(a.playbackRate);this.ud(a.isMuted)}He(){if(!this.B)return null;const a=
this.B;return{pos:this.la,orient:this.ka,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ha}}Oe(a){if(a){this.Db(!0);a=this.B;var b=a.pos;this.la[0]=b[0];this.la[1]=b[1];this.la[2]=b[2];b=a.orient;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];a.setPosition(...this.la);a.setOrientation(...this.ka);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ha=a.uid}else this.Db(!1)}}}"use strict";
self.xe=class extends self.kd{constructor(e,a,b){super(e,a,b);this.L.pb.connect(this.M);this.L.onended=()=>this.Fc()}c(){this.oa();this.L.pb.disconnect();super.c()}O(){return this.L.O()}Fc(){this.H=!0;this.ha=-1;this.i.tc("ended",this.$,this.Nb)}T(){return this.O().ended}kc(){return this.H?!0:this.T()}Da(){let e=this.O().currentTime;this.W||(e=Math.min(e,this.ga()));return e}Play(e,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==e&&(d.loop=e);this.Fb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,g)}this.i.Z(d);this.G=this.H=!1;this.W=e;this.sa=1}oa(){const e=this.O();e.paused||e.pause();this.i.aa(e);this.H=!0;this.G=!1;this.ha=-1}Ua(){if(!(this.G||this.H||this.T())){var e=this.O();e.paused||e.pause();this.i.aa(e);this.G=!0}}Cb(){!this.G||this.H||this.T()||(this.i.Z(this.O()),this.G=!1)}Lb(){this.O().muted=this.Ha||this.Bb()}vc(e){e=!!e;this.W!==e&&(this.W=
e,this.O().loop=e)}Fa(){let e=this.sa;this.Wc&&(e*=this.i.hc);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}uc(e){if(!this.H&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}qc(){return this.Da()}wc(e){e?this.IsPlaying()?(this.O().pause(),this.ma=!0):this.ma=!1:this.ma&&(this.i.Z(this.O()),this.ma=!1)}};"use strict";function Y(e){e.j&&e.j.disconnect();e.j=null;e.Za=null}
self.ze=class extends self.kd{constructor(e,a,b){super(e,a,b);this.j=null;this.Zb=d=>this.Fc(d);this.Sc=!0;this.Za=null;this.N=this.$b=this.ac=0;this.$c=1}c(){this.oa();Y(this);this.Zb=null;super.c()}Fc(e){this.G||this.ma||e.target!==this.Za||(this.H=this.Sc=!0,this.ha=-1,Y(this),this.i.tc("ended",this.$,this.Nb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Sc}kc(){return!this.j||this.H?!0:this.T()}Da(){let e;e=this.G?this.N:this.$b+(this.zb()-this.ac)*this.sa;this.W||(e=Math.min(e,this.ga()));
return e}Play(e,a,b,d){this.$c=1;this.Fb(a);Y(this);this.j=this.X().createBufferSource();this.j.buffer=this.L.ba;this.j.connect(this.M);this.Za=this.j;this.j.onended=this.Zb;this.j.loop=e;this.j.start(d,b);this.G=this.H=this.Sc=!1;this.W=e;this.sa=1;this.ac=this.zb();this.$b=b}oa(){if(this.j)try{this.j.stop(0)}catch(e){}this.H=!0;this.G=!1;this.ha=-1}Ua(){this.G||this.H||this.T()||(this.N=this.Da(),this.W&&(this.N%=this.ga()),this.G=!0,this.j.stop(0))}Cb(){!this.G||this.H||this.T()||(Y(this),this.j=
this.X().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Zb,this.j.loop=this.W,this.Mb(),this.Fa(),this.j.start(0,this.N),this.ac=this.zb(),this.$b=this.N,this.G=!1)}pc(){return super.pc()*this.$c}Lb(){this.$c=this.Ha||this.Bb()?0:1;this.Mb()}vc(e){e=!!e;this.W!==e&&(this.W=e,this.j&&(this.j.loop=e))}Fa(){let e=this.sa;this.Wc&&(e*=this.i.hc);this.j&&(this.j.playbackRate.value=e)}uc(e){this.H||this.T()||(this.G?this.N=e:(this.Ua(),this.N=e,this.Cb()))}qc(){return this.N}wc(e){e?
this.IsPlaying()?(this.ma=!0,this.N=this.Da(),this.W&&(this.N%=this.ga()),this.j.stop(0)):this.ma=!1:this.ma&&(Y(this),this.j=this.X().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Zb,this.j.loop=this.W,this.Mb(),this.Fa(),this.j.start(0,this.N),this.ac=this.zb(),this.$b=this.N,this.ma=!1)}Ec(e){super.Ec(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.X();this.Vd=-1;this.R=this.$="";this.g=null}c(){this.f=null}rg(a){this.Vd=a}zg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ra(){return{type:this.R,tag:this.$,params:this.g}}}
self.qe=class extends e{constructor(a,b,d,g,m,p,t){super(a);this.R="filter";this.g=[b,d,g,m,p,t];this.l=this.o();this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,g)}}};self.oe=class extends e{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.mb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=d;this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b);this.mb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.mb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.mb.disconnect();this.U.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){const m=self.fa.nd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=m(b);this.m(this.cb.gain,m(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.ne=class extends e{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Qd=this.Pd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.bb=this.f.createConvolver();this.bb.normalize=d;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}c(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}ng(a,b){this.Pd=a;this.Qd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Pd;a.bufferUrl="";a.bufferType=this.Qd;return a}};self.re=class extends e{constructor(a,b,d,g,m,p){super(a);this.R="flanger";this.g=[b,d,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.fb=this.o();this.fb.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,d,g)}}};self.te=class extends e{constructor(a,b,d,g,m,p,t){super(a);this.R="phaser";this.g=[b,d,g,m,p,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.se=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,d,g){const m=self.fa.nd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,g)}}};self.ve=class extends e{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ue=class extends e{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.sb=this.o();this.sb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.sb.gain);this.s.start(0);this.l.connect(this.sb);this.l.connect(this.a);this.sb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.sb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.pe=class extends e{constructor(a,b,d,g,m,p){super(a);this.R="distortion";this.g=[b,d,g,m,p];this.l=this.o();this.cc=this.o();this.bc=this.o();this.og(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ic=this.f.createWaveShaper();this.Oc=new Float32Array(65536);this.mf(b,d);this.ic.curve=this.Oc;this.l.connect(this.cc);this.l.connect(this.a);this.cc.connect(this.ic);this.ic.connect(this.bc);
this.bc.connect(this.b)}c(){this.l.disconnect();this.cc.disconnect();this.ic.disconnect();this.bc.disconnect();this.b.disconnect();this.a.disconnect();super.c()}og(a,b){.01>a&&(a=.01);this.cc.gain.value=a;this.bc.gain.value=Math.pow(1/a,.6)*b}mf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.Bg(g,a,b);this.Oc[32768+d]=g;this.Oc[32768-d-1]=-g}}Bg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.fa.Tg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}Y(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.me=class extends e{constructor(a,b,d,g,m,p){super(a);this.R="compressor";this.g=[b,d,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}};
self.le=class extends e{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Td=new Float32Array(this.h.frequencyBinCount);this.ee=new Uint8Array(b);this.ce=this.Ka=0;this.i.We(this)}c(){this.i.gg(this);this.h.disconnect();super.c()}wa(){this.h.getFloatFrequencyData(this.Td);this.h.getByteTimeDomainData(this.ee);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let g=(this.ee[d]-128)/128;0>g&&(g=-g);
this.Ka<g&&(this.Ka=g);b+=g*g}d=self.fa.Me;this.Ka=d(this.Ka);this.ce=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}Ge(){return{tag:this.$,index:this.Vd,peak:this.Ka,rms:this.ce,binCount:this.h.frequencyBinCount,freqBins:this.Td}}}}"use strict";async function Z(e,a){a=a.type;let b=!0;0===a?b=await aa():1===a&&(b=await ba());y(e,"permission-result",{type:a,result:b})}
async function aa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function ba(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.Va.wb(class extends self.yb{constructor(e){super(e,"touch");I(this,"request-permission",a=>Z(this,a))}});"use strict";
self.Va.wb(class extends self.Be{constructor(e){super(e,"video");this.fc=this.Tb=this.$a=!1;this.Yb=this.Qg=0;this.Pc=new WeakSet;I(this,"init",a=>this.Gf(a));R(this,"play",a=>this.Nf(a));R(this,"pause",a=>this.Mf(a));R(this,"set-source",(a,b)=>this.Xf(a,b));R(this,"set-playback-time",(a,b)=>this.Wf(a,b));R(this,"set-looping",(a,b)=>this.Uf(a,b));R(this,"set-muted",(a,b)=>this.Vf(a,b));R(this,"set-volume",(a,b)=>this.Zf(a,b));self.C3Video_GetElement=a=>this.V.get(a)}async Gf(e){this.Tb=e.isInWorker;
e=document.createElement("video");this.fc=!!e.requestVideoFrameCallback;return{"video/webm":!!e.canPlayType("video/webm"),"video/ogg":!!e.canPlayType("video/ogg"),"video/mp4":!!e.canPlayType("video/mp4")}}Z(e){this.v.Z(e);this.Tb&&this.fc&&-1===e.c3_rvfcId&&(e.c3_rvfcId=e.requestVideoFrameCallback(()=>this.Id(e)))}aa(e){this.v.aa(e);this.Tb&&this.fc&&-1!==e.c3_rvfcId&&(e.cancelVideoFrameCallback(e.c3_rvfcId),e.c3_rvfcId=-1)}async Id(e){if(!this.Pc.has(e)){e.c3_rvfcId=e.requestVideoFrameCallback(()=>
this.Id(e));try{const a=e.c3_sequenceNumber++,b=await createImageBitmap(e);a>e.c3_lastFrameSequence&&(e.c3_imageBitmap=b,e.c3_lastFrameSequence=a)}catch(a){}}}md(e,a){const b=document.createElement("video");b.crossOrigin="anonymous";b.playsInline=!0;b.c3_imageBitmap=null;b.c3_rvfcId=-1;b.c3_sequenceNumber=0;b.c3_lastFrameSequence=-1;b.addEventListener("canplay",()=>this.pa(b,e,0));b.addEventListener("canplaythrough",()=>this.pa(b,e,1));b.addEventListener("ended",()=>this.pa(b,e,2));b.addEventListener("error",
()=>this.pa(b,e,3));b.addEventListener("loadstart",()=>this.pa(b,e,4));b.addEventListener("playing",()=>this.pa(b,e,5));b.addEventListener("pause",()=>this.pa(b,e,6));b.addEventListener("stalled",()=>this.pa(b,e,7));const d=a.autoplay;0===d?(b.autoplay=!1,b.preload="none"):1===d?(b.autoplay=!1,b.preload="auto"):b.autoplay=!0;a.src&&(b.src=a.src);2===d&&this.Z(b);this.Yb++;L(this);return b}pa(e,a,b){this.Pc.has(e)||Q(this,"playback-event",a,{type:b})}xd(){}od(e){this.aa(e);e&&!e.paused&&!e.ended&&
0<e.currentTime&&e.pause();e.src="";this.Yb=Math.max(this.Yb-1,0);0===this.Yb&&M(this);this.Pc.add(e)}Nf(e){this.Z(e)}Mf(e){this.aa(e);e.pause()}Xf(e,a){e.src=a.src;e.load()}Wf(e,a){try{e.currentTime=a.time}catch(b){console.error("[Video] Exception setting playback time: ",b)}}Uf(e,a){e.loop=a.isLooping}Vf(e,a){e.muted=a.isMuted}Zf(e,a){e.volume=a.volume}wa(){const e={},a={sequenceNumber:this.Qg++,videoData:e},b=[],d=[];for(const [g,m]of this.V.entries()){const p={currentTime:m.currentTime,duration:m.duration,
videoWidth:m.videoWidth,videoHeight:m.videoHeight};if(this.Tb)if(this.fc){const t=m.c3_imageBitmap;m.c3_imageBitmap=null;(p.imageBitmap=t)&&b.push(t)}else d.push(createImageBitmap(m).then(t=>{p.imageBitmap=t;b.push(t)}).catch(()=>{p.imageBitmap=null}));e[g.toString()]=p}Promise.all(d).then(()=>y(this,"state",a,!1,b))}});
