'use strict';function B(k,a,b,d){k.N.le(k.kc,a,b,d,void 0)}function C(k,a,b){return k.N.Uf(k.kc,a,b,void 0,void 0)}function J(k,a,b,d){k.N.Pa?B(k,a,b,d):k.N.xj()._OnMessageFromDOM({type:"event",component:k.kc,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function K(k,a,b){k.N.S(k.kc,a,b)}function L(k,a){for(const [b,d]of a)K(k,b,d)}function N(k){k.Dd||(k.N.gj(k.Zg),k.Dd=!0)}window.Db=class{constructor(k,a){this.N=k;this.kc=a;this.Dd=!1;this.Zg=()=>this.la()}Gf(){}la(){}};
function O(k){-1!==k.Vb&&(self.clearTimeout(k.Vb),k.Vb=-1)}window.Ci=class{constructor(k,a){this.Te=k;this.Dl=a;this.Vb=-1;this.Ed=-Infinity;this.$g=()=>{this.Vb=-1;this.Ed=Date.now();this.rc=!0;this.Te();this.rc=!1};this.Ag=this.rc=!1}l(){O(this);this.$g=this.Te=null}};"use strict";
function P(k,a){const b=a.elementId,d=k.Yb(b,a);k.Ba.set(b,d);a.isVisible||(d.style.display="none");a=k.Ce(d);a.addEventListener("focus",()=>{Q(k,"elem-focused",b)});a.addEventListener("blur",()=>{Q(k,"elem-blurred",b)});k.td&&document.body.appendChild(d)}function R(k,a,b){K(k,a,d=>{const h=k.Ba.get(d.elementId);return b(h,d)})}function Q(k,a,b,d){d||(d={});d.elementId=b;B(k,a,d)}function S(k,a,b,d){d||(d={});d.elementId=b;J(k,a,d)}
window.Xc=class extends self.Db{constructor(k,a){super(k,a);this.Ba=new Map;this.td=!0;L(this,[["create",b=>P(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Ba.get(b);this.td&&d.parentElement.removeChild(d);this.Ba.delete(b)}}],["set-visible",b=>{this.td&&(this.Ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.td){var d=this.Ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Ba.get(b.elementId);this.Ta(d,b)}}],["focus",b=>{{const d=this.Ce(this.Ba.get(b.elementId));b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.Ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Ba.get(b.elementId).removeAttribute(b.name)}]]);R(this,"get-element",b=>b)}Yb(){throw Error("required override");}Ta(){throw Error("required override");
}Ce(k){return k}};"use strict";
{const k=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(u){const g=document.createElement("script");g.async=!1;g.type="module";return u.Ql?new Promise(r=>{const v="c3_resolve_"+a;++a;self[v]=r;g.textContent=u.Ul+`\n\nself["${v}"]();`;document.head.appendChild(g)}):new Promise((r,v)=>{g.onload=r;g.onerror=v;g.src=u;document.head.appendChild(g)})}let d=!1,h=!1;function w(){if(!d){try{new Worker("blob://",{get type(){h=!0}})}catch(u){}d=!0}return h}const m=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let f=new Audio;const n={"audio/webm; codecs=opus":!!f.canPlayType("audio/webm; codecs=opus")&&!m,"audio/ogg; codecs=opus":!!f.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!f.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!f.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!f.canPlayType("audio/mp4"),"audio/mpeg":!!f.canPlayType("audio/mpeg")};f=null;async function c(u){u=
await e(u);return(new TextDecoder("utf-8")).decode(u)}function e(u){return new Promise((g,r)=>{const v=new FileReader;v.onload=y=>g(y.target.result);v.onerror=y=>r(y);v.readAsArrayBuffer(u)})}const p=[];let t=0;window.RealFile=window.File;const x=[],A=new Map,F=new Map;let G=0;const I=[];self.runOnStartup=function(u){if("function"!==typeof u)throw Error("runOnStartup called without a function");I.push(u)};const l=new Set(["cordova","playable-ad","instant-games"]);let q=!1;window.Ea=class u{constructor(g){this.Pa=
g.Wl;this.ib=null;this.X="";this.Rd=g.Tl;this.Uc={};this.Nb=this.Tc=null;this.zd=[];this.zc=this.da=this.Tb=null;this.Sb=-1;this.Jl=()=>this.nk();this.Rb=[];this.M=g.ah;this.uc="file"===location.protocol.substr(0,4);!this.Pa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&w()||(this.Pa=!1);if("playable-ad"===this.M||"instant-games"===this.M)this.Pa=!1;if("cordova"===this.M&&this.Pa)if(/android/i.test(navigator.userAgent)){const r=/Chrome\/(\d+)/i.exec(navigator.userAgent);r&&90<=
parseInt(r[1],10)||(this.Pa=!1)}else this.Pa=!1;this.Jd=this.Wa=null;"html5"!==this.M&&"playable-ad"!==this.M||!this.uc||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.S("runtime","cordova-fetch-local-file",r=>this.Rj(r));this.S("runtime","create-job-worker",()=>this.Sj());"cordova"===this.M?document.addEventListener("deviceready",()=>this.jg(g)):this.jg(g)}l(){this.ye();this.ib&&
(this.ib=this.ib.onmessage=null);this.Tc&&(this.Tc.terminate(),this.Tc=null);this.Nb&&(this.Nb.l(),this.Nb=null);this.da&&(this.da.parentElement.removeChild(this.da),this.da=null)}ki(){return k&&"cordova"===this.M}ke(){const g=navigator.userAgent;return k&&l.has(this.M)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(g)}async jg(g){"macos-wkwebview"===this.M&&this.cl();if("playable-ad"===this.M){this.Wa=self.c3_base64files;this.Jd={};await this.lj();for(let v=0,y=g.Xb.length;v<y;++v){var r=
g.Xb[v].toLowerCase();this.Jd.hasOwnProperty(r)?g.Xb[v]={Ql:!0,Ul:this.Jd[r]}:this.Wa.hasOwnProperty(r)&&(g.Xb[v]=URL.createObjectURL(this.Wa[r]))}}g.Ll?this.X=g.Ll:(r=location.origin,this.X=("null"===r?"file:///":r)+location.pathname,r=this.X.lastIndexOf("/"),-1!==r&&(this.X=this.X.substr(0,r+1)));g.Yl&&(this.Uc=g.Yl);r=new MessageChannel;this.ib=r.port1;this.ib.onmessage=v=>this._OnMessageFromRuntime(v.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(v=>this.fk(v));this.zc=
new self.li(this);await T(this.zc);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.Pa?await this.Dj(g,r.port2):await this.Cj(g,r.port2)}Ee(g){g=this.Uc.hasOwnProperty(g)?this.Uc[g]:g.endsWith("/workermain.js")&&this.Uc.hasOwnProperty("workermain.js")?this.Uc["workermain.js"]:"playable-ad"===this.M&&this.Wa.hasOwnProperty(g.toLowerCase())?this.Wa[g.toLowerCase()]:g;g instanceof Blob&&(g=URL.createObjectURL(g));
return g}async ce(g,r,v){if(g.startsWith("blob:"))return new Worker(g,v);if("cordova"===this.M&&this.uc)return g=await this.Wc(v.Pl?g:this.Rd+g),new Worker(URL.createObjectURL(new Blob([g],{type:"application/javascript"})),v);g=new URL(g,r);if(location.origin!==g.origin){g=await fetch(g);if(!g.ok)throw Error("failed to fetch worker script");g=await g.blob();return new Worker(URL.createObjectURL(g),v)}return new Worker(g,v)}qb(){return Math.max(window.innerWidth,1)}pb(){return Math.max(window.innerHeight,
1)}hg(g){var r=this.zc;return{baseUrl:this.X,windowInnerWidth:this.qb(),windowInnerHeight:this.pb(),devicePixelRatio:window.devicePixelRatio,isFullscreen:u.bc(),projectData:g.cm,previewImageBlobs:window.cr_previewImageBlobs||this.Wa,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.am||"",exportType:g.ah,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.bm,jobScheduler:{inputPort:r.ef,outputPort:r.sf,maxNumWorkers:r.Fl},
supportedAudioFormats:n,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Rd+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Rd+"opus.wasm.wasm",isFileProtocol:this.uc,isiOSCordova:this.ki(),isiOSWebView:this.ke(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Dj(g,r){var v=this.Ee(g.Xl);this.Tc=await this.ce(v,this.X,{type:"module",name:"Runtime",Pl:!0});this.da=document.createElement("canvas");this.da.style.display="none";v=this.da.transferControlToOffscreen();
document.body.appendChild(this.da);window.c3canvas=this.da;let y=g.Ef||[],E=g.Xb;y=await Promise.all(y.map(z=>this.Hb(z)));E=await Promise.all(E.map(z=>this.Hb(z)));if("cordova"===this.M)for(let z=0,D=g.$d.length;z<D;++z){const H=g.$d[z],M=H[0];if(M===g.Bf||"scriptsInEvents.js"===M||M.endsWith("/scriptsInEvents.js"))H[1]=await this.Hb(M)}this.Tc.postMessage(Object.assign(this.hg(g),{type:"init-runtime",isInWorker:!0,messagePort:r,canvas:v,workerDependencyScripts:y,engineScripts:E,projectScripts:g.$d,
mainProjectScript:g.Bf,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[r,v,...U(this.zc)]);this.zd=x.map(z=>new z(this));this.gg();self.c3_callFunction=(z,D)=>this.Tb.Ej(z,D);"preview"===this.M&&(self.goToLastErrorScript=()=>this.le("runtime","go-to-last-error-script"))}async Cj(g,r){this.da=document.createElement("canvas");this.da.style.display="none";document.body.appendChild(this.da);window.c3canvas=this.da;this.zd=x.map(z=>new z(this));this.gg();var v=g.Xb.map(z=>"string"===typeof z?(new URL(z,
this.X)).toString():z);Array.isArray(g.Ef)&&v.unshift(...g.Ef);v=await Promise.all(v.map(z=>this.Hb(z)));await Promise.all(v.map(z=>b(z)));v=self.C3_ProjectScriptsStatus;const y=g.Bf,E=g.$d;for(let [z,D]of E)if(D||(D=z),z===y)try{D=await this.Hb(D),await b(D),"preview"!==this.M||v[z]||this.tg(z,"main script did not run to completion")}catch(H){this.tg(z,H)}else if("scriptsInEvents.js"===z||z.endsWith("/scriptsInEvents.js"))D=await this.Hb(D),await b(D);"preview"===this.M&&"object"!==typeof self.Zl.$l?
(this.pd(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(g=Object.assign(this.hg(g),{isInWorker:!1,messagePort:r,canvas:this.da,runOnStartupFunctions:I}),this.lg(),this.Nb=self.C3_CreateRuntime(g),await self.C3_InitRuntime(this.Nb,g))}tg(g,r){this.pd();console.error(`[Preview] Failed to load project main script (${g}): `,
r);alert(`Failed to load project main script (${g}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}lg(){this.pd()}pd(){const g=window.Ml;g&&(g.parentElement.removeChild(g),window.Ml=null)}async Sj(){const g=await V(this.zc);return{outputPort:g,transferables:[g]}}xj(){if(this.Pa)throw Error("not available in worker mode");return this.Nb}le(g,r,v,y,E){this.ib.postMessage({type:"event",component:g,handler:r,dispatchOpts:y||null,data:v,responseId:null},
E)}Uf(g,r,v,y,E){const z=G++,D=new Promise((H,M)=>{F.set(z,{resolve:H,reject:M})});this.ib.postMessage({type:"event",component:g,handler:r,dispatchOpts:y||null,data:v,responseId:z},E);return D}["_OnMessageFromRuntime"](g){const r=g.type;if("event"===r)return this.Xj(g);if("result"===r)this.sk(g);else if("runtime-ready"===r)this.tk();else if("alert-error"===r)this.pd(),alert(g.message);else if("creating-runtime"===r)this.lg();else throw Error(`unknown message '${r}'`);}Xj(g){const r=g.component,v=
g.handler,y=g.data,E=g.responseId;if(g=A.get(r))if(g=g.get(v)){var z=null;try{z=g(y)}catch(D){console.error(`Exception in '${r}' handler '${v}':`,D);null!==E&&this.od(E,!1,""+D);return}if(null===E)return z;z&&z.then?z.then(D=>this.od(E,!0,D)).catch(D=>{console.error(`Rejection from '${r}' handler '${v}':`,D);this.od(E,!1,""+D)}):this.od(E,!0,z)}else console.warn(`[DOM] No handler '${v}' for component '${r}'`);else console.warn(`[DOM] No event handlers for component '${r}'`)}od(g,r,v){let y;v&&v.transferables&&
(y=v.transferables);this.ib.postMessage({type:"result",responseId:g,isOk:r,result:v},y)}sk(g){const r=g.responseId,v=g.isOk;g=g.result;const y=F.get(r);v?y.resolve(g):y.reject(g);F.delete(r)}S(g,r,v){let y=A.get(g);y||(y=new Map,A.set(g,y));if(y.has(r))throw Error(`[DOM] Component '${g}' already has handler '${r}'`);y.set(r,v)}static Qa(g){if(x.includes(g))throw Error("DOM handler already added");x.push(g)}gg(){for(const g of this.zd)if("runtime"===g.kc){this.Tb=g;return}throw Error("cannot find runtime DOM handler");
}fk(g){this.le("debugger","message",g)}tk(){for(const g of this.zd)g.Gf()}static bc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||q)}static ug(g){q=!!g}gj(g){this.Rb.push(g);this.Qe()}Xk(g){g=this.Rb.indexOf(g);if(-1===g)throw Error("invalid callback");this.Rb.splice(g,1);this.Rb.length||this.ye()}Qe(){-1===this.Sb&&this.Rb.length&&(this.Sb=requestAnimationFrame(this.Jl))}ye(){-1!==this.Sb&&(cancelAnimationFrame(this.Sb),this.Sb=-1)}nk(){this.Sb=
-1;for(const g of this.Rb)g();this.Qe()}ob(g){this.Tb.ob(g)}Gb(g){this.Tb.Gb(g)}Pe(){this.Tb.Pe()}hd(g){this.Tb.hd(g)}ii(){return!!n["audio/webm; codecs=opus"]}async Bl(g){g=await this.Uf("runtime","opus-decode",{arrayBuffer:g},null,[g]);return new Float32Array(g)}hi(g){return/^(?:[a-z\-]+:)?\/\//.test(g)||"data:"===g.substr(0,5)||"blob:"===g.substr(0,5)}Tf(g){return!this.hi(g)}async Hb(g){return"cordova"===this.M&&(g.startsWith("file:")||this.uc&&this.Tf(g))?(g.startsWith(this.X)&&(g=g.substr(this.X.length)),
g=await this.Wc(g),URL.createObjectURL(new Blob([g],{type:"application/javascript"}))):g}async Rj(g){const r=g.filename;switch(g.as){case "text":return await this.Ih(r);case "buffer":return await this.Wc(r);default:throw Error("unsupported type");}}Mf(g){const r=window.cordova.file.applicationDirectory+"www/"+g.toLowerCase();return new Promise((v,y)=>{window.resolveLocalFileSystemURL(r,E=>{E.file(v,y)},y)})}async Ih(g){g=await this.Mf(g);return await c(g)}ze(){if(p.length&&!(8<=t)){t++;var g=p.shift();
this.mj(g.filename,g.Vl,g.Ol)}}Wc(g){return new Promise((r,v)=>{p.push({filename:g,Vl:y=>{t--;this.ze();r(y)},Ol:y=>{t--;this.ze();v(y)}});this.ze()})}async mj(g,r,v){try{const y=await this.Mf(g),E=await e(y);r(E)}catch(y){v(y)}}cl(){var g={type:"ready"};if("windows-webview2"===this.M)window.chrome.webview.postMessage(JSON.stringify(g));else if("macos-wkwebview"===this.M)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(g));else throw Error("cannot send wrapper message");}async lj(){const g=
[];for(const [r,v]of Object.entries(this.Wa))g.push(this.kj(r,v));await Promise.all(g)}async kj(g,r){if("object"===typeof r)this.Wa[g]=new Blob([r.str],{type:r.type}),this.Jd[g]=r.str;else{let v=await this.uj(r);v||(v=this.oj(r));this.Wa[g]=v}}async uj(g){try{return await (await fetch(g)).blob()}catch(r){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
r),null}}oj(g){g=this.Qk(g);return this.jj(g.data,g.Rl)}Qk(g){var r=g.indexOf(",");if(0>r)throw new URIError("expected comma in data: uri");var v=g.substring(r+1);r=g.substring(5,r).split(";");g=r[0]||"";const y=r[2];v="base64"===r[1]||"base64"===y?atob(v):decodeURIComponent(v);return{Rl:g,data:v}}jj(g,r){var v=g.length;let y=v>>2,E=new Uint8Array(v),z=new Uint32Array(E.buffer,0,y),D,H;for(H=D=0;D<y;++D)z[D]=g.charCodeAt(H++)|g.charCodeAt(H++)<<8|g.charCodeAt(H++)<<16|g.charCodeAt(H++)<<24;for(v&=
3;v--;)E[H]=g.charCodeAt(H),++H;return new Blob([E],{type:r})}}}"use strict";
{const k=self.Ea;function a(l){return l.sourceCapabilities&&l.sourceCapabilities.firesTouchEvents||l.originalEvent&&l.originalEvent.sourceCapabilities&&l.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},h={dispatchUserScriptEvent:!0},w={dispatchRuntimeEvent:!0};function m(l){return new Promise((q,u)=>{const g=document.createElement("link");g.onload=()=>q(g);g.onerror=r=>u(r);g.rel=
"stylesheet";g.href=l;document.head.appendChild(g)})}function f(l){return new Promise((q,u)=>{const g=new Image;g.onload=()=>q(g);g.onerror=r=>u(r);g.src=l})}async function n(l){l=URL.createObjectURL(l);try{return await f(l)}finally{URL.revokeObjectURL(l)}}function c(l){return new Promise((q,u)=>{let g=new FileReader;g.onload=r=>q(r.target.result);g.onerror=r=>u(r);g.readAsText(l)})}async function e(l,q,u){if(!/firefox/i.test(navigator.userAgent))return await n(l);var g=await c(l);g=(new DOMParser).parseFromString(g,
"image/svg+xml");const r=g.documentElement;if(r.hasAttribute("width")&&r.hasAttribute("height")){const v=r.getAttribute("width"),y=r.getAttribute("height");if(!v.includes("%")&&!y.includes("%"))return await n(l)}r.setAttribute("width",q+"px");r.setAttribute("height",u+"px");g=(new XMLSerializer).serializeToString(g);l=new Blob([g],{type:"image/svg+xml"});return await n(l)}function p(l){do{if(l.parentNode&&l.hasAttribute("contenteditable"))return!0;l=l.parentNode}while(l);return!1}const t=new Set(["input",
"textarea","datalist","select"]),x=new Set(["canvas","body","html"]);function A(l){x.has(l.target.tagName.toLowerCase())&&l.preventDefault()}function F(l){(l.metaKey||l.ctrlKey)&&l.preventDefault()}self.C3_GetSvgImageSize=async function(l){l=await n(l);if(0<l.width&&0<l.height)return[l.width,l.height];{l.style.position="absolute";l.style.left="0px";l.style.top="0px";l.style.visibility="hidden";document.body.appendChild(l);const q=l.getBoundingClientRect();document.body.removeChild(l);return[q.width,
q.height]}};self.C3_RasterSvgImageBlob=async function(l,q,u,g,r){l=await e(l,q,u);const v=document.createElement("canvas");v.width=g;v.height=r;v.getContext("2d").drawImage(l,0,0,q,u);return v};let G=!1;document.addEventListener("pause",()=>G=!0);document.addEventListener("resume",()=>G=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(l){return!1}}k.Qa(class extends self.Db{constructor(l){super(l,"runtime");this.Hg=!0;this.Ub=-1;this.yf="any";this.vg=this.wg=!1;this.jf=
this.Lc=this.xb=null;l.S("canvas","update-size",g=>this.Nk(g));l.S("runtime","invoke-download",g=>this.dk(g));l.S("runtime","raster-svg-image",g=>this.pk(g));l.S("runtime","get-svg-image-size",g=>this.$j(g));l.S("runtime","set-target-orientation",g=>this.xk(g));l.S("runtime","register-sw",()=>this.qk());l.S("runtime","post-to-debugger",g=>this.pg(g));l.S("runtime","go-to-script",g=>this.pg(g));l.S("runtime","before-start-ticking",()=>this.Mj());l.S("runtime","debug-highlight",g=>this.Tj(g));l.S("runtime",
"enable-device-orientation",()=>this.ij());l.S("runtime","enable-device-motion",()=>this.hj());l.S("runtime","add-stylesheet",g=>this.Jj(g));l.S("runtime","alert",g=>this.Kj(g));l.S("runtime","hide-cordova-splash",()=>this.ak());const q=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",g=>{const r=g.target;q.has(r.tagName.toLowerCase())||p(r)||g.preventDefault()});const u=l.da;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);u.addEventListener("selectstart",
A);u.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),u.addEventListener("pointerdown",A)):u.addEventListener("touchstart",A);this.Ec=0;window.addEventListener("mousedown",g=>{1===g.button&&g.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.Ok());window.addEventListener("fullscreenchange",
()=>this.fc());window.addEventListener("webkitfullscreenchange",()=>this.fc());window.addEventListener("mozfullscreenchange",()=>this.fc());window.addEventListener("fullscreenerror",g=>this.Ke(g));window.addEventListener("webkitfullscreenerror",g=>this.Ke(g));window.addEventListener("mozfullscreenerror",g=>this.Ke(g));l.ke()&&window.addEventListener("focusout",()=>{{const v=document.activeElement;if(v){var g=v.tagName.toLowerCase();var r=new Set("email number password search tel text url".split(" "));
g="textarea"===g?!0:"input"===g?r.has(v.type.toLowerCase()||"text"):p(v)}else g=!1}g||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=g=>this.Pk(g);this.Ob=new Set;this.Kd=new WeakSet;this.hb=!1}Mj(){"cordova"===this.N.M?(document.addEventListener("pause",()=>this.Oe(!0)),document.addEventListener("resume",()=>this.Oe(!1))):document.addEventListener("visibilitychange",()=>this.Oe(document.hidden));return{isSuspended:!(!document.hidden&&!G)}}Gf(){window.addEventListener("focus",()=>
this.ic("window-focus"));window.addEventListener("blur",()=>{this.ic("window-blur",{parentHasFocus:I()});this.Ec=0});window.addEventListener("focusin",q=>{q=q.target;(t.has(q.tagName.toLowerCase())||p(q))&&this.ic("keyboard-blur")});window.addEventListener("keydown",q=>this.mg("keydown",q));window.addEventListener("keyup",q=>this.mg("keyup",q));window.addEventListener("dblclick",q=>this.Me("dblclick",q,d));window.addEventListener("wheel",q=>this.hk(q));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
q=>{this.Fe(q);this.hc("pointerdown",q)}),this.N.Pa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Lc=new self.Ci(()=>this.sj(),5),this.Lc.Ag=!0,window.addEventListener("pointerrawupdate",q=>this.lk(q))):window.addEventListener("pointermove",q=>this.hc("pointermove",q)),window.addEventListener("pointerup",q=>this.hc("pointerup",q)),window.addEventListener("pointercancel",q=>this.hc("pointercancel",q))):(window.addEventListener("mousedown",q=>{this.Fe(q);this.Ne("pointerdown",
q)}),window.addEventListener("mousemove",q=>this.Ne("pointermove",q)),window.addEventListener("mouseup",q=>this.Ne("pointerup",q)),window.addEventListener("touchstart",q=>{this.Fe(q);this.nd("pointerdown",q)}),window.addEventListener("touchmove",q=>this.nd("pointermove",q)),window.addEventListener("touchend",q=>this.nd("pointerup",q)),window.addEventListener("touchcancel",q=>this.nd("pointercancel",q)));const l=()=>this.Pe();window.addEventListener("pointerup",l,!0);window.addEventListener("touchend",
l,!0);window.addEventListener("click",l,!0);window.addEventListener("keydown",l,!0);window.addEventListener("gamepadconnected",l,!0)}ic(l,q){B(this,l,q||null,w)}qb(){return this.N.qb()}pb(){return this.N.pb()}Ok(){const l=this.qb(),q=this.pb();this.ic("window-resize",{innerWidth:l,innerHeight:q,devicePixelRatio:window.devicePixelRatio,isFullscreen:k.bc()});this.N.ke()&&(-1!==this.Ub&&clearTimeout(this.Ub),this.qg(l,q,0))}Yk(l,q,u){-1!==this.Ub&&clearTimeout(this.Ub);this.Ub=setTimeout(()=>this.qg(l,
q,u),48)}qg(l,q,u){const g=this.qb(),r=this.pb();this.Ub=-1;g!=l||r!=q?this.ic("window-resize",{innerWidth:g,innerHeight:r,devicePixelRatio:window.devicePixelRatio,isFullscreen:k.bc()}):10>u&&this.Yk(g,r,u+1)}xk(l){this.yf=l.targetOrientation}xl(){const l=this.yf;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(l).catch(q=>console.warn("[Construct 3] Failed to lock orientation: ",q));else try{let q=!1;screen.lockOrientation?q=screen.lockOrientation(l):screen.webkitLockOrientation?
q=screen.webkitLockOrientation(l):screen.mozLockOrientation?q=screen.mozLockOrientation(l):screen.msLockOrientation&&(q=screen.msLockOrientation(l));q||console.warn("[Construct 3] Failed to lock orientation")}catch(q){console.warn("[Construct 3] Failed to lock orientation: ",q)}}fc(){const l=k.bc();l&&"any"!==this.yf&&this.xl();B(this,"fullscreenchange",{isFullscreen:l,innerWidth:this.qb(),innerHeight:this.pb()})}Ke(l){console.warn("[Construct 3] Fullscreen request failed: ",l);B(this,"fullscreenerror",
{isFullscreen:k.bc(),innerWidth:this.qb(),innerHeight:this.pb()})}Oe(l){l?this.N.ye():this.N.Qe();B(this,"visibilitychange",{hidden:l})}mg(l,q){"Backspace"===q.key&&A(q);const u=b.get(q.code)||q.code;J(this,l,{code:u,key:q.key,which:q.which,repeat:q.repeat,altKey:q.altKey,ctrlKey:q.ctrlKey,metaKey:q.metaKey,shiftKey:q.shiftKey,timeStamp:q.timeStamp},d)}hk(l){B(this,"wheel",{clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,deltaX:l.deltaX,deltaY:l.deltaY,deltaZ:l.deltaZ,deltaMode:l.deltaMode,
timeStamp:l.timeStamp},d)}Me(l,q,u){a(q)||J(this,l,{button:q.button,buttons:q.buttons,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,timeStamp:q.timeStamp},u)}Ne(l,q){if(!a(q)){var u=this.Ec;"pointerdown"===l&&0!==u?l="pointermove":"pointerup"===l&&0!==q.buttons&&(l="pointermove");J(this,l,{pointerId:1,pointerType:"mouse",button:q.button,buttons:q.buttons,lastButtons:u,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:q.timeStamp},d);this.Ec=q.buttons;this.Me(q.type,q,h)}}hc(l,q){if(this.Lc&&"pointermove"!==l){var u=this.Lc;u.rc||(O(u),u.Ed=Date.now())}u=0;"mouse"===q.pointerType&&(u=this.Ec);J(this,l,{pointerId:q.pointerId,pointerType:q.pointerType,button:q.button,buttons:q.buttons,lastButtons:u,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:q.width||0,height:q.height||0,pressure:q.pressure||0,tangentialPressure:q.tangentialPressure||0,tiltX:q.tiltX||0,
tiltY:q.tiltY||0,twist:q.twist||0,timeStamp:q.timeStamp},d);"mouse"===q.pointerType&&(u="mousemove","pointerdown"===l?u="mousedown":"pointerup"===l&&(u="mouseup"),this.Me(u,q,h),this.Ec=q.buttons)}lk(l){this.jf=l;l=this.Lc;if(-1===l.Vb){var q=Date.now(),u=q-l.Ed,g=l.Dl;u>=g&&l.Ag?(l.Ed=q,l.rc=!0,l.Te(),l.rc=!1):l.Vb=self.setTimeout(l.$g,Math.max(g-u,4))}}sj(){this.hc("pointermove",this.jf);this.jf=null}nd(l,q){for(let u=0,g=q.changedTouches.length;u<g;++u){const r=q.changedTouches[u];J(this,l,{pointerId:r.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:r.clientX,clientY:r.clientY,pageX:r.pageX,pageY:r.pageY,width:2*(r.radiusX||r.webkitRadiusX||0),height:2*(r.radiusY||r.webkitRadiusY||0),pressure:r.force||r.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:r.rotationAngle||0,timeStamp:q.timeStamp},d)}}Fe(l){window!==window.top&&window.focus();this.kg(l.target)&&document.activeElement&&!this.kg(document.activeElement)&&document.activeElement.blur()}kg(l){return!l||l===document||
l===window||l===document.body||"canvas"===l.tagName.toLowerCase()}ij(){this.wg||(this.wg=!0,window.addEventListener("deviceorientation",l=>this.Vj(l)),window.addEventListener("deviceorientationabsolute",l=>this.Wj(l)))}hj(){this.vg||(this.vg=!0,window.addEventListener("devicemotion",l=>this.Uj(l)))}Vj(l){B(this,"deviceorientation",{absolute:!!l.absolute,alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0,timeStamp:l.timeStamp,webkitCompassHeading:l.webkitCompassHeading,webkitCompassAccuracy:l.webkitCompassAccuracy},
d)}Wj(l){B(this,"deviceorientationabsolute",{absolute:!!l.absolute,alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0,timeStamp:l.timeStamp},d)}Uj(l){let q=null;var u=l.acceleration;u&&(q={x:u.x||0,y:u.y||0,z:u.z||0});u=null;var g=l.accelerationIncludingGravity;g&&(u={x:g.x||0,y:g.y||0,z:g.z||0});g=null;const r=l.rotationRate;r&&(g={alpha:r.alpha||0,beta:r.beta||0,gamma:r.gamma||0});B(this,"devicemotion",{acceleration:q,accelerationIncludingGravity:u,rotationRate:g,interval:l.interval,timeStamp:l.timeStamp},
d)}Nk(l){const q=this.N.da;q.style.width=l.styleWidth+"px";q.style.height=l.styleHeight+"px";q.style.marginLeft=l.marginLeft+"px";q.style.marginTop=l.marginTop+"px";this.Hg&&(q.style.display="",this.Hg=!1)}dk(l){const q=l.url;l=l.filename;const u=document.createElement("a"),g=document.body;u.textContent=l;u.href=q;u.download=l;g.appendChild(u);u.click();g.removeChild(u)}async pk(l){var q=l.imageBitmapOpts;l=await self.C3_RasterSvgImageBlob(l.blob,l.imageWidth,l.imageHeight,l.surfaceWidth,l.surfaceHeight);
q=q?await createImageBitmap(l,q):await createImageBitmap(l);return{imageBitmap:q,transferables:[q]}}async $j(l){return await self.C3_GetSvgImageSize(l.blob)}async Jj(l){await m(l.url)}Pe(){var l=[...this.Ob];this.Ob.clear();if(!this.hb)for(const q of l)(l=q.play())&&l.catch(()=>{this.Kd.has(q)||this.Ob.add(q)})}ob(l){if("function"!==typeof l.play)throw Error("missing play function");this.Kd.delete(l);let q;try{q=l.play()}catch(u){this.Ob.add(l);return}q&&q.catch(()=>{this.Kd.has(l)||this.Ob.add(l)})}Gb(l){this.Ob.delete(l);
this.Kd.add(l)}hd(l){this.hb=!!l}ak(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Tj(l){if(l.show){this.xb||(this.xb=document.createElement("div"),this.xb.id="inspectOutline",document.body.appendChild(this.xb));var q=this.xb;q.style.display="";q.style.left=l.left-1+"px";q.style.top=l.top-1+"px";q.style.width=l.width+2+"px";q.style.height=l.height+2+"px";q.textContent=l.name}else this.xb&&(this.xb.style.display="none")}qk(){window.C3_RegisterSW&&window.C3_RegisterSW()}pg(l){window.c3_postToMessagePort&&
(l.from="runtime",window.c3_postToMessagePort(l))}Ej(l,q){return C(this,"js-invoke-function",{name:l,params:q})}Kj(l){alert(l.message)}Pk(l){"entered-fullscreen"===l?(k.ug(!0),this.fc()):"exited-fullscreen"===l?(k.ug(!1),this.fc()):console.warn("Unknown wrapper message: ",l)}})}"use strict";
async function T(k){if(k.Cl)throw Error("already initialised");k.Cl=!0;var a=k.Qd.Ee("dispatchworker.js");k.We=await k.Qd.ce(a,k.X,{name:"DispatchWorker"});a=new MessageChannel;k.ef=a.port1;k.We.postMessage({type:"_init","in-port":a.port2},[a.port2]);k.sf=await V(k)}function U(k){return[k.ef,k.sf]}
async function V(k){const a=k.Ig.length;var b=k.Qd.Ee("jobworker.js");b=await k.Qd.ce(b,k.X,{name:"JobWorker"+a});const d=new MessageChannel,h=new MessageChannel;k.We.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":h.port2},[d.port2,h.port2]);k.Ig.push(b);return h.port1}
self.li=class{constructor(k){this.Qd=k;this.X=k.X;this.X="preview"===k.M?this.X+"workers/":this.X+k.Rd;this.Fl=Math.min(navigator.hardwareConcurrency||2,16);this.We=null;this.Ig=[];this.sf=this.ef=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ea({Wl:!0,Xl:"workermain.js",Xb:["scripts/c3runtime.js"],$d:[],Bf:"",Tl:"scripts/",Ef:[],ah:"html5"}));"use strict";
{function k(a){a.stopPropagation()}self.Ea.Qa(class extends self.Xc{constructor(a){super(a,"list");R(this,"set-selected-index",(b,d)=>this.wk(b,d.selectedIndex));R(this,"add-item",(b,d)=>this.Ij(b,d));R(this,"remove-item",(b,d)=>this.rk(b,d));R(this,"set-item",(b,d)=>this.vk(b,d));R(this,"clear",b=>this.Oj(b));R(this,"load-state",(b,d)=>this.Le(b,d))}Yb(a,b){const d=b.isDropdown,h=b.isMultiSelect,w=b.items,m=document.createElement("select");m.style.position="absolute";m.style.userSelect="none";m.style.webkitUserSelect=
"none";m.multiple=h;d||(m.size=2);for(const f of w)m.add(this.Ae(f));m.addEventListener("touchstart",k);m.addEventListener("touchmove",k);m.addEventListener("touchend",k);m.addEventListener("mousedown",k);m.addEventListener("mouseup",k);m.addEventListener("click",f=>{f.stopPropagation();S(this,"click",a,this.De(m))});m.addEventListener("dblclick",f=>{f.stopPropagation();S(this,"dblclick",a,this.De(m))});m.addEventListener("change",()=>Q(this,"change",a,this.De(m)));b.id&&(m.id=b.id);this.Ta(m,b);
return m}Ae(a){const b=document.createElement("option");b.text=a;return b}De(a){const b=a.selectedIndex,d=[];for(let h=0,w=a.length;h<w;++h)a.options[h].selected&&d.push(h);return{selectedIndex:b,selectedIndices:d}}Ta(a,b){a.title=b.title;a.disabled=!b.isEnabled;a.multiple=!!b.isMultiSelect}wk(a,b){a.selectedIndex=b}Ij(a,b){const d=b.index;b=this.Ae(b.text);0>d?a.add(b):a.add(b,d)}rk(a,b){a.remove(b.index)}vk(a,b){a.options[b.index].text=b.text}Oj(a){a.innerHTML=""}Le(a,b){a.innerHTML="";for(const d of b.items)a.add(this.Ae(d));
a.selectedIndex=b.selectedIndex;for(const d of b.selectedIndices)if(b=a.options[d])b.selected=!0}})}"use strict";
{function k(a){a.stopPropagation()}self.Ea.Qa(class extends self.Xc{constructor(a){super(a,"progress-bar")}Yb(a,b){const d=document.createElement("progress");d.style.position="absolute";d.style.userSelect="none";d.style.webkitUserSelect="none";d.addEventListener("touchstart",k);d.addEventListener("touchmove",k);d.addEventListener("touchend",k);d.addEventListener("mousedown",k);d.addEventListener("mouseup",k);d.addEventListener("click",()=>S(this,"click",a));b.id&&(d.id=b.id);this.Ta(d,b);return d}Ta(a,
b){a.title=b.title;const d=b.value;b=b.max;0<b&&0<=d?(a.max=b,a.value=d):(a.removeAttribute("value"),a.removeAttribute("max"))}})}"use strict";self.Ea.Qa(class extends self.Db{constructor(k){super(k,"mouse");K(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{const k=[],a=2*Math.PI;function b(f){f%=a;0>f&&(f+=a);return f}class d{constructor(f,n,c,e,p,t){this.sc=f;this.tc=n;this.kb=c;this.aa=e;this.Wd=p;this.Bg=t}Fb(){return{tag:this.aa,interp:this.tc,userData:this.Wd,cvt:this.Bg}}eb(){return this.tc}fi(){return"undefined"!==typeof this.Wd}Kf(f){switch(this.kb){case 0:return f;case 1:return Math.fround(f);case 2:return 2===this.tc&&(f=b(f),f/=Math.PI,f=32767*(f-1)),f|=0,-32768>f?-32768:32767<f?32767:f;case 3:return 2===this.tc&&(f=b(f),f/=a,f*=255),f|=
0,0>f?0:255<f?255:f;default:return f}}bg(f,n,c){switch(this.kb){case 0:f.setFloat64(n,c);n+=8;break;case 1:f.setFloat32(n,c);n+=4;break;case 2:f.setInt16(n,c);n+=2;break;case 3:f.setUint8(n,c);n+=1;break;default:f.setFloat32(n,c),n+=4}return n}ed(f){if(2!==this.tc)return f;2===this.kb?f=(f/32767+1)*Math.PI:3===this.kb&&(f=f/255*a);return f}static bd(f,n,c,e,p){switch(f){case 0:return p?c:n;case 1:return n+e*(c-n);case 2:return n===c?f=0:(f=Math.sin(n)*Math.sin(c)+Math.cos(n)*Math.cos(c),f=1<=f?0:
-1>=f?Math.PI:Math.acos(f)),n=0>=Math.cos(c)*Math.sin(n)-Math.sin(c)*Math.cos(n)?b(n+f*e):b(n-f*e);default:return p?c:n}}}class h{constructor(f,n){this.timestamp=f;this.data=n}}class w{constructor(f,n,c){this.ua=f;this.b=f.b;this.H=n;this.U=c;this.mc=[];this.mc.length=this.ua.xa.length;this.lf=this.Fd=0;this.Gg=this.Ud=!1;this.ba=[];this.L=this.C=this.Da=null}Fb(){var f=[];for(let c=0,e=this.ua.xa.length;c<e;++c)f.push(this.eb(this.ua.Sd,c));f={id:this.H,nid:this.U,isTimedOut:this.ji(),interpValues:f,
latestUpdate:null};const n=this.Wh();n&&(f.latestUpdate={timestamp:n.timestamp,data:n.data});return f}Wf(f){this.Gg=!!f}we(f,n){f=f.netValues;var c=this.ua.xa;const e=c.length;this.Ud=!1;for(let p=0;p<e;++p){const t=c[p].Kf(f[p]);this.mc[p]!==t&&(this.mc[p]=t,this.Fd=n,this.ua.Ji(n))}f=n-this.Fd;n-=this.lf;c=this.ua.xg;(this.Ud=100>f&&0===c?!0:1E3>f&&1>=c?95<=n:495<=n)&&this.ua.gi()}xe(f,n,c){const e=this.ua.xa;this.lf=c;f.setUint16(n,this.U);n+=2;for(let p=0,t=this.mc.length;p<t;++p)n=e[p].bg(f,
n,this.mc[p]);return n}ae(f,n){for(let c=0,e=this.ba.length;c<e;++c){const p=this.ba[c];if(p.timestamp===f)return;if(p.timestamp>f){this.ba.splice(c,0,new h(f,n));return}}this.ba.push(new h(f,n))}ji(){return 0===this.ba.length?!1:this.ba[this.ba.length-1].timestamp<this.ua.Sd-3E3}la(){for(;2<this.ba.length&&this.ba[0]!==this.Da&&this.ba[0]!==this.C&&this.ba[0]!==this.L;)this.ba.shift();const f=this.ua.Sd;if(!(this.L&&this.L.timestamp>f&&this.C&&this.C.timestamp<f)){this.L=null;for(let n=0,c=this.ba.length;n<
c;++n){const e=this.ba[n];if(e.timestamp<=f){if(!this.C||e.timestamp>this.C.timestamp)this.Da=this.C,this.C=e}else{this.L=e;break}}}}Wh(){return 0===this.ba.length?null:this.ba[this.ba.length-1]}eb(f,n){if(!this.L&&!this.C)return 0;if(this.L&&!this.C)return this.L.data[n];const c=this.ua.xa;let e,p,t;if(!this.L&&this.C){if(this.Da){var x=this.Da.timestamp;e=this.Da.data[n];p=this.C.timestamp;t=this.C.data[n];f>this.C.timestamp+this.ua.Bd&&(f=this.C.timestamp+this.ua.Bd);x=x===p?0:(f-x)/(p-x);return d.bd(c[n].eb(),
e,t,x,!0)}return this.C.data[n]}x=this.C.timestamp;e=this.C.data[n];p=this.L.timestamp;t=this.L.data[n];x=x===p?0:(f-x)/(p-x);return d.bd(c[n].eb(),e,t,x,!1)}}class m{constructor(f,n,c,e){this.b=f;this.Pc=n;this.Qc=c;this.U=this.b.$h();this.xg=e;this.Wd={};this.Ma=0;this.Bd=250;switch(this.xg){case 1:this.Bd=500;break;case 2:this.Bd=2500}this.xa=[];this.Ca=[];this.yb=new Map;this.Wb=new Set;this.Hc=this.lf=this.Fd=this.Fc=0;this.Lb=!1;this.wd=[];this.Gc=new Map;this.Sd=0;this.b.mh(this)}sb(f){this.U=
f}Ji(f){this.Fd=f}gi(){this.Hc++}hl(){this.Lb=!0}cb(f,n,c,e,p){f=new d(this.xa.length,f,n,c,e,p);switch(n){case 0:this.Ma+=8;break;case 1:this.Ma+=4;break;case 2:this.Ma+=2;break;case 3:this.Ma+=1}this.xa.push(f)}ae(f,n,c){this.Yh(n).ae(f,c)}la(){this.Sd=this.b.ad();for(const f of this.Ca)f.la()}Zh(){const f=[];for(const n of this.xa){const c={tag:n.aa,precision:n.kb,interp:n.eb(),clientvaluetag:n.Bg};n.fi()&&(c.userdata=n.Wd);f.push(c)}return f}Li(f){this.Ma=this.xa.length=0;for(const n of f)this.cb(n.interp,
n.precision,n.tag,n.userdata,n.clientvaluetag)}Yh(f){let n=this.Gc.get(f);if(n)return n;n=new w(this,-1,f);this.Gc.set(f,n);this.Ca.push(n);return n}Xh(f){let n=this.yb.get(f);if(n)return n;n=new w(this,f,this.oh());this.yb.set(f,n);this.Ca.push(n);return n}oh(){do this.Fc++,65535<this.Fc&&(this.Fc=0);while(this.Wb.has(this.Fc));const f=this.Fc;this.Wb.add(f);return f}ne(f){const n=f.H,c=f.U;this.b.j()&&!this.Lb&&this.wd.push(c);this.yb.delete(n);this.Gc.delete(c);this.Wb.delete(c);f=this.Ca.indexOf(f);
-1<f&&this.Ca.splice(f,1)}Hh(){this.wd.length=0;this.yb.clear();this.Gc.clear();this.Wb.clear();this.Ca.length=0}we(f,n){this.Hc=0;for(var c of this.Ca)c.Wf(!1);for(let e=0,p=f.length;e<p;++e){c=f[e];const t=this.Xh(c.uid);t.Wf(!0);t.we(c,n)}for(const e of this.Ca)e.Gg||k.push(e);for(const e of k)this.ne(e);k.length=0}xe(f,n,c){f.setUint16(n,this.U);n+=2;let e=0;this.Lb&&(e=1);f.setUint8(n,e);n+=1;f.setUint16(n,this.Hc);n+=2;f.setUint16(n,this.Ma);n+=2;for(const p of this.Ca)p.Ud&&(n=p.xe(f,n,c));
return n}Bi(f,n){if(this.yb.has(f))console.warn("OverrideNid passed id "+f+" which is already in use and cannot be overridden");else if(this.Wb.has(n))console.warn("OverrideNid passed nid "+n+" which is already in use and cannot be overridden");else{var c=new w(this,f,n);this.yb.set(f,c);this.Wb.add(n);this.Ca.push(c);this.Lb=!0}}oe(f){(f=this.yb.get(f))&&this.ne(f)}pe(f){(f=this.Gc.get(f))&&this.ne(f)}Fb(){return{hasOverriddenNids:this.Lb,netValues:this.xa.map(f=>f.Fb()),netInstances:this.Ca.map(f=>
f.Fb())}}ci(){return{roId:this.Pc,sid:this.Qc,netValues:this.xa.map(f=>f.Fb())}}}self.Jf=d;self.Ch=h;self.Eh=m}"use strict";
{const k=self.Ch,a=self.Jf,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;function d(m){if(m)try{m.close()}catch(f){}}const h=[];class w{constructor(m,f,n){this.b=m;this.H=f;this.U=0;this.fa=n;this.ub=this.J=null;this.vc=!1;this.vb=null;this.xc=!1;this.wb=null;this.$e=this.Sc=this.qc=this.Kb=this.yc=!1;this.Ad=this.Cg=this.hf=0;this.Pg=[];this.Mg=this.Lg=0;this.wa=[];this.L=this.C=this.Da=null;this.Jg=0;this.Se=!1;this.kf=1;this.Gd=
[];this.Sg=this.Hd=0;this.b.ej(this)}sb(m){this.U=m}j(){return this===this.b.R}cd(){return this===this.b.P}jl(){this.Lg=performance.now()}kl(m){this.Mg=m}kd(m,f){m.binaryType="arraybuffer";m.onopen=()=>{"o"===f?this.vc=!0:"r"===f?this.xc=!0:"u"===f&&(this.yc=!0);this.Hj()};m.onmessage=n=>{this.ek(f,n)};m.onerror=n=>{console.error("Peer '"+this.H+"' datachannel '"+f+"' error: ",n);this.b.Ga(this,n);this.b.j()&&!this.j()&&this.T("network error")};m.onclose=()=>{this.T("disconnect")}}Lf(){if(!this.cd()){var m=
this.b.j();this.qc=this.Kb=this.yc=this.xc=this.vc=!1;this.Cg=performance.now();this.J=new b({iceServers:this.b.df});this.J.onicecandidate=n=>{n.candidate&&this.b.Fa({message:"icecandidate",toclientid:this.H,icecandidate:n.candidate})};this.J.onsignalingstatechange=()=>{this.J&&"closed"===this.J.signalingState&&this.T("disconnect")};this.J.oniceconnectionstatechange=()=>{this.J&&("failed"!==this.J.iceConnectionState&&"closed"!==this.J.iceConnectionState||this.T("disconnect"))};this.J.onconnectionstatechange=
()=>{if(this.J){var n=this.J.connectionState;"failed"!==n&&"closed"!==n||this.T("disconnect")}};var f=`c2mp_${this.b.Qh()}_${this.b.Rh()}_${this.b.Sh()}`;m?(this.U=this.b.Ff(),this.ub=this.J.createDataChannel("o",{ordered:!0,protocol:f}),this.kd(this.ub,"o"),this.vb=this.J.createDataChannel("r",{ordered:!1,protocol:f}),this.kd(this.vb,"r"),this.wb=this.J.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:f}),this.kd(this.wb,"u"),this.J.createOffer().then(n=>{this.J.setLocalDescription(n);
this.b.Fa({message:"offer",toclientid:this.H,offer:n})}).catch(n=>{console.error("Host error creating offer for peer '"+this.H+"': ",n);this.b.Ga(this,"could not create offer for peer")})):this.J.ondatachannel=n=>{if(n.channel.protocol!==f)console.error("Unexpected datachannel protocol '"+n.channel.protocol+"', should be '"+f+"'"),this.b.Ga(this,"unexpected datachannel protocol '"+n.channel.protocol+"', should be '"+f+"'");else{var c=n.channel.label;"o"===c?this.ub=n.channel:"r"===c?this.vb=n.channel:
"u"===c?this.wb=n.channel:(console.error("Unknown datachannel label: "+n.channel.label),this.b.Ga(this,"unknown datachannel label '"+n.channel.label+"'"));this.kd(n.channel,c)}}}}async dj(m){if(this.J)try{await this.J.addIceCandidate(m)}catch(f){console.warn("[Multiplayer] Error adding ICE candidate: ",f)}}ei(){return!!this.J}Hj(){!this.Kb&&this.xc&&this.yc&&this.vc&&(this.ik(),this.Kb=!0,this.qc=!1)}ik(){this.hf=performance.now();if(this.b.j()){this.b.ac("o",JSON.stringify({c:"j",i:this.H,n:this.U,
a:this.fa}),this);this.fb("o",JSON.stringify({c:"hi",hn:this.b.R.U,n:this.U,d:this.b.Aa,u:this.b.Jc,objs:this.b.bi(),cvs:this.b.Ph()}));for(const m of this.b.Ia)!m.j()&&m!==this&&m.je()&&this.fb("o",JSON.stringify({c:"j",i:m.H,n:m.U,a:m.fa}))}else this.$e=!0,this.j()&&this.re(performance.now(),!0);this.b.og(this)}Gj(m){!this.qc&&this.Kb&&(this.Pj(m),this.qc=!0,this.Kb=!1)}Pj(m){this.b.j()&&!this.cd()&&this.b.ac("o",JSON.stringify({c:"l",i:this.H,a:this.fa,r:m}),this);this.cd()||this.b.ng(this,m)}je(){return this.Kb&&
!this.qc}fb(m,f){this.b.$i();var n=0;f.length?n=f.length:f.byteLength&&(n=f.byteLength);this.b.Yi(n);n=this.b.wf;const c=this.b.vf,e=this.b.xf;if(!(0<n&&"u"===m&&Math.random()<n))if(0===c&&0===e)this.fg(m,f);else{let p=1;"u"!==m&&Math.random()<n&&(p=3);setTimeout(()=>this.fg(m,f),c*p+Math.random()*e*p)}}fg(m,f){try{"o"===m?this.vc&&this.ub&&this.ub.send(f):"r"===m?this.xc&&this.vb&&this.vb.send(f):"u"===m&&this.yc&&this.wb&&this.wb.send(f)}catch(n){this.Sc||(this.b.j()?"o"===m||"r"===m?("string"===
typeof f?(console.error("Error sending "+f.length+"-char string on '"+m+"' to '"+this.fa+"', host kicking: ",n),console.log("String that failed to send from previous error was: "+f)):console.error("Error sending "+(f.length||f.byteLength)+"-byte binary on '"+m+"' to '"+this.fa+"', host kicking: ",n),this.T("network error")):(this.Ad++,10<=this.Ad&&("string"===typeof f?(console.error("Too many errors ("+this.Ad+") sending data on '"+m+"' to '"+this.fa+"', kicking; last error was for sending "+f.length+
"-char string: ",n),console.log("String that failed to send from previous error was: "+f)):console.error("Too many errors ("+this.Ad+") sending data on '"+m+"' to '"+this.fa+"', kicking; last error was for sending "+(f.length||f.byteLength)+"-byte binary: ",n),this.T("network error"))):console.error("Error sending data on '"+m+"': ",n))}}re(m,f){this.Sc||(!f&&!this.je()&&this.J&&25E3<m-this.Cg?(console.warn("Timed out '"+this.fa+"', could not establish connection after 25sec"),this.T("timeout")):
!f&&this.je()&&2E4<m-this.hf?(console.warn("Timed out '"+this.fa+"', not heard from for 20sec"),this.T("timeout")):(this.Jg=m,this.Se=!0,this.kf++,this.fb("u","ping:"+this.kf)))}Fi(m){m="pong:"+m.substr(5);this.b.j()&&(m=m+"/"+Math.round(performance.now()).toString());this.fb("u",m)}mk(m){if(this.Se){var f=m.indexOf(":");if(-1<f){if(parseFloat(m.substr(f+1))===this.kf){f=performance.now();this.Se=!1;var n=(f-this.Jg)/2;this.Gd.push(n);10<this.Gd.length&&this.Gd.shift();h.push(...this.Gd);h.sort((t,
x)=>t-x);this.Sg=h[h.length-1]-h[0];var c=0,e=h.length;4<=h.length&&6>=h.length?(++c,--e):6<h.length&&(c+=2,e-=2);var p=0;for(let t=c;t<e;++t)p+=h[t];this.Hd=p/(e-c);h.length=0;this.b.j()||(c=m.indexOf("/"),-1<c?(m=parseFloat(m.substr(c+1)),isFinite(m)?this.b.lh(m,f,n,this.Hd):console.warn("Invalid host time from pong response")):console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}ek(m,f){const n=this.b.wf,c=this.b.vf,e=this.b.xf;
if(!(0<n&&"u"===m&&Math.random()<n))if(0===c&&0===e)this.eg(m,f);else{let p=1;"u"!==m&&Math.random()<n&&(p=3);setTimeout(()=>this.eg(m,f),c*p+Math.random()*e*p)}}eg(m,f){if(!this.Sc){this.hf=performance.now();this.b.Zi();var n=0;f.data.length?n=f.data.length:f.data.byteLength&&(n=f.data.byteLength);this.b.Xi(n);if("string"===typeof f.data){if(!(""===f.data.trim()||4>f.data.length))if(m=f.data.substr(0,4),"ping"===m)this.Fi(f.data);else if("pong"===m)this.mk(f.data);else{try{var c=JSON.parse(f.data)}catch(e){this.b.Ga(this,
e);this.b.j()?(console.error("Error parsing message as JSON for peer '"+this.H+"', host kicking: ",e),this.T("data error")):console.error("Error parsing message as JSON for peer '"+this.H+"': ",e);console.log("String that failed to parse from previous error: "+f.data);return}if(c)try{c.c&&"m"!==c.c?this.Qj(c):this.b.jk(this,c)}catch(e){this.b.Ga(this,e),this.b.j()?(console.error("Error handling message for peer '"+this.H+"', host kicking: ",e),this.T("data error")):console.error("Error handling message for peer '"+
this.H+"': ",e)}}}else{!this.$e&&this.b.j()&&"u"===m&&(this.$e=!0,this.b.Ri(this.H));try{this.Nj(f.data)}catch(e){this.b.Ga(this,e),this.b.j()?(console.error("Error handling binary update for peer '"+this.H+"', host kicking: ",e),this.T("data error")):console.error("Error handling binary update for peer '"+this.H+"': ",e)}}}}Qj(m){switch(m.c){case "disconnect":m.k&&B(this.b,"peer-kicked");var f=!this.b.j()&&!this.j();this.T(m.r);f&&this.b.ue();break;case "hi":this.b.j()||(this.b.R.sb(m.hn),this.b.P.sb(m.n),
this.b.Ii(m.d),this.b.Ni(m.u),this.b.ri(m.objs),this.b.pi(m.cvs));break;case "j":this.b.j()||(f=new w(this.b,m.i,m.a),f.sb(m.n),this.b.og(f));break;case "l":!this.b.j()&&(f=this.b.$c(m.i))&&(f.cd()||this.b.ng(f,m.r),f.T(m.r));break;default:console.error("Unknown control message from peer '"+this.H+"': "+m.c),this.b.Ga(this,"unknown control message '"+m.c+"'")}}Nj(m){this.b.j()?this.bk(m):this.kk(m)}bk(m){m=new DataView(m);let f=0;var n=m.getUint32(f);f+=4;if(1664249200!==n)console.warn("Rejected packet with incorrect magic number (received '"+
n+"', expected '1664249200'");else if(n=m.getFloat64(f),f+=8,n+=this.Hd,!(3E3<=Math.abs(n-performance.now()))){m.getUint8(f);f+=1;var c=m.getUint8(f);f+=1;var e=[],p=this.b.Ha;for(let x=0;x<c;++x)if(x>=p.length)e.push(0);else{var t=p[x];switch(t.kb){case 0:t=m.getFloat64(f);f+=8;break;case 1:t=m.getFloat32(f);f+=4;break;case 2:t=t.ed(m.getInt16(f));f+=2;break;case 3:t=t.ed(m.getUint8(f));f+=1;break;default:t=m.getFloat32(f),f+=4}e.push(t)}this.cj(n,e)}}cj(m,f){for(let n=0,c=this.wa.length;n<c;++n){const e=
this.wa[n];if(e.timestamp===m)return;if(e.timestamp>m){this.wa.splice(n,0,new k(m,f));return}}this.wa.push(new k(m,f))}la(m){if(0!==this.wa.length){for(;2<this.wa.length&&this.wa[0]!==this.Da&&this.wa[0]!==this.C&&this.wa[0]!==this.L;)this.wa.shift();if(!(this.L&&this.L.timestamp>m&&this.C&&this.C.timestamp<m)){this.L=null;for(let f=0,n=this.wa.length;f<n;++f){const c=this.wa[f];if(c.timestamp<=m){if(!this.C||c.timestamp>this.C.timestamp)this.Da=this.C,this.C=c}else{this.L=c;break}}}}}kk(m){m=new DataView(m);
let f=0;var n=m.getUint32(f);f+=4;1664249200!==n?console.warn("Rejected packet with incorrect magic number (received '"+n+"', expected '1664249200'"):(n=m.getUint32(f),f+=4,0===n?this.Bj(m,f):1===n?this.Aj(m,f):console.warn("Ignoring packet with incorrect flags (received "+n+", expected 0 or 1"))}Bj(m,f){const n=m.getFloat64(f);f+=8;const c=m.getUint16(f);f+=2;for(let x=0;x<c;++x){var e=m.getUint16(f);f+=2;var p=m.getUint8(f);f+=1;let A=null,F=0;const G=this.b.Qf(e);G?(A=G.xa,F=A.length,1===p&&G.hl()):
console.warn("Don't know which object corresponds to NID "+e);e=m.getUint16(f);f+=2;p=m.getUint16(f);f+=2;for(let I=0;I<e;++I){const l=m.getUint16(f);f+=2;if(G){const q=[];let u=f;for(let g=0;g<F;++g){var t=A[g];switch(t.kb){case 0:t=m.getFloat64(u);u+=8;break;case 1:t=m.getFloat32(u);u+=4;break;case 2:t=t.ed(m.getInt16(u));u+=2;break;case 3:t=t.ed(m.getUint8(u));u+=1;break;default:t=m.getFloat32(u),u+=4}q.push(t)}G.ae(n,l,q)}f+=p}}}Aj(m,f){const n=m.getFloat64(f);f+=8;const c=m.getUint16(f);f+=2;
for(let p=0;p<c;++p){var e=m.getUint16(f);f+=2;const t=this.b.Qf(e);t||console.warn("Don't know which object corresponds to NID "+e);e=m.getUint16(f);f+=2;for(let x=0;x<e;++x){const A=m.getUint16(f);f+=2;t&&!t.Lb&&(this.b.ck(t,A,n),t.pe(A))}}}T(m,f){if(!this.Sc){this.Sc=!0;this.Gj(m);this.fb("o",JSON.stringify({c:"disconnect",r:m,k:!!f}));var n=this.ub,c=this.vb,e=this.wb,p=this.J;setTimeout(()=>{d(n);d(c);d(e);d(p)},0);this.J=this.wb=this.vb=this.ub=null;this.yc=this.xc=this.vc=!1;this.b.Vk(this)}}Vh(m){m=
m.sc;if(!this.L&&!this.C)return 0;if(this.L&&!this.C){var f=this.L.data;return 0>m||m>=f.length?0:f[m]}var n=this.b.ad();let c,e;if(!this.L&&this.C){if(this.Da){var p=this.Da.timestamp;f=this.Da.data[m];c=this.C.timestamp;e=this.C.data[m];n>this.C.timestamp+250&&(n=this.C.timestamp+250);p=p===c?0:(n-p)/(c-p);return a.bd(this.b.Ha[m].eb(),f,e,p,!0)}f=this.C.data;return 0>m||m>=f.length?0:f[m]}p=this.C.timestamp;f=this.C.data[m];c=this.L.timestamp;e=this.L.data[m];p=p===c?0:(n-p)/(c-p);return a.bd(this.b.Ha[m].eb(),
f,e,p,!1)}}self.Dh=w}"use strict";
{const k=self.Jf,a=self.Dh,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,d=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,h=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,w=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,m=[{urls:"stun:stun.l.google.com:19302"}];
let f=!1;const n=[];self.Ea.Qa(class extends self.Db{constructor(c){super(c,"multiplayer");this.df=[];this.V=null;this.ta=this.Na=!1;this.Kl={ih:0,version:0,name:"",fh:"",eh:""};this.ma=this.Ye=this.Xe=this.qf=this.rf="";this.Ia=[];this.Za=new Map;this.Pb=0;this.Vd=new Set;this.R=this.P=null;this.Aa=80;this.Jc=this.cf=30;this.Og=0;this.Bb={Vc:0,hh:0,Cf:0,gh:0,Zd:0,dh:0,Af:0,bh:0,Yd:0};this.vd=new ArrayBuffer(262144);this.Ve=new DataView(this.vd);this.za=[];this.Hl=1;this.Mc=new Map;this.Nc=new Map;
this.wf=this.xf=this.vf=0;this.zb=[];this.ea=this.Oa=0;this.na=this.ab=this.Aa;this.Ha=[];this.ud=new Map;this.uf=!1;this.Ie(m);setInterval(()=>this.qj(),2E3);window.addEventListener("unload",()=>this.ec("quit"));K(this,"get-supported",()=>this.Zj());K(this,"add-ice-servers",e=>this.Ie(e.list));K(this,"simulate-latency",e=>this.Ki(e.latency,e.pdv,e.loss));K(this,"set-bandwidth-profile",e=>this.Hi(e.updateRate,e.delay));K(this,"tick",e=>this.la(e));K(this,"alert",e=>this.nh(e));K(this,"signalling-connect",
e=>this.Si(e.url));K(this,"signalling-disconnect",()=>this.ag());K(this,"signalling-login",e=>this.Ui(e.alias));K(this,"signalling-join-room",e=>this.Ti(e.game,e.instance,e.room,e.maxClients));K(this,"signalling-auto-join-room",e=>this.Qi(e.game,e.instance,e.room,e.maxClients,e.lock));K(this,"signalling-leave-room",()=>this.ue());K(this,"signalling-list-game-instances",e=>this.Vi(e.game));K(this,"signalling-list-rooms",e=>this.Wi(e.game,e.instance,e.which));K(this,"disconnect-room",()=>this.Of(!0));
K(this,"peer-send-message",e=>this.wi(e));K(this,"host-broadcast",e=>this.ti(e));K(this,"kick-peer",e=>this.vi(e));K(this,"sync-object",e=>this.Ai(e));K(this,"sync-inst-var",e=>this.zi(e));K(this,"associate-object",e=>this.si(e));K(this,"remove-object-id",e=>this.oe(e.uid));K(this,"remove-net-insts",e=>this.xi(e));K(this,"remove-object-nid",e=>this.yi(e));K(this,"set-client-state",e=>this.Xf(e.tag,e.value));K(this,"add-client-input-value",e=>this.jh(e.tag,e.precision,e.interp))}wj(c){return c?"string"===
typeof c?c:"string"===typeof c.message?c.message:"string"===typeof c.details?c.details:"string"===typeof c.data?c.data:"string"===typeof c.type?c.type:"unknown error":"unknown error"}ie(){return this.Na&&this.ta}cc(){return this.ie()&&this.ma}j(){return this.cc()&&this.P&&this.R===this.P}Qh(){return this.ie()?this.Xe:""}Rh(){return this.ie()?this.Ye:""}Sh(){return this.cc()?this.ma:""}Ki(c,e,p){this.vf=Math.max(c,0);this.xf=Math.max(e,0);this.wf=Math.max(p,0)}Zj(){return{isSupported:!(!b||!w)}}Si(c){if(!this.V&&
!this.Na){try{this.V=new WebSocket(c,"c2multiplayer")}catch(e){this.V=null;this.rb(e);return}this.V.onopen=()=>{-1===this.V.protocol.indexOf("c2multiplayer")?(this.rb("server does not support 'c2multiplayer' protocol"),this.V.close(1002,"'c2multiplayer' protocol required"),this.V=null,this.Na=!1):this.Na=!0};this.V.onclose=()=>{this.yk();this.ta=this.Na=!1;this.V=null};this.V.onerror=e=>{console.error("Signalling server error: ",e);this.rb(e)};this.V.onmessage=e=>{this.zk(e)}}}ag(){this.V&&this.Na&&
(this.V.close(),this.V=null,this.Na=!1)}zk(c){let e;try{e=JSON.parse(c.data)}catch(p){this.rb(p);return}switch(e.message){case "welcome":this.Lk(e);break;case "login-ok":this.Gk(e);break;case "join-ok":this.Dk(e);break;case "leave-ok":this.Fk();break;case "kicked":this.Ek();break;case "peer-joined":this.Ik(e);break;case "peer-quit":this.Jk(e);break;case "icecandidate":this.Bk(e);break;case "offer":this.Hk(e);break;case "answer":this.Ak(e);break;case "instance-list":this.Ck(e);break;case "room-list":this.Kk(e);
break;case "error":this.rb(e.details);break;default:this.rb("received unknown signalling message")}}di(c){for(const e of this.df)if(e.urls===c.urls)return!0;return!1}Ie(c){if(c)for(let e of c)"string"===typeof e&&(e={urls:e}),this.di(e)||(e.hasOwnProperty("url")||(e.url=e.urls),this.df.push(e))}rb(c){B(this,"signalling-error",{message:this.wj(c)})}yk(){B(this,"signalling-close")}Lk(c){if(1>c.protocolrev||1<c.protocolrev)this.rb("signalling server protocol revision not supported"),this.ag();else{this.rf=
c.clientid;var e=this.Kl;e.ih=c.protocolrev;e.version=c.version;e.name=c.name;e.fh=c.operator;e.eh=c.motd;this.Ie(c.ice_servers);B(this,"signalling-welcome",{myid:this.rf,sigservinfo:{protocolrev:e.ih,version:e.version,name:e.name,operator:e.fh,motd:e.eh}})}}Gk(c){this.qf=c.alias;this.ta=!0;B(this,"signalling-login-ok",{myalias:this.qf})}$h(){return this.Hl++}Ff(){if(this.j()){do this.Pb++,65535<this.Pb&&(this.Pb=0);while(this.Vd.has(this.Pb));var c=this.Pb;this.Vd.add(c);return c}}Nh(c){this.j()&&
this.Vd.delete(c)}Dk(c){this.ec("disconnect");this.Xe=c.game;this.Ye=c.instance;this.ma=c.room;this.P=new a(this,this.rf,this.qf);c.host?(this.R=this.P,this.Pb=0,this.Vd.clear(),this.R.sb(this.Ff())):(this.ea=this.Oa=this.zb.length=0,this.Aa=80,this.Jc=this.cf=30,this.na=this.ab=this.Aa,this.R=new a(this,c.hostid,c.hostalias),this.R.Lf());B(this,"signalling-join-ok",{isHost:!!c.host,hostId:this.R.H,hostAlias:this.R.fa,game:this.Xe,gameInstance:this.Ye,room:this.ma})}Fk(){this.ma="";B(this,"signalling-leave-ok")}Ek(){this.Of();
this.ma="";B(this,"signalling-kicked")}Ik(c){if(this.ta&&this.ma&&this.j()){var e=this.Za.get(c.peerid);e&&e.T("rejoin");(new a(this,c.peerid,c.peeralias)).Lf()}}Jk(c){if(this.ta&&this.ma&&this.j()){var e=this.Za.get(c.id);e&&e.T(c.reason)}}Bk(c){if(this.ta&&this.ma){var e=this.Za.get(c.from);e&&e.dj(new h(c.icecandidate))}}Hk(c){if(this.ta&&this.ma&&!this.j()&&this.P&&this.R&&this.R.ei()&&c.from===this.R.H){var e=this.R.J;e.setRemoteDescription(new d(c.offer)).then(()=>{e.createAnswer().then(p=>
{e.setLocalDescription(p);this.Fa({message:"answer",toclientid:this.R.H,answer:p})}).catch(p=>{console.error("Peer error creating answer: ",p);this.Ga(this.P,"could not create answer to host offer")})}).catch(p=>{console.error("Peer error setting remote description: ",p);this.Ga(this.P,"could not set remote description")})}}Ak(c){if(this.ta&&this.ma&&this.j()){var e=this.Za.get(c.from);e&&e.J.setRemoteDescription(new d(c.answer)).catch(p=>{console.error("Host error setting remote description: ",p)})}}Ck(c){B(this,
"signalling-instance-list",{list:c.list})}Kk(c){B(this,"signalling-room-list",{list:c.list})}Fa(c){this.V&&this.Na&&this.V.send(JSON.stringify(c))}Ui(c){this.ta||this.Fa({message:"login",protocolrev:1,alias:c})}Ti(c,e,p,t){this.ta&&!this.ma&&this.Fa({message:"join",game:c,instance:e,room:p,max_clients:t})}Qi(c,e,p,t,x){this.ta&&!this.ma&&this.Fa({message:"auto-join",game:c,instance:e,room:p,max_clients:t,lock_when_full:x})}ue(){this.ta&&this.Fa({message:"leave"})}Ri(c){this.ta&&this.j()&&this.Fa({message:"confirm-peer",
id:c})}Vi(c){this.V&&this.Na&&this.Fa({message:"list-instances",game:c})}Wi(c,e,p){this.V&&this.Na&&this.Fa({message:"list-rooms",game:c,instance:e,which:p})}Of(c){this.ea=this.Oa=this.zb.length=0;this.ec("disconnect");for(const e of this.za)e.Hh();c&&this.ue()}ej(c){this.Ia.push(c);this.Za.set(c.H,c);B(this,"add-peer",{id:c.H,alias:c.fa})}Vk(c){B(this,"remove-peer",{id:c.H});this.j()&&this.Nh(c.U);const e=this.Ia.indexOf(c);-1<e&&this.Ia.splice(e,1);this.Za.delete(c.H);this.R===c&&(this.R=null,this.ec("host quit"));
this.P===c&&(this.P=null,this.ma="",this.ec("disconnect"))}ec(c){if(!f){for(f=!0;this.Ia.length;)this.Ia[0].T(c);f=!1}}$c(c){return this.Za.get(c)||null}Oh(c){return(c=this.Za.get(c))?c.fa:""}ti(c){const e=c.fromId,p=c.tag,t=c.message;c=c.mode;const x=this.$c(e);this.ac(c,JSON.stringify({c:"m",t:p,f:e,m:t}),x)}ac(c,e,p){if(this.j()){var t=this.Ia.slice(0);for(const x of t)x&&x!==this.P&&x!==p&&x.fb(c,e)}}qj(){const c=performance.now();if(this.j()){n.push(...this.Ia);for(const e of n)e&&e!==this.P&&
e.re(c,!1);n.length=0}else this.R&&this.R.re(c,!1)}mh(c){this.za.push(c);this.Nc.set(c.Pc,c);this.Mc.set(c.U,c)}bi(){const c={};for(const [e,p]of this.Mc.entries())c[p.Qc]={nid:e,nvs:p.Zh()};return c}ri(c){this.Mc.clear();for(const e of this.za)if(c.hasOwnProperty(e.Qc.toString())){const p=c[e.Qc.toString()];e.sb(p.nid);this.Mc.set(p.nid,e);e.Li(p.nvs)}else console.warn("Could not map object SID '"+e.Qc+"' - host did not send NID for it"),e.sb(-1)}Qf(c){return this.Mc.get(c)||null}la(c){if(!this.cc())return null;
c=c.dt;const e=performance.now();e-this.Og>=1E3/(this.j()?this.cf:this.Jc)-5&&(this.Gi(e),this.Og=e);const p=this.Bb;1E3<=e-p.Vc&&(p.hh=p.Cf,p.gh=p.Zd,p.dh=p.Af,p.bh=p.Yd,p.Cf=0,p.Zd=0,p.Af=0,p.Yd=0,p.Vc+=1E3,500<e-p.Vc&&(p.Vc=e),B(this,"stats",{stats:{outboundPerSec:p.hh,outboundBandwidthPerSec:p.gh,inboundPerSec:p.dh,inboundBandwidthPerSec:p.bh}}));this.j()||(this.ea<this.Oa?(this.ea+=10*c,this.ea>this.Oa&&(this.ea=this.Oa)):this.ea>this.Oa&&(this.ea-=10*c,this.ea<this.Oa&&(this.ea=this.Oa)),this.na<
this.ab?(this.na+=30*c,this.na>this.ab&&(this.na=this.ab)):this.na>this.ab&&(this.na-=30*c,this.na<this.ab&&(this.na=this.ab)));c=this.ad();for(const t of this.Ia)t.la(c);for(const t of this.za)t.la();return{simulationTime:this.ad(),hostInputArrivalTime:this.Uh(),clientDelay:this.Aa,peerData:this.yj(),roData:this.zj(),isReadyForInput:this.Sf()}}yj(){const c={};for(const e of this.Ia){const p={};for(const t of this.Ha)p[t.aa]=e.Vh(t);c[e.H]={nid:e.U,latency:e.Hd,pdv:e.Sg,clientState:p}}return c}zj(){const c=
{};for(const e of this.za)c[e.Pc]=e.Fb();return c}async Gi(c){this.j()?(await this.bl(c),this.al(c)):await this.$k(c)}async Lj(){const c=await C(this,"before-client-update");for(const e of c.clientStateUpdates)this.Xf(e.tag,e.value)}async $k(c){this.Sf()&&await this.Lj();if(this.P&&this.uf){var e=this.Ve,p=0,t=this.Ha,x=this.P.Pg,A=c-this.P.Lg,F=c-this.P.Mg;if(100>A||(1E3>A?95<=F:495<=F)){e.setUint32(p,1664249200);p+=4;e.setFloat64(p,c+this.ea);p+=8;e.setUint8(p,0);p+=1;e.setUint8(p,t.length);p+=
1;for(let G=0,I=t.length;G<I;++G)A=t[G],F=0,G<x.length&&(F=A.Kf(x[G])),p=A.bg(e,p,F);this.P.kl(c);this.R.fb("u",new Uint8Array(this.vd.slice(0,p)))}}}async bl(c){const e=this.Ve;let p=0,t=0;const x=await C(this,"get-object-info",{ros:this.za.map(A=>A.ci())});for(const A of this.za){const F=A.Pc;x.hasOwnProperty(F)&&(A.we(x[F],c),0<A.Hc&&t++)}if(0!==t){e.setUint32(p,1664249200);p+=4;e.setUint32(p,0);p+=4;e.setFloat64(p,c);p+=8;e.setUint16(p,t);p+=2;for(const A of this.za)0<A.Hc&&(p=A.xe(e,p,c));this.ac("u",
new Uint8Array(this.vd.slice(0,p)),null)}}al(c){const e=this.Ve;let p=0,t=0;for(const x of this.za)x.wd.length&&t++;if(0!==t){e.setUint32(p,1664249200);p+=4;e.setUint32(p,1);p+=4;e.setFloat64(p,c);p+=8;e.setUint16(p,t);p+=2;for(const x of this.za)if(c=x.wd,c.length){e.setUint16(p,x.U);p+=2;e.setUint16(p,c.length);p+=2;for(const A of c)e.setUint16(p,A),p+=2;c.length=0}this.ac("r",new Uint8Array(this.vd.slice(0,p)),null)}}lh(c,e,p,t){if(!this.j()){this.ab=t+this.Aa;c=c+p-e;0===this.zb.length&&(this.ea=
c,this.na=this.ab);this.zb.push(c);30<this.zb.length&&this.zb.shift();n.push(...this.zb);n.sort((x,A)=>x-A);c=0;e=n.length;4<=n.length&&6>=n.length?(++c,--e):6<n.length&&19>=n.length?(c+=2,e-=2):19<n.length&&(c+=5,e-=5);p=0;for(t=c;t<e;++t)p+=n[t];this.Oa=p/(e-c);n.length=0}}ad(){return this.j()?performance.now()-this.Aa:performance.now()+this.ea-this.na}Uh(){return this.j()?performance.now():performance.now()+this.ea+this.na}Xf(c,e){if(!this.j()&&this.P&&this.uf&&(c=this.ud.get(c))){c=c.sc;var p=
this.P.Pg;p.length<c+1&&(p.length=c+1);p[c]!==e&&(p[c]=e,this.P.jl())}}jh(c,e,p){e=new k(this.Ha.length,p,e,c,null);this.ud.set(c,e);this.Ha.push(e)}Ph(){const c=[];for(const e of this.Ha)c.push({tag:e.aa,precision:e.kb,interp:e.eb()});return c}pi(c){this.ud.clear();this.Ha.length=0;for(let p=0,t=c.length;p<t;++p){var e=c[p];e=new k(p,e.interp,e.precision,e.tag,null);this.ud.set(e.aa,e);this.Ha.push(e)}this.uf=!0}oe(c){for(const e of this.za)e.oe(c)}Sf(){return this.cc()?this.j()?!0:0!==this.Oa:!1}Hi(c,
e){this.cc()||(this.Jc=this.cf=c,this.Aa=e)}og(c){B(this,"peer-open",{id:c.H,alias:c.fa})}wi(c){const e=c.tag,p=c.message,t=c.mode;(c=this.$c(c.id))&&c.fb(t,JSON.stringify({c:"m",t:e,m:p}))}ng(c,e){B(this,"peer-close",{id:c.H,alias:c.fa,reason:e||"unknown"})}Ga(c,e){console.error(`[Multiplayer] Peer '${c.fa}' (${c.H}) error: `,e)}jk(c,e){c=e.f||c.H;B(this,"peer-message",{tag:e.t,fromId:c,fromAlias:this.Oh(c),content:e.m})}ck(c,e,p){B(this,"instance-destroyed",{roId:c.Pc,nid:e,timestamp:p})}vi(c){if(this.j()){var e=
c.reason;(c=this.$c(c.id))&&c.T(e,!0)}}$i(){this.Bb.Cf++}Yi(c){this.Bb.Zd+=c}Zi(){this.Bb.Af++}Xi(c){this.Bb.Yd+=c}Ii(c){this.Aa=c}Ni(c){this.Jc=c}Ai(c){const e=c.data,p=c.precision,t=c.bandwidth;for(const x of c.objectClasses)c=new self.Eh(this,x.roId,x.sid,t),1===e?(c.cb(1,p,"x"),c.cb(1,p,"y")):2===e?c.cb(2,p,"a"):3===e&&(c.cb(1,p,"x"),c.cb(1,p,"y"),c.cb(2,p,"a"))}nh(c){alert(c.message)}zi(c){const e=c.precision,p=c.interp,t=c.cvt;for(const x of c.syncData)this.Nc.get(x.roId).cb(p,e,"iv",x.varIndex,
t)}si(c){var e=c.peerId;const p=c.instUid;c=this.Nc.get(c.roId);e=this.Za.get(e);c&&e&&this.j()&&c.Bi(p,e.U)}xi(c){for(const [e,p]of Object.entries(c))if(c=this.Nc.get(parseInt(e,10)))for(const t of p)c.pe(t)}yi(c){const e=c.nid;(c=this.Nc.get(c.roId))&&c.pe(e)}})}"use strict";async function W(k,a){a=a.type;let b=!0;0===a?b=await X():1===a&&(b=await aa());B(k,"permission-result",{type:a,result:b})}
async function X(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(k){return console.warn("[Touch] Failed to request orientation permission: ",k),!1}}
async function aa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(k){return console.warn("[Touch] Failed to request motion permission: ",k),!1}}self.Ea.Qa(class extends self.Db{constructor(k){super(k,"touch");K(this,"request-permission",a=>W(this,a))}});"use strict";
{const k=180/Math.PI;self.Ra=class extends self.Db{constructor(a){super(a,"audio");this.yd=this.o=null;this.Cd=this.bf=!1;this.lb=()=>this.yl();this.Ka=[];this.W=[];this.Va=null;this.Kg="";this.Ng=-1;this.Kc=new Map;this.mf=1;this.hb=!1;this.zf=0;this.Td=1;this.Ze=0;this.Rg="HRTF";this.Dg="inverse";this.Tg=600;this.Qg=1E4;this.Vg=1;this.Fg=this.tf=!1;this.Yg=this.N.ii();this.La=new Map;this.Jb=new Set;this.ff=!1;this.nf="";this.Ab=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.gk(b,d);this.xd=null;
self.C3Audio_GetOutputStream=()=>this.Yj();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.nj(b)],["play",b=>this.Rk(b)],["stop",b=>this.vl(b)],["stop-all",()=>this.wl()],["set-paused",b=>this.ol(b)],["set-volume",b=>this.tl(b)],["fade-volume",b=>this.tj(b)],["set-master-volume",b=>this.ml(b)],["set-muted",b=>this.nl(b)],["set-silent",b=>this.ql(b)],["set-looping",b=>this.ll(b)],["set-playback-rate",b=>this.pl(b)],["seek",b=>this.Zk(b)],["preload",b=>this.Sk(b)],["unload",b=>
this.zl(b)],["unload-all",()=>this.Al()],["set-suspended",b=>this.rl(b)],["add-effect",b=>this.cg(b)],["set-effect-param",b=>this.fl(b)],["remove-effects",b=>this.Uk(b)],["tick",b=>this.Mk(b)],["load-state",b=>this.Le(b)]])}async nj(a){a.isiOSCordova&&(this.tf=!0);this.zf=a.timeScaleMode;this.Rg=["equalpower","HRTF","soundfield"][a.panningModel];this.Dg=["linear","inverse","exponential"][a.distanceModel];this.Tg=a.refDistance;this.Qg=a.maxDistance;this.Vg=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.Yg||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.o=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.o=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.dg();this.o.onstatechange=()=>{"running"!==this.o.state&&this.dg()};this.yd=this.o.createGain();this.yd.connect(this.o.destination);b=a.listenerPos;this.o.listener.setPosition(b[0],b[1],b[2]);this.o.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.de();try{await Promise.all(a.preloadList.map(d=>this.ld(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.o.sampleRate}}dg(){this.Cd||(this.bf=!1,window.addEventListener("pointerup",this.lb,!0),window.addEventListener("touchend",this.lb,!0),window.addEventListener("click",this.lb,!0),window.addEventListener("keydown",this.lb,!0),this.Cd=!0)}pj(){this.Cd&&(this.bf=!0,window.removeEventListener("pointerup",this.lb,!0),window.removeEventListener("touchend",
this.lb,!0),window.removeEventListener("click",this.lb,!0),window.removeEventListener("keydown",this.lb,!0),this.Cd=!1)}yl(){if(!this.bf){var a=this.o;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.pj()}}va(){return this.o}de(){return this.o.currentTime}mb(){return this.yd}Pf(a){return(a=this.La.get(a.toLowerCase()))?a[0].ka():this.mb()}kh(a,b){a=a.toLowerCase();let d=this.La.get(a);
d||(d=[],this.La.set(a,d));b.il(d.length);b.sl(a);d.push(b);this.sg(a)}sg(a){let b=this.mb();const d=this.La.get(a);if(d&&d.length){b=d[0].ka();for(let h=0,w=d.length;h<w;++h){const m=d[h];h+1===w?m.pa(this.mb()):m.pa(d[h+1].ka())}}for(const h of this.bb(a))h.Di(b);this.Ab&&this.nf===a&&(this.Ab.disconnect(),this.Ab.connect(b))}Zc(){return this.mf}dd(){return this.hb}gl(){this.Fg=!0}Kh(a,b){return b?this.N.Bl(a).then(d=>{const h=this.o.createBuffer(1,d.length,48E3);h.getChannelData(0).set(d);return h}):
new Promise((d,h)=>{this.o.decodeAudioData(a,d,h)})}ob(a){this.N.ob(a)}Gb(a){this.N.Gb(a)}Vf(a){let b=0;for(let d=0,h=this.W.length;d<h;++d){const w=this.W[d];this.W[b]=w;w.ga===a?w.l():++b}this.W.length=b}Ei(){let a=0;for(let b=0,d=this.Ka.length;b<d;++b){const h=this.Ka[b];this.Ka[a]=h;h.nb()?h.l():++a}this.Ka.length=a}*bb(a){if(a)for(const b of this.W)self.Ra.Lh(b.aa,a)&&(yield b);else this.Va&&!this.Va.qa()&&(yield this.Va)}async ld(a,b,d,h,w){for(const m of this.Ka)if(m.$b()===b)return await Y(m),
m;if(w)return null;h&&(this.tf||this.Fg)&&this.Ei();w="audio/webm; codecs=opus"===d&&!this.Yg;h&&w&&this.gl();a=!h||this.tf||w?new self.Fh(this,a,b,d,h,w):new self.Ah(this,a,b,d,h);this.Ka.push(a);await Y(a);return a}async Be(a,b,d,h,w){for(const m of this.W)if(m.$b()===b&&(m.be()||w))return m.Oi(h),m;a=await this.ld(a,b,d,w);h="html5"===a.Re?new self.Bh(a.A,a,h):new self.Gh(a.A,a,h);this.W.push(h);return h}fj(a){let b=this.Kc.get(a);if(!b){let d=null;b={Df:0,Sl:new Promise(h=>d=h),resolve:d};this.Kc.set(a,
b)}b.Df++}Wk(a){const b=this.Kc.get(a);if(!b)throw Error("expected pending tag");b.Df--;0===b.Df&&(b.resolve(),this.Kc.delete(a))}ve(a){a||(a=this.Kg);return(a=this.Kc.get(a))?a.Sl:Promise.resolve()}md(){if(0<this.Jb.size)N(this);else for(const a of this.W)if(a.Rf()){N(this);break}}la(){for(var a of this.Jb)a.la();a=this.de();for(var b of this.W)b.la(a);b=this.W.filter(d=>d.Rf()).map(d=>d.Zb());B(this,"state",{tickCount:this.Ng,audioInstances:b,analysers:[...this.Jb].map(d=>d.Th())});0===b.length&&
0===this.Jb.size&&this.Dd&&(this.N.Xk(this.Zg),this.Dd=!1)}me(a,b,d){B(this,"trigger",{type:a,tag:b,aiid:d})}async Rk(a){const b=a.originalUrl,d=a.url,h=a.type,w=a.isMusic,m=a.tag,f=a.isLooping,n=a.vol,c=a.pos,e=a.panning;let p=a.off;0<p&&!a.trueClock&&(this.o.getOutputTimestamp?(a=this.o.getOutputTimestamp(),p=p-a.performanceTime/1E3+a.contextTime):p=p-performance.now()/1E3+this.o.currentTime);this.Kg=m;this.fj(m);try{this.Va=await this.Be(b,d,h,m,w),e?(this.Va.gd(!0),this.Va.Mi(e.x,e.y,e.angle,
e.innerAngle,e.outerAngle,e.outerGain),e.hasOwnProperty("uid")&&this.Va.Pi(e.uid)):this.Va.gd(!1),this.Va.Play(f,n,c,p)}catch(t){console.error("[Construct 3] Audio: error starting playback: ",t);return}finally{this.Wk(m)}N(this)}vl(a){a=a.tag;for(const b of this.bb(a))b.gb()}wl(){for(const a of this.W)a.gb()}ol(a){const b=a.tag;a=a.paused;for(const d of this.bb(b))a?d.dc():d.fd();this.md()}tl(a){const b=a.tag;a=a.vol;for(const d of this.bb(b))d.jd(a)}async tj(a){const b=a.tag,d=a.vol,h=a.duration;
a=a.stopOnEnd;await this.ve(b);for(const w of this.bb(b))w.Mh(d,h,a);this.md()}ml(a){this.mf=a.vol;for(const b of this.W)b.rd()}nl(a){const b=a.tag;a=a.isMuted;for(const d of this.bb(b))d.Yf(a)}ql(a){this.hb=a.isSilent;this.N.hd(this.hb);for(const b of this.W)b.qd()}ll(a){const b=a.tag;a=a.isLooping;for(const d of this.bb(b))d.se(a)}async pl(a){const b=a.tag;a=a.rate;await this.ve(b);for(const d of this.bb(b))d.$f(a)}async Zk(a){const b=a.tag;a=a.pos;await this.ve(b);for(const d of this.bb(b))d.qe(a)}async Sk(a){const b=
a.originalUrl,d=a.url,h=a.type;a=a.isMusic;try{await this.Be(b,d,h,"",a)}catch(w){console.error("[Construct 3] Audio: error preloading: ",w)}}async zl(a){if(a=await this.ld("",a.url,a.type,a.isMusic,!0))a.l(),a=this.Ka.indexOf(a),-1!==a&&this.Ka.splice(a,1)}Al(){for(const a of this.Ka)a.l();this.Ka.length=0}rl(a){a=a.isSuspended;!a&&this.o.resume&&this.o.resume();for(const b of this.W)b.te(a);a&&this.o.suspend&&this.o.suspend()}Mk(a){this.Td=a.timeScale;this.Ze=a.gameTime;this.Ng=a.tickCount;if(0!==
this.zf)for(var b of this.W)b.Ib();(b=a.listenerPos)&&this.o.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const h of this.W)h.Ua===a&&h.Zf(d.x,d.y,d.angle)}}async cg(a){var b=a.type;const d=a.tag;var h=a.params;if("filter"===b)h=new self.uh(this,...h);else if("delay"===b)h=new self.sh(this,...h);else if("convolution"===b){b=null;try{b=await this.ld(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(w){console.log("[Construct 3] Audio: error loading convolution: ",
w);return}h=new self.rh(this,b.Ja,...h);h.dl(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)h=new self.vh(this,...h);else if("phaser"===b)h=new self.xh(this,...h);else if("gain"===b)h=new self.wh(this,...h);else if("tremolo"===b)h=new self.zh(this,...h);else if("ringmod"===b)h=new self.yh(this,...h);else if("distortion"===b)h=new self.th(this,...h);else if("compressor"===b)h=new self.qh(this,...h);else if("analyser"===b)h=new self.ph(this,...h);else throw Error("invalid effect type");this.kh(d,
h);this.rg()}fl(a){const b=a.index,d=a.param,h=a.value,w=a.ramp,m=a.time;a=this.La.get(a.tag);!a||0>b||b>=a.length||(a[b].ya(d,h,w,m),this.rg())}Uk(a){a=a.tag.toLowerCase();const b=this.La.get(a);if(b&&b.length){for(const d of b)d.l();this.La.delete(a);this.sg(a)}}bj(a){this.Jb.add(a);this.md()}Tk(a){this.Jb.delete(a)}rg(){this.ff||(this.ff=!0,Promise.resolve().then(()=>this.rj()))}rj(){const a={};for(const [b,d]of this.La)a[b]=d.map(h=>h.Zb());B(this,"fxstate",{fxstate:a});this.ff=!1}async Le(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.W)d.nb()&&1===b||(d.nb()||2!==b)&&d.gb();for(const h of this.La.values())for(const w of h)w.l();this.La.clear();this.Td=a.timeScale;this.Ze=a.gameTime;d=a.listenerPos;this.o.listener.setPosition(d[0],d[1],d[2]);this.hb=a.isSilent;this.N.hd(this.hb);this.mf=a.masterVolume;d=[];for(const h of Object.values(a.effects))d.push(Promise.all(h.map(w=>this.cg(w))));await Promise.all(d);await Promise.all(a.playing.map(h=>this.Fj(h,b)));this.md()}async Fj(a,b){if(3!==
b){var d=a.bufferOriginalUrl,h=a.bufferUrl,w=a.bufferType,m=a.isMusic,f=a.tag,n=a.isLooping,c=a.volume,e=a.playbackTime;if(!m||1!==b)if(m||2!==b){b=null;try{b=await this.Be(d,h,w,f,m)}catch(p){console.error("[Construct 3] Audio: error loading audio state: ",p);return}b.oi(a.pan);b.Play(n,c,e,0);a.isPlaying||b.dc();b.He(a)}}}gk(a,b){this.Ab&&this.Ab.disconnect();this.nf=b.toLowerCase();this.Ab=this.o.createMediaStreamSource(a);this.Ab.connect(this.Pf(this.nf))}Yj(){this.xd||(this.xd=this.o.createMediaStreamDestination(),
this.yd.connect(this.xd));return this.xd.stream}static Lh(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static aj(a){return a*k}static Jh(a){return Math.pow(10,a/20)}static Nf(a){return Math.max(Math.min(self.Ra.Jh(a),1),0)}static ni(a){return Math.log(a)/Math.log(10)*20}static mi(a){return self.Ra.ni(Math.max(Math.min(a,1),0))}static Nl(a,b){return 1-Math.exp(-b*a)}};self.Ea.Qa(self.Ra)}"use strict";function Y(k){k.Id||(k.Id=k.Ge());return k.Id}
self.Hf=class{constructor(k,a,b,d,h){this.A=k;this.Il=a;this.Cb=b;this.oa=d;this.El=h;this.Re="";this.Id=null}l(){this.Id=this.A=null}Ge(){}va(){return this.A.va()}fe(){return this.Il}$b(){return this.Cb}ee(){return this.oa}nb(){return this.El}Sa(){}};"use strict";
self.Ah=class extends self.Hf{constructor(k,a,b,d,h){super(k,a,b,d,h);this.Re="html5";this.ca=new Audio;this.ca.crossOrigin="anonymous";this.ca.autoplay=!1;this.ca.preload="auto";this.Ac=this.Bc=null;this.ca.addEventListener("canplaythrough",()=>!0);this.Ic=this.va().createGain();this.Dc=null;this.ca.addEventListener("canplay",()=>{this.Bc&&(this.Bc(),this.Ac=this.Bc=null);!this.Dc&&this.ca&&(this.Dc=this.va().createMediaElementSource(this.ca),this.Dc.connect(this.Ic))});this.onended=null;this.ca.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.ca.addEventListener("error",w=>{console.error(`[Construct 3] Audio '${this.Cb}' error: `,w);this.Ac&&(this.Ac(w),this.Ac=this.Bc=null)})}l(){this.A.Vf(this);this.Ic.disconnect();this.Ic=null;this.Dc.disconnect();this.Dc=null;this.ca&&!this.ca.paused&&this.ca.pause();this.ca=this.onended=null;super.l()}Ge(){return new Promise((k,a)=>{this.Bc=k;this.Ac=a;this.ca.src=this.Cb})}ja(){return this.ca}Sa(){return this.ca.duration}};"use strict";
async function ba(k){if(k.tb)return k.tb;var a=k.A.N;if("cordova"===a.M&&a.Tf(k.Cb)&&a.uc)k.tb=await a.Wc(k.Cb);else{a=await fetch(k.Cb);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);k.tb=await a.arrayBuffer()}}async function ca(k){if(k.Ja)return k.Ja;k.Ja=await k.A.Kh(k.tb,k.Gl);k.tb=null}
self.Fh=class extends self.Hf{constructor(k,a,b,d,h,w){super(k,a,b,d,h);this.Re="webaudio";this.Ja=this.tb=null;this.Gl=!!w}l(){this.A.Vf(this);this.Ja=this.tb=null;super.l()}async Ge(){try{await ba(this),await ca(this)}catch(k){console.error(`[Construct 3] Failed to load audio '${this.Cb}': `,k)}}Sa(){return this.Ja?this.Ja.duration:0}};"use strict";
{let k=0;self.If=class{constructor(a,b,d){this.A=a;this.ga=b;this.aa=d;this.sd=k++;this.ha=this.va().createGain();this.ha.connect(this.mb());this.O=null;this.wc=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.Z=!0;this.sa=this.$a=this.Y=!1;this.Rc=1;this.Mb=!1;this.jb=1;a=this.A.zf;this.gf=1===a&&!this.nb()||2===a;this.oc=this.Ua=-1;this.Xg=!1}l(){this.ga=this.A=null;this.O&&(this.O.disconnect(),this.O=null);this.ha.disconnect();this.ha=null}va(){return this.A.va()}mb(){return this.A.Pf(this.aa)}Zc(){return this.A.Zc()}Yc(){return this.gf?
this.A.Ze:performance.now()/1E3}fe(){return this.ga.fe()}$b(){return this.ga.$b()}ee(){return this.ga.ee()}nb(){return this.ga.nb()}Oi(a){this.aa=a}qa(){}be(){}IsPlaying(){return!this.Z&&!this.Y&&!this.qa()}Rf(){return!this.Z&&!this.qa()}Eb(){}Sa(){return this.ga.Sa()}Play(){}gb(){}dc(){}fd(){}jd(a){this.Rc=a;this.ha.gain.cancelScheduledValues(0);this.oc=-1;this.ha.gain.value=this.ge()}Mh(a,b,d){if(!this.Mb){a*=this.Zc();var h=this.ha.gain;h.cancelScheduledValues(0);var w=this.A.de();b=w+b;h.setValueAtTime(h.value,
w);h.linearRampToValueAtTime(a,b);this.Rc=a;this.oc=b;this.Xg=d}}rd(){this.jd(this.Rc)}la(a){-1!==this.oc&&a>=this.oc&&(this.oc=-1,this.Xg&&this.gb(),this.A.me("fade-ended",this.aa,this.sd))}ge(){const a=this.Rc*this.Zc();return isFinite(a)?a:0}Yf(a){a=!!a;this.Mb!==a&&(this.Mb=a,this.qd())}dd(){return this.A.dd()}qd(){}se(){}$f(a){this.jb!==a&&(this.jb=a,this.Ib())}Ib(){}qe(){}te(){}gd(a){a=!!a;this.wc!==a&&((this.wc=a)?(this.O||(this.O=this.va().createPanner(),this.O.panningModel=this.A.Rg,this.O.distanceModel=
this.A.Dg,this.O.refDistance=this.A.Tg,this.O.maxDistance=this.A.Qg,this.O.rolloffFactor=this.A.Vg),this.ha.disconnect(),this.ha.connect(this.O),this.O.connect(this.mb())):(this.O.disconnect(),this.ha.disconnect(),this.ha.connect(this.mb())))}Mi(a,b,d,h,w,m){this.wc&&(this.Zf(a,b,d),a=self.Ra.aj,this.O.coneInnerAngle=a(h),this.O.coneOuterAngle=a(w),this.O.coneOuterGain=m)}Zf(a,b,d){this.wc&&(this.Ya[0]=a,this.Ya[1]=b,this.Ya[2]=0,this.Xa[0]=Math.cos(d),this.Xa[1]=Math.sin(d),this.Xa[2]=0,this.O.setPosition(...this.Ya),
this.O.setOrientation(...this.Xa))}Pi(a){this.Ua=a}he(){}Di(a){const b=this.O||this.ha;b.disconnect();b.connect(a)}Zb(){return{aiid:this.sd,tag:this.aa,duration:this.Sa(),volume:this.Rc,isPlaying:this.IsPlaying(),playbackTime:this.Eb(),playbackRate:this.jb,uid:this.Ua,bufferOriginalUrl:this.fe(),bufferUrl:"",bufferType:this.ee(),isMusic:this.nb(),isLooping:this.sa,isMuted:this.Mb,resumePosition:this.he(),pan:this.ai()}}He(a){this.$f(a.playbackRate);this.Yf(a.isMuted)}ai(){if(!this.O)return null;const a=
this.O;return{pos:this.Ya,orient:this.Xa,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.Ua}}oi(a){if(a){this.gd(!0);a=this.O;var b=a.pos;this.Ya[0]=b[0];this.Ya[1]=b[1];this.Ya[2]=b[2];b=a.orient;this.Xa[0]=b[0];this.Xa[1]=b[1];this.Xa[2]=b[2];a.setPosition(...this.Ya);a.setOrientation(...this.Xa);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.Ua=a.uid}else this.gd(!1)}}}"use strict";
self.Bh=class extends self.If{constructor(k,a,b){super(k,a,b);this.ga.Ic.connect(this.ha);this.ga.onended=()=>this.Je()}l(){this.gb();this.ga.Ic.disconnect();super.l()}ja(){return this.ga.ja()}Je(){this.Z=!0;this.Ua=-1;this.A.me("ended",this.aa,this.sd)}qa(){return this.ja().ended}be(){return this.Z?!0:this.qa()}Eb(){let k=this.ja().currentTime;this.sa||(k=Math.min(k,this.Sa()));return k}Play(k,a,b){const d=this.ja();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==k&&(d.loop=k);this.jd(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(h){console.warn(`[Construct 3] Exception seeking audio '${this.ga.$b()}' to position '${b}': `,h)}this.A.ob(d);this.Y=this.Z=!1;this.sa=k;this.jb=1}gb(){const k=this.ja();k.paused||k.pause();this.A.Gb(k);this.Z=!0;this.Y=!1;this.Ua=-1}dc(){if(!(this.Y||this.Z||this.qa())){var k=this.ja();k.paused||k.pause();this.A.Gb(k);this.Y=!0}}fd(){!this.Y||this.Z||this.qa()||(this.A.ob(this.ja()),this.Y=!1)}qd(){this.ja().muted=this.Mb||this.dd()}se(k){k=
!!k;this.sa!==k&&(this.sa=k,this.ja().loop=k)}Ib(){let k=this.jb;this.gf&&(k*=this.A.Td);try{this.ja().playbackRate=k}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${k}':`,a)}}qe(k){if(!this.Z&&!this.qa())try{this.ja().currentTime=k}catch(a){console.warn(`[Construct 3] Error seeking audio to '${k}': `,a)}}he(){return this.Eb()}te(k){k?this.IsPlaying()?(this.ja().pause(),this.$a=!0):this.$a=!1:this.$a&&(this.A.ob(this.ja()),this.$a=!1)}};"use strict";
function Z(k){k.B&&k.B.disconnect();k.B=null;k.jc=null}
self.Gh=class extends self.If{constructor(k,a,b){super(k,a,b);this.B=null;this.Ld=d=>this.Je(d);this.af=!0;this.jc=null;this.ia=this.Md=this.Nd=0;this.pf=1}l(){this.gb();Z(this);this.Ld=null;super.l()}Je(k){this.Y||this.$a||k.target!==this.jc||(this.Z=this.af=!0,this.Ua=-1,Z(this),this.A.me("ended",this.aa,this.sd))}qa(){return!this.Z&&this.B&&this.B.loop||this.Y?!1:this.af}be(){return!this.B||this.Z?!0:this.qa()}Eb(){let k;k=this.Y?this.ia:this.Md+(this.Yc()-this.Nd)*this.jb;this.sa||(k=Math.min(k,
this.Sa()));return k}Play(k,a,b,d){this.pf=1;this.jd(a);Z(this);this.B=this.va().createBufferSource();this.B.buffer=this.ga.Ja;this.B.connect(this.ha);this.jc=this.B;this.B.onended=this.Ld;this.B.loop=k;this.B.start(d,b);this.Y=this.Z=this.af=!1;this.sa=k;this.jb=1;this.Nd=this.Yc();this.Md=b}gb(){if(this.B)try{this.B.stop(0)}catch(k){}this.Z=!0;this.Y=!1;this.Ua=-1}dc(){this.Y||this.Z||this.qa()||(this.ia=this.Eb(),this.sa&&(this.ia%=this.Sa()),this.Y=!0,this.B.stop(0))}fd(){!this.Y||this.Z||this.qa()||
(Z(this),this.B=this.va().createBufferSource(),this.B.buffer=this.ga.Ja,this.B.connect(this.ha),this.jc=this.B,this.B.onended=this.Ld,this.B.loop=this.sa,this.rd(),this.Ib(),this.B.start(0,this.ia),this.Nd=this.Yc(),this.Md=this.ia,this.Y=!1)}ge(){return super.ge()*this.pf}qd(){this.pf=this.Mb||this.dd()?0:1;this.rd()}se(k){k=!!k;this.sa!==k&&(this.sa=k,this.B&&(this.B.loop=k))}Ib(){let k=this.jb;this.gf&&(k*=this.A.Td);this.B&&(this.B.playbackRate.value=k)}qe(k){this.Z||this.qa()||(this.Y?this.ia=
k:(this.dc(),this.ia=k,this.fd()))}he(){return this.ia}te(k){k?this.IsPlaying()?(this.$a=!0,this.ia=this.Eb(),this.sa&&(this.ia%=this.Sa()),this.B.stop(0)):this.$a=!1:this.$a&&(Z(this),this.B=this.va().createBufferSource(),this.B.buffer=this.ga.Ja,this.B.connect(this.ha),this.jc=this.B,this.B.onended=this.Ld,this.B.loop=this.sa,this.rd(),this.Ib(),this.B.start(0,this.ia),this.Nd=this.Yc(),this.Md=this.ia,this.$a=!1)}He(k){super.He(k);this.ia=k.resumePosition}};"use strict";
{class k{constructor(a){this.A=a;this.o=a.va();this.sc=-1;this.oa=this.aa="";this.s=null}l(){this.o=null}il(a){this.sc=a}sl(a){this.aa=a}G(){return this.o.createGain()}ka(){}pa(){}F(a,b,d,h){a.cancelScheduledValues(0);if(0===h)a.value=b;else{var w=this.o.currentTime;h+=w;switch(d){case 0:a.setValueAtTime(b,h);break;case 1:a.setValueAtTime(a.value,w);a.linearRampToValueAtTime(b,h);break;case 2:a.setValueAtTime(a.value,w),a.exponentialRampToValueAtTime(b,h)}}}Zb(){return{type:this.oa,tag:this.aa,params:this.s}}}
self.uh=class extends k{constructor(a,b,d,h,w,m,f){super(a);this.oa="filter";this.s=[b,d,h,w,m,f];this.D=this.G();this.h=this.G();this.h.gain.value=f;this.g=this.G();this.g.gain.value=1-f;this.K=this.o.createBiquadFilter();this.K.type=b;this.K.frequency.value=d;this.K.detune.value=h;this.K.Q.value=w;this.K.gain.vlaue=m;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h)}l(){this.D.disconnect();this.K.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b,d,h);this.F(this.g.gain,1-b,d,h);break;case 1:this.s[1]=b;this.F(this.K.frequency,b,d,h);break;case 2:this.s[2]=b;this.F(this.K.detune,b,d,h);break;case 3:this.s[3]=b;this.F(this.K.Q,b,d,h);break;case 4:this.s[4]=b,this.F(this.K.gain,b,d,h)}}};self.sh=class extends k{constructor(a,b,d,h){super(a);this.oa="delay";this.s=[b,d,h];this.D=
this.G();this.h=this.G();this.h.gain.value=h;this.g=this.G();this.g.gain.value=1-h;this.Cc=this.G();this.ra=this.o.createDelay(b);this.ra.delayTime.value=b;this.nc=this.G();this.nc.gain.value=d;this.D.connect(this.Cc);this.D.connect(this.g);this.Cc.connect(this.h);this.Cc.connect(this.ra);this.ra.connect(this.nc);this.nc.connect(this.Cc)}l(){this.D.disconnect();this.h.disconnect();this.g.disconnect();this.Cc.disconnect();this.ra.disconnect();this.nc.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,d,h){const w=self.Ra.Nf;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[2]=b;this.F(this.h.gain,b,d,h);this.F(this.g.gain,1-b,d,h);break;case 4:this.s[1]=w(b);this.F(this.nc.gain,w(b),d,h);break;case 5:this.s[0]=b,this.F(this.ra.delayTime,b,d,h)}}};self.rh=class extends k{constructor(a,b,d,h){super(a);this.oa="convolution";this.s=[d,h];this.zg=this.yg="";this.D=this.G();this.h=this.G();this.h.gain.value=h;this.g=
this.G();this.g.gain.value=1-h;this.lc=this.o.createConvolver();this.lc.normalize=d;this.lc.buffer=b;this.D.connect(this.lc);this.D.connect(this.g);this.lc.connect(this.h)}l(){this.D.disconnect();this.lc.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[1]=b,this.F(this.h.gain,b,d,h),this.F(this.g.gain,1-b,d,h)}}dl(a,
b){this.yg=a;this.zg=b}Zb(){const a=super.Zb();a.bufferOriginalUrl=this.yg;a.bufferUrl="";a.bufferType=this.zg;return a}};self.vh=class extends k{constructor(a,b,d,h,w,m){super(a);this.oa="flanger";this.s=[b,d,h,w,m];this.D=this.G();this.g=this.G();this.g.gain.value=1-m/2;this.h=this.G();this.h.gain.value=m/2;this.pc=this.G();this.pc.gain.value=w;this.ra=this.o.createDelay(b+d);this.ra.delayTime.value=b;this.I=this.o.createOscillator();this.I.frequency.value=h;this.$=this.G();this.$.gain.value=d;
this.D.connect(this.ra);this.D.connect(this.g);this.ra.connect(this.h);this.ra.connect(this.pc);this.pc.connect(this.ra);this.I.connect(this.$);this.$.connect(this.ra.delayTime);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.ra.disconnect();this.I.disconnect();this.$.disconnect();this.g.disconnect();this.h.disconnect();this.pc.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0);this.s[4]=b;this.F(this.h.gain,b/2,d,h);this.F(this.g.gain,1-b/2,d,h);break;case 6:this.s[1]=b/1E3;this.F(this.$.gain,b/1E3,d,h);break;case 7:this.s[2]=b;this.F(this.I.frequency,b,d,h);break;case 8:this.s[3]=b/100,this.F(this.pc.gain,b/100,d,h)}}};self.xh=class extends k{constructor(a,b,d,h,w,m,f){super(a);this.oa="phaser";this.s=[b,d,h,w,m,f];this.D=this.G();this.g=this.G();this.g.gain.value=1-f/2;this.h=this.G();this.h.gain.value=f/2;this.K=this.o.createBiquadFilter();this.K.type="allpass";
this.K.frequency.value=b;this.K.detune.value=d;this.K.Q.value=h;this.I=this.o.createOscillator();this.I.frequency.value=m;this.$=this.G();this.$.gain.value=w;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h);this.I.connect(this.$);this.$.connect(this.K.frequency);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.K.disconnect();this.I.disconnect();this.$.disconnect();this.g.disconnect();this.h.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();
this.g.connect(a)}ka(){return this.D}ya(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b/2,d,h);this.F(this.g.gain,1-b/2,d,h);break;case 1:this.s[0]=b;this.F(this.K.frequency,b,d,h);break;case 2:this.s[1]=b;this.F(this.K.detune,b,d,h);break;case 3:this.s[2]=b;this.F(this.K.Q,b,d,h);break;case 6:this.s[3]=b;this.F(this.$.gain,b,d,h);break;case 7:this.s[4]=b,this.F(this.I.frequency,b,d,h)}}};self.wh=class extends k{constructor(a,b){super(a);this.oa="gain";this.s=
[b];this.v=this.G();this.v.gain.value=b}l(){this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}ya(a,b,d,h){const w=self.Ra.Nf;switch(a){case 4:this.s[0]=w(b),this.F(this.v.gain,w(b),d,h)}}};self.zh=class extends k{constructor(a,b,d){super(a);this.oa="tremolo";this.s=[b,d];this.v=this.G();this.v.gain.value=1-d/2;this.I=this.o.createOscillator();this.I.frequency.value=b;this.$=this.G();this.$.gain.value=d/2;this.I.connect(this.$);this.$.connect(this.v.gain);
this.I.start(0)}l(){this.I.stop(0);this.I.disconnect();this.$.disconnect();this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}ya(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.v.gain,1-b/2,d,h);this.F(this.$.gain,b/2,d,h);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,d,h)}}};self.yh=class extends k{constructor(a,b,d){super(a);this.oa="ringmod";this.s=[b,d];this.D=this.G();this.h=this.G();this.h.gain.value=d;this.g=this.G();
this.g.gain.value=1-d;this.Oc=this.G();this.Oc.gain.value=0;this.I=this.o.createOscillator();this.I.frequency.value=b;this.I.connect(this.Oc.gain);this.I.start(0);this.D.connect(this.Oc);this.D.connect(this.g);this.Oc.connect(this.h)}l(){this.I.stop(0);this.I.disconnect();this.Oc.disconnect();this.D.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0);this.s[1]=b;this.F(this.h.gain,b,d,h);this.F(this.g.gain,1-b,d,h);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,d,h)}}};self.th=class extends k{constructor(a,b,d,h,w,m){super(a);this.oa="distortion";this.s=[b,d,h,w,m];this.D=this.G();this.Pd=this.G();this.Od=this.G();this.el(h,w);this.h=this.G();this.h.gain.value=m;this.g=this.G();this.g.gain.value=1-m;this.Xd=this.o.createWaveShaper();this.Ue=new Float32Array(65536);this.vj(b,d);this.Xd.curve=this.Ue;this.D.connect(this.Pd);this.D.connect(this.g);
this.Pd.connect(this.Xd);this.Xd.connect(this.Od);this.Od.connect(this.h)}l(){this.D.disconnect();this.Pd.disconnect();this.Xd.disconnect();this.Od.disconnect();this.h.disconnect();this.g.disconnect();super.l()}el(a,b){.01>a&&(a=.01);this.Pd.gain.value=a;this.Od.gain.value=Math.pow(1/a,.6)*b}vj(a,b){for(let d=0;32768>d;++d){let h=d/32768;h=this.ul(h,a,b);this.Ue[32768+d]=h;this.Ue[32768-d-1]=-h}}ul(a,b,d){d=1.05*d*b-b;const h=0>a?-a:a;return(h<b?h:b+d*self.Ra.Nl(h-b,1/d))*(0>a?-1:1)}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[4]=b,this.F(this.h.gain,b,d,h),this.F(this.g.gain,1-b,d,h)}}};self.qh=class extends k{constructor(a,b,d,h,w,m){super(a);this.oa="compressor";this.s=[b,d,h,w,m];this.v=this.o.createDynamicsCompressor();this.v.threshold.value=b;this.v.knee.value=d;this.v.ratio.value=h;this.v.attack.value=w;this.v.release.value=m}l(){this.v.disconnect();super.l()}pa(a){this.v.disconnect();
this.v.connect(a)}ka(){return this.v}ya(){}};self.ph=class extends k{constructor(a,b,d){super(a);this.oa="analyser";this.s=[b,d];this.v=this.o.createAnalyser();this.v.fftSize=b;this.v.smoothingTimeConstant=d;this.Eg=new Float32Array(this.v.frequencyBinCount);this.Wg=new Uint8Array(b);this.Ug=this.Qb=0;this.A.bj(this)}l(){this.A.Tk(this);this.v.disconnect();super.l()}la(){this.v.getFloatFrequencyData(this.Eg);this.v.getByteTimeDomainData(this.Wg);const a=this.v.fftSize;let b=this.Qb=0;for(var d=0;d<
a;++d){let h=(this.Wg[d]-128)/128;0>h&&(h=-h);this.Qb<h&&(this.Qb=h);b+=h*h}d=self.Ra.mi;this.Qb=d(this.Qb);this.Ug=d(Math.sqrt(b/a))}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}ya(){}Th(){return{tag:this.aa,index:this.sc,peak:this.Qb,rms:this.Ug,binCount:this.v.frequencyBinCount,freqBins:this.Eg}}}}"use strict";
{function k(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.Ea.Qa(class extends self.Xc{constructor(b){super(b,"text-input");R(this,"scroll-to-bottom",d=>this.uk(d))}Yb(b,d){let h;const w=d.type;"textarea"===w?(h=document.createElement("textarea"),h.style.resize="none"):(h=document.createElement("input"),h.type=w);h.style.position="absolute";h.autocomplete="off";h.addEventListener("touchstart",k);h.addEventListener("touchmove",k);h.addEventListener("touchend",
k);h.addEventListener("mousedown",k);h.addEventListener("mouseup",k);h.addEventListener("keydown",a);h.addEventListener("keyup",a);h.addEventListener("click",m=>{m.stopPropagation();S(this,"click",b)});h.addEventListener("dblclick",m=>{m.stopPropagation();S(this,"dblclick",b)});h.addEventListener("input",()=>Q(this,"change",b,{text:h.value}));d.id&&(h.id=d.id);this.Ta(h,d);return h}Ta(b,d){b.value=d.text;b.placeholder=d.placeholder;b.title=d.title;b.disabled=!d.isEnabled;b.readOnly=d.isReadOnly;b.spellcheck=
d.spellCheck;d=d.maxLength;0>d?b.removeAttribute("maxlength"):b.setAttribute("maxlength",d)}uk(b){b.scrollTop=b.scrollHeight}})}"use strict";
{function k(a){a.stopPropagation()}self.Ea.Qa(class extends self.Xc{constructor(a){super(a,"button")}Yb(a,b){const d=document.createElement("input");var h=d;b.isCheckbox?(d.type="checkbox",h=document.createElement("label"),h.appendChild(d),h.appendChild(document.createTextNode("")),h.style.fontFamily="sans-serif",h.style.userSelect="none",h.style.webkitUserSelect="none",h.style.display="inline-block",h.style.color="black"):d.type="button";h.style.position="absolute";h.addEventListener("touchstart",
k);h.addEventListener("touchmove",k);h.addEventListener("touchend",k);h.addEventListener("mousedown",k);h.addEventListener("mouseup",k);h.addEventListener("keydown",k);h.addEventListener("keyup",k);d.addEventListener("click",()=>S(this,"click",a,{isChecked:d.checked}));b.id&&(d.id=b.id);this.Ta(h,b);return h}ig(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Ce(a){return this.ig(a)}Ta(a,b){const d=this.ig(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;a===d?d.value=b.text:
a.lastChild.textContent=b.text}})};
