'use strict';function z(g,a,b,d){g.A.oc(g.Za,a,b,d,void 0)}function E(g,a,b,d){g.A.ca?z(g,a,b,d):g.A.hf()._OnMessageFromDOM({type:"event",component:g.Za,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(g,a,b){g.A.C(g.Za,a,b)}function L(g,a){for(const [b,d]of a)J(g,b,d)}function M(g){g.Rb||(g.A.Te(g.ce),g.Rb=!0)}window.wb=class{constructor(g,a){this.A=g;this.Za=a;this.Rb=!1;this.ce=()=>this.Ca()}ed(){}Ca(){}};function N(g){-1!==g.Oa&&(self.clearTimeout(g.Oa),g.Oa=-1)}
window.Ke=class{constructor(g,a){this.Lc=g;this.xg=a;this.Oa=-1;this.Sb=-Infinity;this.de=()=>{this.Oa=-1;this.Sb=Date.now();this.eb=!0;this.Lc();this.eb=!1};this.Md=this.eb=!1}c(){N(this);this.de=this.Lc=null}};"use strict";function O(g,a){const b=a.elementId,d=g.jd(b,a);g.Y.set(b,d);a.isVisible||(d.style.display="none");a=g.yc(d);a.addEventListener("focus",()=>{P(g,"elem-focused",b)});a.addEventListener("blur",()=>{P(g,"elem-blurred",b)});g.Mb&&document.body.appendChild(d)}
function Q(g,a){J(g,"get-element",b=>{const d=g.Y.get(b.elementId);return a(d,b)})}function P(g,a,b){var d;d||(d={});d.elementId=b;z(g,a,d)}
window.we=class extends self.wb{constructor(g,a){super(g,a);this.Y=new Map;this.Mb=!0;L(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Mb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Mb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Mb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.uc(d,b)}}],["focus",b=>{{const d=this.yc(this.Y.get(b.elementId));b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);Q(this,b=>b)}jd(){throw Error("required override");}uc(){throw Error("required override");}yc(g){return g}};
"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Ig?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=m.Mg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let d=!1,f=!1;function n(){if(!d){try{new Worker("blob://",{get type(){f=!0}})}catch(m){}d=!0}return f}const q=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus")&&!q,"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=
await w(m);return(new TextDecoder("utf-8")).decode(m)}function w(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const x=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Ua=class m{constructor(c){this.ca=
c.Og;this.oa=null;this.F="";this.bc=c.Lg;this.tb={};this.Ha=this.sb=null;this.Pb=[];this.hb=this.K=this.Ma=null;this.La=-1;this.Cg=()=>this.Hf();this.Ka=[];this.v=c.ee;this.fb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.ca=!1)}else this.ca=!1;this.Ub=this.ha=null;"html5"!==this.v&&"playable-ad"!==this.v||!this.fb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.rf(k));this.C("runtime","create-job-worker",()=>this.sf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.yd(c)):this.yd(c)}c(){this.vc();this.oa&&(this.oa=this.oa.onmessage=
null);this.sb&&(this.sb.terminate(),this.sb=null);this.Ha&&(this.Ha.c(),this.Ha=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Fe(){return g&&"cordova"===this.v}nc(){const c=navigator.userAgent;return g&&e.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async yd(c){"macos-wkwebview"===this.v&&this.$f();if("playable-ad"===this.v){this.ha=self.c3_base64files;this.Ub={};await this.Ye();for(let l=0,p=c.Pa.length;l<p;++l){var k=c.Pa[l].toLowerCase();this.Ub.hasOwnProperty(k)?
c.Pa[l]={Ig:!0,Mg:this.Ub[k]}:this.ha.hasOwnProperty(k)&&(c.Pa[l]=URL.createObjectURL(this.ha[k]))}}c.Dg?this.F=c.Dg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Qg&&(this.tb=c.Qg);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Df(l));this.hb=new self.Ge(this);await R(this.hb);"object"===typeof window.StatusBar&&
window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.kf(c,k.port2):await this.jf(c,k.port2)}zc(c){c=this.tb.hasOwnProperty(c)?this.tb[c]:c.endsWith("/workermain.js")&&this.tb.hasOwnProperty("workermain.js")?this.tb["workermain.js"]:"playable-ad"===this.v&&this.ha.hasOwnProperty(c.toLowerCase())?this.ha[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async hc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,
l);if("cordova"===this.v&&this.fb)return c=await this.vb(l.Hg?c:this.bc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}va(){return Math.max(window.innerWidth,1)}ua(){return Math.max(window.innerHeight,1)}wd(c){var k=this.hb;return{baseUrl:this.F,windowInnerWidth:this.va(),
windowInnerHeight:this.ua(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Sa(),projectData:c.Vg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Tg||"",exportType:c.ee,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ug,jobScheduler:{inputPort:k.Rc,outputPort:k.Yc,maxNumWorkers:k.zg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.bc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.bc+"opus.wasm.wasm",isFileProtocol:this.fb,isiOSCordova:this.Fe(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async kf(c,k){var l=this.zc(c.Pg);this.sb=await this.hc(l,this.F,{type:"module",name:"Runtime",Hg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let p=c.dd||[],
u=c.Pa;p=await Promise.all(p.map(r=>this.Da(r)));u=await Promise.all(u.map(r=>this.Da(r)));if("cordova"===this.v)for(let r=0,t=c.ec.length;r<t;++r){const y=c.ec[r],H=y[0];if(H===c.bd||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))y[1]=await this.Da(H)}this.sb.postMessage(Object.assign(this.wd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.ec,mainProjectScript:c.bd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...S(this.hb)]);this.Pb=F.map(r=>new r(this));this.vd();self.c3_callFunction=(r,t)=>this.Ma.lf(r,t);"preview"===this.v&&(self.goToLastErrorScript=()=>this.oc("runtime","go-to-last-error-script"))}async jf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Pb=F.map(r=>new r(this));this.vd();var l=c.Pa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.dd)&&l.unshift(...c.dd);l=await Promise.all(l.map(r=>
this.Da(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const p=c.bd,u=c.ec;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Da(t),await b(t),"preview"!==this.v||l[r]||this.Gd(r,"main script did not run to completion")}catch(y){this.Gd(r,y)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Da(t),await b(t);"preview"===this.v&&"object"!==typeof self.Rg.Sg?(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.wd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:K}),this.Ad(),this.Ha=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ha,c))}Gd(c,k){this.Ib();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ad(){this.Ib()}Ib(){const c=
window.Eg;c&&(c.parentElement.removeChild(c),window.Eg=null)}async sf(){const c=await T(this.hb);return{outputPort:c,transferables:[c]}}hf(){if(this.ca)throw Error("not available in worker mode");return this.Ha}oc(c,k,l,p,u){this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}od(c,k,l,p,u){const r=I++,t=new Promise((y,H)=>{G.set(r,{resolve:y,reject:H})});this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.xf(c);if("result"===k)this.Kf(c);else if("runtime-ready"===k)this.Lf();else if("alert-error"===k)this.Ib(),alert(c.message);else if("creating-runtime"===k)this.Ad();else throw Error(`unknown message '${k}'`);}xf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Hb(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Hb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Hb(u,!1,""+t)}):this.Hb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Hb(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.oa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Kf(c){const k=c.responseId,l=c.isOk;c=c.result;const p=G.get(k);l?p.resolve(c):p.reject(c);G.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static ub(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}vd(){for(const c of this.Pb)if("runtime"===c.Za){this.Ma=c;return}throw Error("cannot find runtime DOM handler");}Df(c){this.oc("debugger","message",c)}Lf(){for(const c of this.Pb)c.ed()}static Sa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Hd(c){h=!!c}Te(c){this.Ka.push(c);this.Jc()}Xf(c){c=this.Ka.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ka.splice(c,1);this.Ka.length||this.vc()}Jc(){-1===this.La&&this.Ka.length&&(this.La=requestAnimationFrame(this.Cg))}vc(){-1!==this.La&&(cancelAnimationFrame(this.La),this.La=-1)}Hf(){this.La=-1;for(const c of this.Ka)c();this.Jc()}ta(c){this.Ma.ta(c)}Ba(c){this.Ma.Ba(c)}Ic(){this.Ma.Ic()}Cb(c){this.Ma.Cb(c)}Ee(){return!!B["audio/webm; codecs=opus"]}async vg(c){c=await this.od("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}De(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}nd(c){return!this.De(c)}async Da(c){return"cordova"===this.v&&(c.startsWith("file:")||this.fb&&this.nd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.vb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async rf(c){const k=c.filename;switch(c.as){case "text":return await this.ve(k);case "buffer":return await this.vb(k);
default:throw Error("unsupported type");}}hd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async ve(c){c=await this.hd(c);return await D(c)}wc(){if(x.length&&!(8<=C)){C++;var c=x.shift();this.Ze(c.filename,c.Ng,c.Gg)}}vb(c){return new Promise((k,l)=>{x.push({filename:c,Ng:p=>{C--;this.wc();k(p)},Gg:p=>{C--;this.wc();l(p)}});this.wc()})}async Ze(c,k,l){try{const p=await this.hd(c),u=await w(p);
k(u)}catch(p){l(p)}}$f(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Ye(){const c=[];for(const [k,l]of Object.entries(this.ha))c.push(this.Xe(k,l));await Promise.all(c)}async Xe(c,k){if("object"===typeof k)this.ha[c]=new Blob([k.str],{type:k.type}),this.Ub[c]=k.str;else{let l=await this.ff(k);
l||(l=this.af(k));this.ha[c]=l}}async ff(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}af(c){c=this.Rf(c);return this.We(c.data,c.Jg)}Rf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||
"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Jg:c,data:l}}We(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,y;for(y=t=0;t<p;++t)r[t]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(l&=3;l--;)u[y]=c.charCodeAt(y),++y;return new Blob([u],{type:k})}}}"use strict";
{const g=self.Ua;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function w(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function x(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await w(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.ub(class extends self.wb{constructor(e){super(e,"runtime");this.Rd=!0;this.Na=-1;this.$c="any";this.Id=this.Jd=!1;this.Uc=
this.pb=this.xa=null;e.C("canvas","update-size",c=>this.Of(c));e.C("runtime","invoke-download",c=>this.Bf(c));e.C("runtime","raster-svg-image",c=>this.If(c));e.C("runtime","get-svg-image-size",c=>this.zf(c));e.C("runtime","set-target-orientation",c=>this.Mf(c));e.C("runtime","register-sw",()=>this.Jf());e.C("runtime","post-to-debugger",c=>this.Cd(c));e.C("runtime","go-to-script",c=>this.Cd(c));e.C("runtime","before-start-ticking",()=>this.qf());e.C("runtime","debug-highlight",c=>this.tf(c));e.C("runtime",
"enable-device-orientation",()=>this.Ve());e.C("runtime","enable-device-motion",()=>this.Ue());e.C("runtime","add-stylesheet",c=>this.nf(c));e.C("runtime","alert",c=>this.pf(c));e.C("runtime","hide-cordova-splash",()=>this.Af());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||x(k)||c.preventDefault()});const m=e.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",
A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.mb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.Pf());window.addEventListener("fullscreenchange",
()=>this.Va());window.addEventListener("webkitfullscreenchange",()=>this.Va());window.addEventListener("mozfullscreenchange",()=>this.Va());window.addEventListener("fullscreenerror",c=>this.Ec(c));window.addEventListener("webkitfullscreenerror",c=>this.Ec(c));window.addEventListener("mozfullscreenerror",c=>this.Ec(c));e.nc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):x(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Qf(c);this.Ia=new Set;this.Vb=new WeakSet;this.na=!1}qf(){"cordova"===this.A.v?(document.addEventListener("pause",()=>this.Hc(!0)),document.addEventListener("resume",()=>this.Hc(!1))):document.addEventListener("visibilitychange",()=>this.Hc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}ed(){window.addEventListener("focus",()=>
this.Xa("window-focus"));window.addEventListener("blur",()=>{this.Xa("window-blur",{parentHasFocus:K()});this.mb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||x(h))&&this.Xa("keyboard-blur")});window.addEventListener("keydown",h=>this.Bd("keydown",h));window.addEventListener("keyup",h=>this.Bd("keyup",h));window.addEventListener("dblclick",h=>this.Fc("dblclick",h,d));window.addEventListener("wheel",h=>this.Ff(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Ac(h);this.Wa("pointerdown",h)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.pb=new self.Ke(()=>this.df(),5),this.pb.Md=!0,window.addEventListener("pointerrawupdate",h=>this.Gf(h))):window.addEventListener("pointermove",h=>this.Wa("pointermove",h)),window.addEventListener("pointerup",h=>this.Wa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Wa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Ac(h);this.Gc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Gc("pointermove",h)),window.addEventListener("mouseup",h=>this.Gc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Ac(h);this.Gb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Gb("pointermove",h)),window.addEventListener("touchend",h=>this.Gb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Gb("pointercancel",h)));const e=()=>this.Ic();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Xa(e,h){z(this,e,h||null,n)}va(){return this.A.va()}ua(){return this.A.ua()}Pf(){const e=this.va(),h=this.ua();this.Xa("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Sa()});this.A.nc()&&(-1!==this.Na&&clearTimeout(this.Na),this.Dd(e,h,0))}Yf(e,h,m){-1!==this.Na&&clearTimeout(this.Na);this.Na=setTimeout(()=>this.Dd(e,
h,m),48)}Dd(e,h,m){const c=this.va(),k=this.ua();this.Na=-1;c!=e||k!=h?this.Xa("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Sa()}):10>m&&this.Yf(c,k,m+1)}Mf(e){this.$c=e.targetOrientation}rg(){const e=this.$c;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Va(){const e=g.Sa();e&&"any"!==this.$c&&this.rg();z(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.va(),innerHeight:this.ua()})}Ec(e){console.warn("[Construct 3] Fullscreen request failed: ",e);z(this,"fullscreenerror",
{isFullscreen:g.Sa(),innerWidth:this.va(),innerHeight:this.ua()})}Hc(e){e?this.A.vc():this.A.Jc();z(this,"visibilitychange",{hidden:e})}Bd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;E(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Ff(e){z(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Fc(e,h,m){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},m)}Gc(e,h){if(!a(h)){var m=this.mb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.mb=h.buttons;this.Fc(h.type,h,f)}}Wa(e,h){if(this.pb&&"pointermove"!==e){var m=this.pb;m.eb||(N(m),m.Sb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.mb);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Fc(m,h,f),this.mb=h.buttons)}Gf(e){this.Uc=e;e=this.pb;if(-1===e.Oa){var h=Date.now(),m=h-e.Sb,c=e.xg;m>=c&&e.Md?(e.Sb=h,e.eb=!0,e.Lc(),e.eb=!1):e.Oa=self.setTimeout(e.de,Math.max(c-m,4))}}df(){this.Wa("pointermove",this.Uc);this.Uc=null}Gb(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];E(this,e,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Ac(e){window!==window.top&&window.focus();this.zd(e.target)&&document.activeElement&&!this.zd(document.activeElement)&&document.activeElement.blur()}zd(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ve(){this.Jd||(this.Jd=!0,window.addEventListener("deviceorientation",e=>this.vf(e)),window.addEventListener("deviceorientationabsolute",e=>this.wf(e)))}Ue(){this.Id||(this.Id=!0,window.addEventListener("devicemotion",e=>this.uf(e)))}vf(e){z(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
d)}wf(e){z(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}uf(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});z(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},
d)}Of(e){const h=this.A.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Rd&&(h.style.display="",this.Rd=!1)}Bf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async If(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async zf(e){return await self.C3_GetSvgImageSize(e.blob)}async nf(e){await q(e.url)}Ic(){var e=[...this.Ia];this.Ia.clear();if(!this.na)for(const h of e)(e=h.play())&&e.catch(()=>{this.Vb.has(h)||this.Ia.add(h)})}ta(e){if("function"!==typeof e.play)throw Error("missing play function");this.Vb.delete(e);let h;try{h=e.play()}catch(m){this.Ia.add(e);return}h&&h.catch(()=>{this.Vb.has(e)||this.Ia.add(e)})}Ba(e){this.Ia.delete(e);
this.Vb.add(e)}Cb(e){this.na=!!e}Af(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}tf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),this.xa.id="inspectOutline",document.body.appendChild(this.xa));var h=this.xa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Jf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Cd(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}lf(e,h){return this.A.od(this.Za,"js-invoke-function",{name:e,params:h},void 0,void 0)}pf(e){alert(e.message)}Qf(e){"entered-fullscreen"===e?(g.Hd(!0),this.Va()):"exited-fullscreen"===e?(g.Hd(!1),this.Va()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function R(g){if(g.wg)throw Error("already initialised");g.wg=!0;var a=g.ac.zc("dispatchworker.js");g.Nc=await g.ac.hc(a,g.F,{name:"DispatchWorker"});a=new MessageChannel;g.Rc=a.port1;g.Nc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.Yc=await T(g)}function S(g){return[g.Rc,g.Yc]}
async function T(g){const a=g.Sd.length;var b=g.ac.zc("jobworker.js");b=await g.ac.hc(b,g.F,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;g.Nc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);g.Sd.push(b);return f.port1}
self.Ge=class{constructor(g){this.ac=g;this.F=g.F;this.F="preview"===g.v?this.F+"workers/":this.F+g.bc;this.zg=Math.min(navigator.hardwareConcurrency||2,16);this.Nc=null;this.Sd=[];this.Yc=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ua({Og:!0,Pg:"workermain.js",Pa:["scripts/c3runtime.js"],ec:[],bd:"",Lg:"scripts/",dd:[],ee:"html5"}));"use strict";
{function g(a){a.stopPropagation()}self.Ua.ub(class extends self.we{constructor(a){super(a,"button")}jd(a,b){const d=document.createElement("input");var f=d;b.isCheckbox?(d.type="checkbox",f=document.createElement("label"),f.appendChild(d),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):d.type="button";f.style.position="absolute";f.addEventListener("touchstart",
g);f.addEventListener("touchmove",g);f.addEventListener("touchend",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);d.addEventListener("click",()=>{var n={isChecked:d.checked};n.elementId=a;E(this,"click",n)});b.id&&(d.id=b.id);this.uc(f,b);return f}xd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}yc(a){return this.xd(a)}uc(a,b){const d=this.xd(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;
a===d?d.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
{const g=180/Math.PI;self.da=class extends self.wb{constructor(a){super(a,"audio");this.Ob=this.f=null;this.Qb=this.Qc=!1;this.qa=()=>this.sg();this.aa=[];this.D=[];this.ga=null;this.Td="";this.Ud=-1;this.ob=new Map;this.Vc=1;this.na=!1;this.ad=0;this.cc=1;this.Oc=0;this.Wd="HRTF";this.Nd="inverse";this.Xd=600;this.Vd=1E4;this.Zd=1;this.Pd=this.Zc=!1;this.be=this.A.Ee();this.ba=new Map;this.Fa=new Set;this.Sc=!1;this.Wc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Ef(b,d);this.Nb=null;
self.C3Audio_GetOutputStream=()=>this.yf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.$e(b)],["play",b=>this.Sf(b)],["stop",b=>this.pg(b)],["stop-all",()=>this.qg()],["set-paused",b=>this.ig(b)],["set-volume",b=>this.ng(b)],["fade-volume",b=>this.ef(b)],["set-master-volume",b=>this.gg(b)],["set-muted",b=>this.hg(b)],["set-silent",b=>this.kg(b)],["set-looping",b=>this.fg(b)],["set-playback-rate",b=>this.jg(b)],["seek",b=>this.Zf(b)],["preload",b=>this.Tf(b)],["unload",b=>
this.tg(b)],["unload-all",()=>this.ug()],["set-suspended",b=>this.lg(b)],["add-effect",b=>this.td(b)],["set-effect-param",b=>this.cg(b)],["remove-effects",b=>this.Vf(b)],["tick",b=>this.Nf(b)],["load-state",b=>this.Cf(b)]])}async $e(a){a.isiOSCordova&&(this.Zc=!0);this.ad=a.timeScaleMode;this.Wd=["equalpower","HRTF","soundfield"][a.panningModel];this.Nd=["linear","inverse","exponential"][a.distanceModel];this.Xd=a.refDistance;this.Vd=a.maxDistance;this.Zd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.be||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.ud();this.f.onstatechange=()=>{"running"!==this.f.state&&this.ud()};this.Ob=this.f.createGain();this.Ob.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.ic();try{await Promise.all(a.preloadList.map(d=>this.Eb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}ud(){this.Qb||(this.Qc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Qb=!0)}bf(){this.Qb&&(this.Qc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Qb=!1)}sg(){if(!this.Qc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.bf()}}W(){return this.f}ic(){return this.f.currentTime}ra(){return this.Ob}ld(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ra()}fe(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.eg(d.length);b.mg(a);d.push(b);this.Fd(a)}Fd(a){let b=this.ra();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let f=0,n=d.length;f<n;++f){const q=d[f];f+1===n?q.S(this.ra()):q.S(d[f+1].P())}}for(const f of this.la(a))f.Le(b);this.ya&&this.Wc===a&&(this.ya.disconnect(),this.ya.connect(b))}yb(){return this.Vc}zb(){return this.na}dg(){this.Pd=!0}ye(a,b){return b?this.A.vg(a).then(d=>{const f=this.f.createBuffer(1,d.length,48E3);f.getChannelData(0).set(d);return f}):
new Promise((d,f)=>{this.f.decodeAudioData(a,d,f)})}ta(a){this.A.ta(a)}Ba(a){this.A.Ba(a)}pd(a){let b=0;for(let d=0,f=this.D.length;d<f;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Me(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const f=this.aa[b];this.aa[a]=f;f.sa()?f.c():++a}this.aa.length=a}*la(a){if(a)for(const b of this.D)self.da.ze(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Eb(a,b,d,f,n){for(const q of this.aa)if(q.Ra()===b)return await U(q),
q;if(n)return null;f&&(this.Zc||this.Pd)&&this.Me();n="audio/webm; codecs=opus"===d&&!this.be;f&&n&&this.dg();a=!f||this.Zc||n?new self.te(this,a,b,d,f,n):new self.re(this,a,b,d,f);this.aa.push(a);await U(a);return a}async xc(a,b,d,f,n){for(const q of this.D)if(q.Ra()===b&&(q.fc()||n))return q.Oe(f),q;a=await this.Eb(a,b,d,n);f="html5"===a.Kc?new self.se(a.i,a,f):new self.ue(a.i,a,f);this.D.push(f);return f}Se(a){let b=this.ob.get(a);if(!b){let d=null;b={cd:0,Kg:new Promise(f=>d=f),resolve:d};this.ob.set(a,
b)}b.cd++}Wf(a){const b=this.ob.get(a);if(!b)throw Error("expected pending tag");b.cd--;0===b.cd&&(b.resolve(),this.ob.delete(a))}tc(a){a||(a=this.Td);return(a=this.ob.get(a))?a.Kg:Promise.resolve()}Fb(){if(0<this.Fa.size)M(this);else for(const a of this.D)if(a.md()){M(this);break}}Ca(){for(var a of this.Fa)a.Ca();a=this.ic();for(var b of this.D)b.Ca(a);b=this.D.filter(d=>d.md()).map(d=>d.Qa());z(this,"state",{tickCount:this.Ud,audioInstances:b,analysers:[...this.Fa].map(d=>d.Be())});0===b.length&&
0===this.Fa.size&&this.Rb&&(this.A.Xf(this.ce),this.Rb=!1)}pc(a,b,d){z(this,"trigger",{type:a,tag:b,aiid:d})}async Sf(a){const b=a.originalUrl,d=a.url,f=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,D=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Td=q;this.Se(q);try{this.ga=await this.xc(b,d,f,q,n),w?(this.ga.Bb(!0),this.ga.Ne(w.x,w.y,w.angle,
w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ga.Pe(w.uid)):this.ga.Bb(!1),this.ga.Play(v,B,D,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Wf(q)}M(this)}pg(a){a=a.tag;for(const b of this.la(a))b.ma()}qg(){for(const a of this.D)a.ma()}ig(a){const b=a.tag;a=a.paused;for(const d of this.la(b))a?d.Ta():d.Ab();this.Fb()}ng(a){const b=a.tag;a=a.vol;for(const d of this.la(b))d.Db(a)}async ef(a){const b=a.tag,d=a.vol,f=a.duration;
a=a.stopOnEnd;await this.tc(b);for(const n of this.la(b))n.Ae(d,f,a);this.Fb()}gg(a){this.Vc=a.vol;for(const b of this.D)b.Kb()}hg(a){const b=a.tag;a=a.isMuted;for(const d of this.la(b))d.qd(a)}kg(a){this.na=a.isSilent;this.A.Cb(this.na);for(const b of this.D)b.Jb()}fg(a){const b=a.tag;a=a.isLooping;for(const d of this.la(b))d.rc(a)}async jg(a){const b=a.tag;a=a.rate;await this.tc(b);for(const d of this.la(b))d.sd(a)}async Zf(a){const b=a.tag;a=a.pos;await this.tc(b);for(const d of this.la(b))d.qc(a)}async Tf(a){const b=
a.originalUrl,d=a.url,f=a.type;a=a.isMusic;try{await this.xc(b,d,f,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async tg(a){if(a=await this.Eb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}ug(){for(const a of this.aa)a.c();this.aa.length=0}lg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.sc(a);a&&this.f.suspend&&this.f.suspend()}Nf(a){this.cc=a.timeScale;this.Oc=a.gameTime;this.Ud=a.tickCount;if(0!==
this.ad)for(var b of this.D)b.Ea();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.D)f.fa===a&&f.rd(d.x,d.y,d.angle)}}async td(a){var b=a.type;const d=a.tag;var f=a.params;if("filter"===b)f=new self.le(this,...f);else if("delay"===b)f=new self.je(this,...f);else if("convolution"===b){b=null;try{b=await this.Eb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}f=new self.ie(this,b.$,...f);f.ag(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.me(this,...f);else if("phaser"===b)f=new self.oe(this,...f);else if("gain"===b)f=new self.ne(this,...f);else if("tremolo"===b)f=new self.qe(this,...f);else if("ringmod"===b)f=new self.pe(this,...f);else if("distortion"===b)f=new self.ke(this,...f);else if("compressor"===b)f=new self.he(this,...f);else if("analyser"===b)f=new self.ge(this,...f);else throw Error("invalid effect type");this.fe(d,
f);this.Ed()}cg(a){const b=a.index,d=a.param,f=a.value,n=a.ramp,q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,n,q),this.Ed())}Vf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Fd(a)}}Re(a){this.Fa.add(a);this.Fb()}Uf(a){this.Fa.delete(a)}Ed(){this.Sc||(this.Sc=!0,Promise.resolve().then(()=>this.cf()))}cf(){const a={};for(const [b,d]of this.ba)a[b]=d.map(f=>f.Qa());z(this,"fxstate",{fxstate:a});this.Sc=!1}async Cf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.sa()&&1===b||(d.sa()||2!==b)&&d.ma();for(const f of this.ba.values())for(const n of f)n.c();this.ba.clear();this.cc=a.timeScale;this.Oc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.na=a.isSilent;this.A.Cb(this.na);this.Vc=a.masterVolume;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(n=>this.td(n))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.mf(f,b)));this.Fb()}async mf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,f=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,w=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.xc(d,f,n,v,q)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Je(a.pan);b.Play(B,D,w,0);a.isPlaying||b.Ta();b.Cc(a)}}}Ef(a,b){this.ya&&this.ya.disconnect();this.Wc=b.toLowerCase();this.ya=this.f.createMediaStreamSource(a);this.ya.connect(this.ld(this.Wc))}yf(){this.Nb||(this.Nb=this.f.createMediaStreamDestination(),
this.Ob.connect(this.Nb));return this.Nb.stream}static ze(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Qe(a){return a*g}static xe(a){return Math.pow(10,a/20)}static kd(a){return Math.max(Math.min(self.da.xe(a),1),0)}static Ie(a){return Math.log(a)/Math.log(10)*20}static He(a){return self.da.Ie(Math.max(Math.min(a,1),0))}static Fg(a,b){return 1-Math.exp(-b*a)}};self.Ua.ub(self.da)}"use strict";function U(g){g.Tb||(g.Tb=g.Bc());return g.Tb}
self.fd=class{constructor(g,a,b,d,f){this.i=g;this.Bg=a;this.za=b;this.R=d;this.yg=f;this.Kc="";this.Tb=null}c(){this.Tb=this.i=null}Bc(){}W(){return this.i.W()}kc(){return this.Bg}Ra(){return this.za}jc(){return this.R}sa(){return this.yg}ea(){}};"use strict";
self.re=class extends self.fd{constructor(g,a,b,d,f){super(g,a,b,d,f);this.Kc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.ib=this.jb=null;this.J.addEventListener("canplaythrough",()=>!0);this.nb=this.W().createGain();this.lb=null;this.J.addEventListener("canplay",()=>{this.jb&&(this.jb(),this.ib=this.jb=null);!this.lb&&this.J&&(this.lb=this.W().createMediaElementSource(this.J),this.lb.connect(this.nb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.za}' error: `,n);this.ib&&(this.ib(n),this.ib=this.jb=null)})}c(){this.i.pd(this);this.nb.disconnect();this.nb=null;this.lb.disconnect();this.lb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Bc(){return new Promise((g,a)=>{this.jb=g;this.ib=a;this.J.src=this.za})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function V(g){if(g.wa)return g.wa;var a=g.i.A;if("cordova"===a.v&&a.nd(g.za)&&a.fb)g.wa=await a.vb(g.za);else{a=await fetch(g.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.wa=await a.arrayBuffer()}}async function W(g){if(g.$)return g.$;g.$=await g.i.ye(g.wa,g.Ag);g.wa=null}
self.te=class extends self.fd{constructor(g,a,b,d,f,n){super(g,a,b,d,f);this.Kc="webaudio";this.$=this.wa=null;this.Ag=!!n}c(){this.i.pd(this);this.$=this.wa=null;super.c()}async Bc(){try{await V(this),await W(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.za}': `,g)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let g=0;self.gd=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Lb=g++;this.M=this.W().createGain();this.M.connect(this.ra());this.B=null;this.gb=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.rb=1;this.Ga=!1;this.pa=1;a=this.i.ad;this.Tc=1===a&&!this.sa()||2===a;this.bb=this.fa=-1;this.ae=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.ld(this.Z)}yb(){return this.i.yb()}xb(){return this.Tc?
this.i.Oc:performance.now()/1E3}kc(){return this.L.kc()}Ra(){return this.L.Ra()}jc(){return this.L.jc()}sa(){return this.L.sa()}Oe(a){this.Z=a}T(){}fc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}md(){return!this.H&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}ma(){}Ta(){}Ab(){}Db(a){this.rb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.lc()}Ae(a,b,d){if(!this.Ga){a*=this.yb();var f=this.M.gain;f.cancelScheduledValues(0);var n=this.i.ic();b=n+b;f.setValueAtTime(f.value,
n);f.linearRampToValueAtTime(a,b);this.rb=a;this.bb=b;this.ae=d}}Kb(){this.Db(this.rb)}Ca(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.ae&&this.ma(),this.i.pc("fade-ended",this.Z,this.Lb))}lc(){const a=this.rb*this.yb();return isFinite(a)?a:0}qd(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Jb())}zb(){return this.i.zb()}Jb(){}rc(){}sd(a){this.pa!==a&&(this.pa=a,this.Ea())}Ea(){}qc(){}sc(){}Bb(a){a=!!a;this.gb!==a&&((this.gb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Wd,this.B.distanceModel=
this.i.Nd,this.B.refDistance=this.i.Xd,this.B.maxDistance=this.i.Vd,this.B.rolloffFactor=this.i.Zd),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ra())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Ne(a,b,d,f,n,q){this.gb&&(this.rd(a,b,d),a=self.da.Qe,this.B.coneInnerAngle=a(f),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}rd(a,b,d){this.gb&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(d),this.ia[1]=Math.sin(d),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Pe(a){this.fa=a}mc(){}Le(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Qa(){return{aiid:this.Lb,tag:this.Z,duration:this.ea(),volume:this.rb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.pa,uid:this.fa,bufferOriginalUrl:this.kc(),bufferUrl:"",bufferType:this.jc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.mc(),pan:this.Ce()}}Cc(a){this.sd(a.playbackRate);this.qd(a.isMuted)}Ce(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Je(a){if(a){this.Bb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.Bb(!1)}}}"use strict";
self.se=class extends self.gd{constructor(g,a,b){super(g,a,b);this.L.nb.connect(this.M);this.L.onended=()=>this.Dc()}c(){this.ma();this.L.nb.disconnect();super.c()}O(){return this.L.O()}Dc(){this.H=!0;this.fa=-1;this.i.pc("ended",this.Z,this.Lb)}T(){return this.O().ended}fc(){return this.H?!0:this.T()}Aa(){let g=this.O().currentTime;this.V||(g=Math.min(g,this.ea()));return g}Play(g,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.Db(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ra()}' to position '${b}': `,f)}this.i.ta(d);this.G=this.H=!1;this.V=g;this.pa=1}ma(){const g=this.O();g.paused||g.pause();this.i.Ba(g);this.H=!0;this.G=!1;this.fa=-1}Ta(){if(!(this.G||this.H||this.T())){var g=this.O();g.paused||g.pause();this.i.Ba(g);this.G=!0}}Ab(){!this.G||this.H||this.T()||(this.i.ta(this.O()),this.G=!1)}Jb(){this.O().muted=this.Ga||this.zb()}rc(g){g=!!g;this.V!==g&&
(this.V=g,this.O().loop=g)}Ea(){let g=this.pa;this.Tc&&(g*=this.i.cc);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}qc(g){if(!this.H&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}mc(){return this.Aa()}sc(g){g?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ta(this.O()),this.ka=!1)}};"use strict";
function X(g){g.j&&g.j.disconnect();g.j=null;g.Ya=null}
self.ue=class extends self.gd{constructor(g,a,b){super(g,a,b);this.j=null;this.Wb=d=>this.Dc(d);this.Pc=!0;this.Ya=null;this.N=this.Xb=this.Yb=0;this.Xc=1}c(){this.ma();X(this);this.Wb=null;super.c()}Dc(g){this.G||this.ka||g.target!==this.Ya||(this.H=this.Pc=!0,this.fa=-1,X(this),this.i.pc("ended",this.Z,this.Lb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Pc}fc(){return!this.j||this.H?!0:this.T()}Aa(){let g;g=this.G?this.N:this.Xb+(this.xb()-this.Yb)*this.pa;this.V||(g=Math.min(g,this.ea()));
return g}Play(g,a,b,d){this.Xc=1;this.Db(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Wb;this.j.loop=g;this.j.start(d,b);this.G=this.H=this.Pc=!1;this.V=g;this.pa=1;this.Yb=this.xb();this.Xb=b}ma(){if(this.j)try{this.j.stop(0)}catch(g){}this.H=!0;this.G=!1;this.fa=-1}Ta(){this.G||this.H||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Ab(){!this.G||this.H||this.T()||(X(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Kb(),this.Ea(),this.j.start(0,this.N),this.Yb=this.xb(),this.Xb=this.N,this.G=!1)}lc(){return super.lc()*this.Xc}Jb(){this.Xc=this.Ga||this.zb()?0:1;this.Kb()}rc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Ea(){let g=this.pa;this.Tc&&(g*=this.i.cc);this.j&&(this.j.playbackRate.value=g)}qc(g){this.H||this.T()||(this.G?this.N=g:(this.Ta(),this.N=g,this.Ab()))}mc(){return this.N}sc(g){g?
this.IsPlaying()?(this.ka=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Kb(),this.Ea(),this.j.start(0,this.N),this.Yb=this.xb(),this.Xb=this.N,this.ka=!1)}Cc(g){super.Cc(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.f=a.W();this.Qd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}eg(a){this.Qd=a}mg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var n=this.f.currentTime;f+=n;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,f)}}}Qa(){return{type:this.R,tag:this.Z,params:this.g}}}
self.le=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.R="filter";this.g=[b,d,f,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=f;this.u.Q.value=n;this.u.gain.vlaue=q;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,f)}}};self.je=class extends g{constructor(a,b,d,f){super(a);this.R="delay";this.g=[b,d,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.kb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=d;this.l.connect(this.kb);this.l.connect(this.a);this.kb.connect(this.b);this.kb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.kb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.kb.disconnect();this.U.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){const n=self.da.kd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 4:this.g[1]=n(b);this.m(this.ab.gain,n(b),d,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,f)}}};self.ie=class extends g{constructor(a,b,d,f){super(a);this.R="convolution";this.g=[d,f];this.Ld=this.Kd="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.$a=this.f.createConvolver();this.$a.normalize=d;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}c(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}ag(a,b){this.Kd=a;this.Ld=b}Qa(){const a=
super.Qa();a.bufferOriginalUrl=this.Kd;a.bufferUrl="";a.bufferType=this.Ld;return a}};self.me=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="flanger";this.g=[b,d,f,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.cb=this.o();this.cb.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,d,f)}}};self.oe=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.R="phaser";this.g=[b,d,f,n,q,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=q;this.I=this.o();this.I.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,f)}}};self.ne=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){const n=self.da.kd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,f)}}};self.qe=class extends g{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,f);this.m(this.I.gain,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.pe=class extends g{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.qb=this.o();this.qb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.qb.gain);this.s.start(0);this.l.connect(this.qb);this.l.connect(this.a);this.qb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.qb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,f);
this.m(this.a.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.ke=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="distortion";this.g=[b,d,f,n,q];this.l=this.o();this.$b=this.o();this.Zb=this.o();this.bg(f,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.dc=this.f.createWaveShaper();this.Mc=new Float32Array(65536);this.gf(b,d);this.dc.curve=this.Mc;this.l.connect(this.$b);this.l.connect(this.a);this.$b.connect(this.dc);this.dc.connect(this.Zb);
this.Zb.connect(this.b)}c(){this.l.disconnect();this.$b.disconnect();this.dc.disconnect();this.Zb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}bg(a,b){.01>a&&(a=.01);this.$b.gain.value=a;this.Zb.gain.value=Math.pow(1/a,.6)*b}gf(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.og(f,a,b);this.Mc[32768+d]=f;this.Mc[32768-d-1]=-f}}og(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.da.Fg(f-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}};self.he=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="compressor";this.g=[b,d,f,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ge=class extends g{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Od=new Float32Array(this.h.frequencyBinCount);this.$d=new Uint8Array(b);this.Yd=this.Ja=0;this.i.Re(this)}c(){this.i.Uf(this);this.h.disconnect();super.c()}Ca(){this.h.getFloatFrequencyData(this.Od);this.h.getByteTimeDomainData(this.$d);const a=this.h.fftSize;let b=this.Ja=0;for(var d=0;d<a;++d){let f=(this.$d[d]-128)/128;0>f&&(f=-f);
this.Ja<f&&(this.Ja=f);b+=f*f}d=self.da.He;this.Ja=d(this.Ja);this.Yd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Be(){return{tag:this.Z,index:this.Qd,peak:this.Ja,rms:this.Yd,binCount:this.h.frequencyBinCount,freqBins:this.Od}}}}"use strict";async function Y(g,a){a=a.type;let b=!0;0===a?b=await Z():1===a&&(b=await aa());z(g,"permission-result",{type:a,result:b})}
async function Z(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function aa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.Ua.ub(class extends self.wb{constructor(g){super(g,"touch");J(this,"request-permission",a=>Y(this,a))}});
